[workspace]
members = ["crates/nana-ui", "crates/nana-window", "examples/component-gallery"]
resolver = "2"

[workspace.dependencies]
iced = {
    git = "https://github.com/sena-nana/iced.git",
    rev = "a3bdc6f5f09ff9aec50c57273fc7eb21fd370603",
    default-features = false,
    features = ["wgpu", "canvas", "advanced", "smol", "thread-pool", "x11", "wayland"],
}
iced_wgpu = {
    git = "https://github.com/sena-nana/iced.git",
    rev = "a3bdc6f5f09ff9aec50c57273fc7eb21fd370603",
}
iced_winit = {
    git = "https://github.com/sena-nana/iced.git",
    rev = "a3bdc6f5f09ff9aec50c57273fc7eb21fd370603",
}
