[workspace]
members = ["crates/nana-ui", "crates/nana-window", "examples/component-gallery"]
resolver = "2"

[workspace.dependencies]
iced = {
    git = "https://github.com/sena-nana/iced.git",
    rev = "31bde4e4bac6de08f5ba581a8ea9c55ad0031e67",
    default-features = false,
    features = ["wgpu", "canvas", "advanced", "smol", "thread-pool", "x11", "wayland"],
}
iced_wgpu = {
    git = "https://github.com/sena-nana/iced.git",
    rev = "31bde4e4bac6de08f5ba581a8ea9c55ad0031e67",
}
iced_winit = {
    git = "https://github.com/sena-nana/iced.git",
    rev = "31bde4e4bac6de08f5ba581a8ea9c55ad0031e67",
}
