#!/usr/bin/env python3
"""Performance contract entry point. CLI, JSON schema and exit codes are stable."""
from contract_support.cli import (
    add_common_args,
    main,
    run_cli,
    selected_ids,
    write_one,
)
from contract_support.comparison import (
    compare_issue12_pair,
    evaluate_relative_paths,
    load_issue12_report,
    named_fixed_machine,
    relative_gate_can_enforce,
)
from contract_support.extractors import (
    extract_gpui,
    extract_iced,
    extract_nana,
    gpui_unsupported,
)
from contract_support.invariants import (
    compare_invariant,
    counters_from_block,
    evaluate_invariants,
    evaluate_runner_invariant_paths,
    expand_invariant_report_paths,
    gpu_counters_from_observed,
    is_runner_envelope,
    judge_runner_invariants,
    lookup_path,
    machine_note,
    read_frames_after_idle,
)
from contract_support.process import (
    cargo_run,
    run_command,
)
from contract_support.reports import (
    envelope,
    find_case_by_nodes,
    key_error_reason,
    measured_counters,
    percentile_fields,
)
from contract_support.schema import (
    CATALOG_PATH,
    EXIT_ERROR,
    EXIT_OK,
    EXIT_UNSUPPORTED,
    GPUI_SNAPSHOT_REMOVED_REASON,
    GPU_COMPOSITIONS,
    GPU_HOST_STAGES,
    GPU_WORK_COUNTER_KEYS,
    ICED_SAME_SCENARIO_MUTATION_KINDS,
    ICED_SNAPSHOT_REMOVED_REASON,
    ICED_UNSUPPORTED_ANIMATION_REASON,
    ICED_UNSUPPORTED_DOCK_REASON,
    ICED_UNSUPPORTED_GPU_SCENE_REASON,
    ICED_UNSUPPORTED_IME_REASON,
    ICED_UNSUPPORTED_MUTATION_KINDS,
    ICED_UNSUPPORTED_MUTATION_REASON,
    ICED_UNSUPPORTED_OVERLAY_REASON,
    ICED_UNSUPPORTED_TEXT_EDITOR_REASON,
    ICED_UNSUPPORTED_VIRTUAL_TREE_REASON,
    INCOMPARABLE_STATIC_TREE_50K,
    INCOMPARABLE_STATIC_TREE_50K_REASON,
    ISSUE12_FIXTURE_IDS,
    KIND_PARAM_KEYS,
    MUTATION_KINDS,
    NANA_LIST_CATALOG_WINDOW_FIELDS,
    NANA_TABLE_CATALOG_WINDOW_FIELDS,
    NANA_TABLE_COLUMN_EXTENT_PX,
    NANA_TABLE_ROW_EXTENT_PX,
    PERF_ROOT,
    PR_INVARIANTS_DIR_NAME,
    RELATIVE_CPU_LIMITS,
    RELATIVE_MEMORY_LIMIT,
    REPO_ROOT,
    REQUIRED_HOVER_NODES,
    REQUIRED_MUTATION_NODES,
    REQUIRED_TABLE_COLUMNS,
    REQUIRED_TABLE_OVERSCAN_COLUMNS,
    REQUIRED_TABLE_OVERSCAN_ROWS,
    REQUIRED_TABLE_ROWS,
    REQUIRED_TABLE_VISIBLE_COLUMNS,
    REQUIRED_TABLE_VISIBLE_ROWS,
    SCENARIO_DIR,
    SCHEMA_VERSION,
    SECTION_8_1_CATALOG_WORKLOAD_IDS,
    SECTION_8_1_HONEST_OK_IDS,
    SECTION_8_1_STATIC_UI_IDS,
    SECTION_8_1_UNSUPPORTED_IDS,
    SECTION_8_1_WEEKLY_UBUNTU_IDS,
    STATIC_TREE_GENERATION,
    STATIC_TREE_NODE_KIND,
    STATIC_TREE_PARENT_RULE,
    TEXT_TABLE_CACHE_GAPS,
    TEXT_TABLE_EXPORTED_SHAPE_KEYS,
    UsageError,
    WORK_COUNTER_KEYS,
    catalog_table_live_bound,
    catalog_table_window,
    catalog_uniform_window_item_cap,
    catalog_virtual_list_live_bound,
    catalog_virtual_list_window,
    dump_json,
    gpui_scenario_bench_skip_reason,
    iced_scenario_bench_skip_reason,
    is_gpui_scenario_bench_report,
    is_iced_scenario_bench_report,
    is_incomparable_static_tree_50k,
    is_shared_static_tree,
    list_harness_ids,
    load_catalog,
    load_json,
    load_scenario,
    nana_catalog_window_equivalence,
    nana_framework_list_window_args,
    nana_framework_table_window_args,
    nana_gpu_scene_skip_reason,
    nana_list_catalog_window_equivalence,
    nana_table_catalog_window_equivalence,
    repo_root_from,
    scenario_path,
    static_tree_children,
    static_tree_parent,
    static_tree_sample_parents,
    validate_all_scenarios,
    validate_scenario,
)

def self_test(root=None):
    from contract_support.self_tests import self_test as run
    return run(root)

if __name__ == "__main__":
    raise SystemExit(main())
