import { defineConfig } from "vitepress";
import { apiStylePlugin } from "./plugins/api-style";

const restoreStyle = `(function(){try{var s=localStorage.getItem('nanaui-docs-style');document.documentElement.classList.add(s==='rust'?'prefer-rust':'prefer-view')}catch(e){document.documentElement.classList.add('prefer-view')}})();`;

export default defineConfig({
  lang: "zh-CN",
  title: "NanaUI",
  description: "易上手的桌面界面框架。一棵界面树，窗口和 GPU 由你的应用持有。",
  cleanUrls: true,
  ignoreDeadLinks: [/^https?:\/\//, /archive\/docs-notes/, /\.\.\/\.\.\//],
  head: [["script", {}, restoreStyle]],
  markdown: {
    config(md) {
      apiStylePlugin(md);
    },
  },
  themeConfig: {
    search: { provider: "local" },
    outline: { label: "本页目录", level: [2, 3] },
    docFooter: { prev: "上一页", next: "下一页" },
    sidebarMenuLabel: "菜单",
    darkModeSwitchLabel: "外观",
    returnToTopLabel: "回到顶部",
    nav: [
      { text: "指南", link: "/guide/introduction", activeMatch: "/guide/" },
      { text: "组件", link: "/components/", activeMatch: "/components/" },
      { text: "架构", link: "/architecture/", activeMatch: "/architecture/" },
      {
        text: "参考",
        link: "/reference/how-it-works",
        activeMatch: "/reference/(?!theme|text-engine|input-conformance|input-cost|third-party)",
      },
      {
        text: "维护者",
        link: "/reference/theme",
        activeMatch: "/reference/(theme|text-engine|input-conformance|input-cost|third-party)",
      },
    ],
    sidebar: {
      "/guide/": [
        {
          text: "开始",
          items: [
            { text: "介绍", link: "/guide/introduction" },
            { text: "快速开始", link: "/guide/quick-start" },
            { text: "从 Vue 过来", link: "/guide/from-vue" },
            { text: "示例", link: "/guide/examples" },
          ],
        },
        {
          text: "基础",
          items: [
            { text: "创建应用", link: "/guide/essentials/application" },
            { text: "视图写法", link: "/guide/essentials/view" },
            { text: "响应式", link: "/guide/essentials/reactivity" },
            { text: "计算值", link: "/guide/essentials/computed" },
            { text: "侦听", link: "/guide/essentials/watch" },
            { text: "类与样式", link: "/guide/essentials/class-and-style" },
            { text: "条件", link: "/guide/essentials/conditional" },
            { text: "列表", link: "/guide/essentials/list" },
            { text: "事件", link: "/guide/essentials/events" },
            { text: "表单绑定", link: "/guide/essentials/forms" },
            { text: "句柄", link: "/guide/essentials/refs" },
            { text: "挂载与卸载", link: "/guide/essentials/lifecycle" },
          ],
        },
        {
          text: "组件深入",
          items: [
            { text: "组合视图", link: "/guide/essentials/view-functions" },
            { text: "依赖提供", link: "/guide/components/provide" },
            { text: "扩展控件", link: "/guide/components/registry" },
            { text: "属性", link: "/guide/components/props" },
            { text: "事件", link: "/guide/components/events" },
            { text: "双向绑定", link: "/guide/components/v-model" },
            { text: "具名 slot", link: "/guide/components/slots" },
            { text: "异步", link: "/guide/components/async" },
          ],
        },
        {
          text: "内置",
          items: [
            { text: "Transition", link: "/guide/built-ins/transition" },
            { text: "KeepAlive", link: "/guide/built-ins/keep-alive" },
            { text: "Teleport", link: "/guide/built-ins/teleport" },
            { text: "Suspense", link: "/guide/built-ins/suspense" },
          ],
        },
        {
          text: "进阶",
          items: [
            { text: ".vue 方言", link: "/guide/scaling/sfc" },
            { text: "热重载", link: "/guide/scaling/hot-reload" },
            { text: "Store", link: "/guide/scaling/store" },
            { text: "打包", link: "/guide/scaling/packaging" },
            { text: "性能", link: "/guide/scaling/performance" },
            { text: "无障碍", link: "/guide/scaling/accessibility" },
            { text: "Fetch", link: "/guide/scaling/fetch" },
          ],
        },
      ],
      "/components/": [
        {
          text: "组件",
          items: [{ text: "总览", link: "/components/" }],
        },
        {
          text: "操作与输入",
          items: [
            { text: "Button", link: "/components/button" },
            { text: "IconButton", link: "/components/icon-button" },
            { text: "TextInput", link: "/components/text-input" },
            { text: "TextArea", link: "/components/text-area" },
            { text: "NumberInput", link: "/components/number-input" },
            { text: "Checkbox", link: "/components/checkbox" },
            { text: "Switch", link: "/components/switch" },
            { text: "RangeField", link: "/components/range-field" },
            { text: "Select", link: "/components/select" },
            { text: "Dropdown", link: "/components/dropdown" },
            { text: "SearchDropdown", link: "/components/search-dropdown" },
            { text: "SegmentedControl", link: "/components/segmented-control" },
            { text: "Tabs", link: "/components/tabs" },
            { text: "XYPad", link: "/components/xy-pad" },
            { text: "ColorField", link: "/components/color-field" },
            { text: "PathField", link: "/components/path-field" },
            { text: "DatePicker", link: "/components/date-picker" },
          ],
        },
        {
          text: "布局与文本",
          items: [
            { text: "Text", link: "/components/text" },
            { text: "RichTextView", link: "/components/rich-text-view" },
            { text: "RichTextEditor", link: "/components/rich-text-editor" },
            { text: "Column", link: "/components/column" },
            { text: "Row", link: "/components/row" },
            { text: "Stack", link: "/components/stack" },
            { text: "Divider", link: "/components/divider" },
            { text: "IconGlyph", link: "/components/icon-glyph" },
            { text: "ScrollView", link: "/components/scroll-view" },
          ],
        },
        {
          text: "表格与树",
          items: [
            { text: "Table", link: "/components/table" },
            { text: "TreeView", link: "/components/tree-view" },
            { text: "ReorderList", link: "/components/reorder-list" },
          ],
        },
        {
          text: "展示",
          items: [
            { text: "Card", link: "/components/card" },
            { text: "List", link: "/components/list" },
            { text: "ListItem", link: "/components/list-item" },
            { text: "FormField", link: "/components/form-field" },
            { text: "EmptyState", link: "/components/empty-state" },
            { text: "Progress", link: "/components/progress" },
            { text: "Skeleton", link: "/components/skeleton" },
            { text: "Spinner", link: "/components/spinner" },
            { text: "StatusBadge", link: "/components/status-badge" },
            { text: "Chip", link: "/components/chip" },
            { text: "Avatar", link: "/components/avatar" },
            { text: "Thumbnail", link: "/components/thumbnail" },
            { text: "Texture", link: "/components/texture" },
            { text: "Tooltip", link: "/components/tooltip" },
            { text: "ValidationMessage", link: "/components/validation-message" },
            { text: "QrCode", link: "/components/qr-code" },
            { text: "ImageViewer", link: "/components/image-viewer" },
            { text: "NativeMarkdown", link: "/components/native-markdown" },
            { text: "CalendarHeatmap", link: "/components/calendar-heatmap" },
            { text: "TimeSeriesChart", link: "/components/time-series-chart" },
            { text: "DonutChart", link: "/components/donut-chart" },
            { text: "GraphCanvas", link: "/components/graph-canvas" },
            { text: "GraphMinimap", link: "/components/graph-minimap" },
          ],
        },
        {
          text: "浮层",
          items: [
            { text: "Dialog", link: "/components/dialog" },
            { text: "ConfirmDialog", link: "/components/confirm-dialog" },
            { text: "Drawer", link: "/components/drawer" },
            { text: "Popover", link: "/components/popover" },
            { text: "ActionMenu", link: "/components/action-menu" },
            { text: "ContextMenu", link: "/components/context-menu" },
            { text: "CommandPalette", link: "/components/command-palette" },
          ],
        },
        {
          text: "壳层",
          items: [
            { text: "AppShell", link: "/components/app-shell" },
            { text: "DesktopShell", link: "/components/desktop-shell" },
            { text: "AppTitleBar", link: "/components/app-title-bar" },
            { text: "Toolbar", link: "/components/toolbar" },
            { text: "StatusBar", link: "/components/status-bar" },
            { text: "MediaTransportBar", link: "/components/media-transport-bar" },
            { text: "Workspace", link: "/components/workspace" },
            { text: "SidebarFrame", link: "/components/sidebar-frame" },
            { text: "SidebarSection", link: "/components/sidebar-section" },
            { text: "SidebarRow", link: "/components/sidebar-row" },
            { text: "SettingsRow", link: "/components/settings-row" },
            { text: "Dock", link: "/components/dock" },
            { text: "SplitPane", link: "/components/split-pane" },
            { text: "PaneChrome", link: "/components/pane-chrome" },
          ],
        },
      ],
      "/architecture/": [
        {
          text: "架构",
          items: [
            { text: "总览", link: "/architecture/" },
            { text: "一帧", link: "/architecture/frame" },
            { text: "实时画面", link: "/architecture/gpu" },
            { text: "文本", link: "/architecture/text" },
            { text: "窗口", link: "/architecture/window" },
          ],
        },
      ],
      "/reference/": [
        {
          text: "查阅",
          items: [
            { text: "框架如何运行", link: "/reference/how-it-works" },
            { text: "应用 API", link: "/reference/application-api" },
            { text: "声明式视图", link: "/reference/reactive-view" },
            { text: "L3 建树", link: "/reference/l3-authoring" },
            { text: "Vue", link: "/reference/vue" },
            { text: "Vue 窗口", link: "/reference/vue-windows" },
            { text: "Vue 宿主边界", link: "/reference/vue-host" },
            { text: "布局（CSS 子集）", link: "/reference/layout" },
            { text: "布局（Rust）", link: "/reference/rust-layout" },
            { text: "布局结果合同", link: "/reference/layout-result" },
            { text: "诊断码", link: "/reference/errors" },
          ],
        },
        {
          text: "界面合同",
          items: [
            { text: "控件", link: "/reference/components" },
            { text: "工作区", link: "/reference/workspace" },
            { text: "视觉", link: "/reference/look" },
            { text: "窗口", link: "/reference/window" },
            { text: "两阶段启动", link: "/reference/startup" },
          ],
        },
        {
          text: "宿主与绘制",
          items: [
            { text: "实时画面", link: "/reference/gpu" },
            { text: "Runtime 与 Scene", link: "/reference/runtime-scene" },
            { text: "架构合同", link: "/reference/architecture" },
            { text: "Markdown 绘制", link: "/reference/markdown-rendering" },
            { text: "诊断", link: "/reference/diagnostics" },
            { text: "打包", link: "/reference/packaging" },
            { text: "热重载", link: "/reference/hot-reload" },
            { text: "Android", link: "/reference/android" },
          ],
        },
        {
          text: "维护者笔记",
          collapsed: true,
          items: [
            { text: "主题审计记录", link: "/reference/theme" },
            { text: "文本引擎", link: "/reference/text-engine" },
            { text: "输入验收矩阵", link: "/reference/input-conformance" },
            { text: "输入成本", link: "/reference/input-cost" },
            { text: "第三方代码与许可证", link: "/reference/third-party" },
          ],
        },
      ],
    },
  },
});
