#!/usr/bin/env python3
"""Generate the full Tabler outline icon catalog crate (crates/nana-icons-tabler).

The crate is a generated, committed artifact: consumers build offline, compile
only the icons they reference into their binaries, and the full set stays one
`Icon` constant away. Sources are fetched once per version from the npm tarball
( MIT ) and cached under target/; regeneration is `python3 scripts/generate_tabler_catalog.py`.
"""

from __future__ import annotations

import io
import re
import ssl
import subprocess
import sys
import tarfile
import urllib.request
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import generate_tabler_icons as shared  # SVG -> IconShape/svg converter core

TABLER_VERSION = "3.46.0"
TARBALL_URL = f"https://registry.npmjs.org/@tabler/icons/-/icons-{TABLER_VERSION}.tgz"
ROOT = Path(__file__).resolve().parents[1]
CRATE = ROOT / "crates/nana-icons-tabler"
OUT = CRATE / "src/lib.rs"
CACHE = ROOT / "target/tabler-cache"

CTX = ssl.create_default_context()


def fetch_tarball() -> bytes:
    CACHE.mkdir(parents=True, exist_ok=True)
    cached = CACHE / f"tabler-icons-{TABLER_VERSION}.tgz"
    if not cached.exists():
        print(f"download {TARBALL_URL}")
        with urllib.request.urlopen(TARBALL_URL, context=CTX, timeout=120) as response:
            cached.write_bytes(response.read())
    return cached.read_bytes()


def load_svgs(blob: bytes) -> dict[str, str]:
    svgs: dict[str, str] = {}
    with tarfile.open(fileobj=io.BytesIO(blob), mode="r:gz") as tar:
        for member in tar.getmembers():
            if member.isfile() and re.fullmatch(
                r"package/icons/outline/[^/]+\.svg", member.name
            ):
                name = Path(member.name).stem
                svgs[name] = tar.extractfile(member).read().decode("utf-8")
    return svgs


def const_name(icon: str) -> str:
    return icon.replace("-", "_").upper()


def emit_icon(ident: str, icon: str, svg: str) -> str:
    statics, shapes = shared.parse_svg(svg)
    rewritten = [b.replace("TMP_PATH_", f"{ident}_PATH_") for b in statics]
    shapes = [s.replace("TMP_PATH_", f"{ident}_PATH_") for s in shapes]
    shape_body = ",\n        ".join(f"IconShape::{s}" for s in shapes)
    svg_raw = shared.rust_raw(shared.compact_svg(svg))
    return "\n".join(
        rewritten
        + [
            f"static {ident}_SHAPES: &[IconShape] = &[\n        {shape_body},\n    ];",
            f"static {ident}_SVG: &str = {svg_raw};",
            (
                f"pub static {ident}_ICON: IconData = IconData {{\n"
                f'        name: "{icon}",\n'
                f"        shapes: {ident}_SHAPES,\n"
                f"        svg: {ident}_SVG,\n"
                "    };"
            ),
        ]
    )


def main() -> None:
    svgs = load_svgs(fetch_tarball())
    names = sorted(svgs)

    header = [
        f"// @generated by scripts/generate_tabler_catalog.py from @tabler/icons {TABLER_VERSION} (MIT).",
        "// Do not edit by hand. Consumers reference the root `Icon` constants; the",
        "// linker drops every unreferenced icon, so only used geometry reaches binaries.",
        "// Icons whose source contains `fill=\"currentColor\"` sub-shapes paint exactly",
        "// (rasterized by resvg); their `IconShape` test geometry approximates fills.",
        "#![allow(non_upper_case_globals)]",
        "#![allow(clippy::approx_constant)] // arc-to-cubic control points land near pi/tau",
        "use nana_ui_core::icon::Icon;",
        "mod data {",
        "    use nana_ui_core::icon::{IconData, IconPathCommand, IconShape};",
    ]
    body: list[str] = []
    consts: list[str] = []
    seen: dict[str, str] = {}

    for icon in names:
        ident = const_name(icon)
        try:
            block = emit_icon(ident, icon, svgs[icon])
        except Exception as error:  # noqa: BLE001 - report and abort on any icon
            raise SystemExit(f"{icon}: generation failed: {error}") from error
        for match in re.finditer(r"static ([A-Z0-9_]+):", block):
            static = match.group(1)
            if static in seen:
                raise SystemExit(
                    f"{icon}: static {static} collides with {seen[static]}; "
                    "adjust the catalog naming scheme"
                )
            seen[static] = icon
        body.append(block)
        consts.append(f"pub const {ident}: Icon = Icon::from_data(&data::{ident}_ICON);")

    chunks = (
        header
        + body
        + ["}"]
        + consts
        + [f"pub fn count() -> u32 {{ {len(body)} }}"]
    )
    OUT.write_text("\n".join(chunks) + "\n", encoding="utf-8")
    print(f"emitted {len(body)} icons -> {OUT}")

    subprocess.run(
        ["cargo", "fmt", "--manifest-path", str(CRATE / "Cargo.toml")],
        check=True,
    )


if __name__ == "__main__":
    main()
