// @generated by scripts/generate_lucide_icons.py from lucide-static 0.544.0.
// Do not edit by hand. SVG sources are not embedded.
use crate::icon::{Icon, IconData, IconPathCommand, IconShape};

static ABOUT_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([12.0, 16.0]),
    IconPathCommand::LineTo([12.0, 12.0]),
];
static ABOUT_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([12.0, 8.0]),
    IconPathCommand::LineTo([12.01, 8.0]),
];
static ABOUT_SHAPES: &[IconShape] = &[
    IconShape::Circle {
        center: [12.0, 12.0],
        radius: 10.0,
    },
    IconShape::Path(ABOUT_PATH_0),
    IconShape::Path(ABOUT_PATH_1),
];
static ABOUT: IconData = IconData {
    name: "info",
    shapes: ABOUT_SHAPES,
};

static ADD_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([5.0, 12.0]),
    IconPathCommand::LineTo([19.0, 12.0]),
];
static ADD_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([12.0, 5.0]),
    IconPathCommand::LineTo([12.0, 19.0]),
];
static ADD_SHAPES: &[IconShape] = &[IconShape::Path(ADD_PATH_0), IconShape::Path(ADD_PATH_1)];
static ADD: IconData = IconData {
    name: "plus",
    shapes: ADD_SHAPES,
};

static APPEARANCE_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([12.0, 2.0]),
    IconPathCommand::LineTo([12.0, 4.0]),
];
static APPEARANCE_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([12.0, 20.0]),
    IconPathCommand::LineTo([12.0, 22.0]),
];
static APPEARANCE_PATH_2: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([4.93, 4.93]),
    IconPathCommand::LineTo([6.34, 6.34]),
];
static APPEARANCE_PATH_3: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([17.66, 17.66]),
    IconPathCommand::LineTo([19.07, 19.07]),
];
static APPEARANCE_PATH_4: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([2.0, 12.0]),
    IconPathCommand::LineTo([4.0, 12.0]),
];
static APPEARANCE_PATH_5: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([20.0, 12.0]),
    IconPathCommand::LineTo([22.0, 12.0]),
];
static APPEARANCE_PATH_6: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([6.34, 17.66]),
    IconPathCommand::LineTo([4.93, 19.07]),
];
static APPEARANCE_PATH_7: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([19.07, 4.93]),
    IconPathCommand::LineTo([17.66, 6.34]),
];
static APPEARANCE_SHAPES: &[IconShape] = &[
    IconShape::Circle {
        center: [12.0, 12.0],
        radius: 4.0,
    },
    IconShape::Path(APPEARANCE_PATH_0),
    IconShape::Path(APPEARANCE_PATH_1),
    IconShape::Path(APPEARANCE_PATH_2),
    IconShape::Path(APPEARANCE_PATH_3),
    IconShape::Path(APPEARANCE_PATH_4),
    IconShape::Path(APPEARANCE_PATH_5),
    IconShape::Path(APPEARANCE_PATH_6),
    IconShape::Path(APPEARANCE_PATH_7),
];
static APPEARANCE: IconData = IconData {
    name: "sun",
    shapes: APPEARANCE_SHAPES,
};

static ARROW_LEFT_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([12.0, 19.0]),
    IconPathCommand::LineTo([5.0, 12.0]),
    IconPathCommand::LineTo([12.0, 5.0]),
];
static ARROW_LEFT_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([19.0, 12.0]),
    IconPathCommand::LineTo([5.0, 12.0]),
];
static ARROW_LEFT_SHAPES: &[IconShape] = &[
    IconShape::Path(ARROW_LEFT_PATH_0),
    IconShape::Path(ARROW_LEFT_PATH_1),
];
static ARROW_LEFT: IconData = IconData {
    name: "arrow-left",
    shapes: ARROW_LEFT_SHAPES,
};

static ARROW_RIGHT_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([5.0, 12.0]),
    IconPathCommand::LineTo([19.0, 12.0]),
];
static ARROW_RIGHT_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([12.0, 5.0]),
    IconPathCommand::LineTo([19.0, 12.0]),
    IconPathCommand::LineTo([12.0, 19.0]),
];
static ARROW_RIGHT_SHAPES: &[IconShape] = &[
    IconShape::Path(ARROW_RIGHT_PATH_0),
    IconShape::Path(ARROW_RIGHT_PATH_1),
];
static ARROW_RIGHT: IconData = IconData {
    name: "arrow-right",
    shapes: ARROW_RIGHT_SHAPES,
};

static ARROW_UP_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([5.0, 12.0]),
    IconPathCommand::LineTo([12.0, 5.0]),
    IconPathCommand::LineTo([19.0, 12.0]),
];
static ARROW_UP_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([12.0, 19.0]),
    IconPathCommand::LineTo([12.0, 5.0]),
];
static ARROW_UP_SHAPES: &[IconShape] = &[
    IconShape::Path(ARROW_UP_PATH_0),
    IconShape::Path(ARROW_UP_PATH_1),
];
static ARROW_UP: IconData = IconData {
    name: "arrow-up",
    shapes: ARROW_UP_SHAPES,
};

static BOT_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([12.0, 8.0]),
    IconPathCommand::LineTo([12.0, 4.0]),
    IconPathCommand::LineTo([8.0, 4.0]),
];
static BOT_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([2.0, 14.0]),
    IconPathCommand::LineTo([4.0, 14.0]),
];
static BOT_PATH_2: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([20.0, 14.0]),
    IconPathCommand::LineTo([22.0, 14.0]),
];
static BOT_PATH_3: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([15.0, 13.0]),
    IconPathCommand::LineTo([15.0, 15.0]),
];
static BOT_PATH_4: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([9.0, 13.0]),
    IconPathCommand::LineTo([9.0, 15.0]),
];
static BOT_SHAPES: &[IconShape] = &[
    IconShape::Path(BOT_PATH_0),
    IconShape::RoundedRect {
        origin: [4.0, 8.0],
        size: [16.0, 12.0],
        radius: 2.0,
    },
    IconShape::Path(BOT_PATH_1),
    IconShape::Path(BOT_PATH_2),
    IconShape::Path(BOT_PATH_3),
    IconShape::Path(BOT_PATH_4),
];
static BOT: IconData = IconData {
    name: "bot",
    shapes: BOT_SHAPES,
};

static CHEVRON_DOWN_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([6.0, 9.0]),
    IconPathCommand::LineTo([12.0, 15.0]),
    IconPathCommand::LineTo([18.0, 9.0]),
];
static CHEVRON_DOWN_SHAPES: &[IconShape] = &[IconShape::Path(CHEVRON_DOWN_PATH_0)];
static CHEVRON_DOWN: IconData = IconData {
    name: "chevron-down",
    shapes: CHEVRON_DOWN_SHAPES,
};

static CHEVRON_RIGHT_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([9.0, 18.0]),
    IconPathCommand::LineTo([15.0, 12.0]),
    IconPathCommand::LineTo([9.0, 6.0]),
];
static CHEVRON_RIGHT_SHAPES: &[IconShape] = &[IconShape::Path(CHEVRON_RIGHT_PATH_0)];
static CHEVRON_RIGHT: IconData = IconData {
    name: "chevron-right",
    shapes: CHEVRON_RIGHT_SHAPES,
};

static CHEVRON_UP_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([18.0, 15.0]),
    IconPathCommand::LineTo([12.0, 9.0]),
    IconPathCommand::LineTo([6.0, 15.0]),
];
static CHEVRON_UP_SHAPES: &[IconShape] = &[IconShape::Path(CHEVRON_UP_PATH_0)];
static CHEVRON_UP: IconData = IconData {
    name: "chevron-up",
    shapes: CHEVRON_UP_SHAPES,
};

static CHART_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([3.0, 3.0]),
    IconPathCommand::LineTo([3.0, 19.0]),
    IconPathCommand::CubicTo {
        control_a: [3.0, 20.1046],
        control_b: [3.8954, 21.0],
        to: [5.0, 21.0],
    },
    IconPathCommand::LineTo([21.0, 21.0]),
];
static CHART_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([19.0, 9.0]),
    IconPathCommand::LineTo([14.0, 14.0]),
    IconPathCommand::LineTo([10.0, 10.0]),
    IconPathCommand::LineTo([7.0, 13.0]),
];
static CHART_SHAPES: &[IconShape] = &[IconShape::Path(CHART_PATH_0), IconShape::Path(CHART_PATH_1)];
static CHART: IconData = IconData {
    name: "chart-line",
    shapes: CHART_SHAPES,
};

static CLOSE_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([18.0, 6.0]),
    IconPathCommand::LineTo([6.0, 18.0]),
];
static CLOSE_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([6.0, 6.0]),
    IconPathCommand::LineTo([18.0, 18.0]),
];
static CLOSE_SHAPES: &[IconShape] = &[IconShape::Path(CLOSE_PATH_0), IconShape::Path(CLOSE_PATH_1)];
static CLOSE: IconData = IconData {
    name: "x",
    shapes: CLOSE_SHAPES,
};

static EYE_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([2.062, 12.348]),
    IconPathCommand::CubicTo {
        control_a: [1.9787, 12.1235],
        control_b: [1.9787, 11.8765],
        to: [2.062, 11.652],
    },
    IconPathCommand::CubicTo {
        control_a: [3.722, 7.6269],
        control_b: [7.646, 5.0006],
        to: [12.0, 5.0006],
    },
    IconPathCommand::CubicTo {
        control_a: [16.354, 5.0006],
        control_b: [20.278, 7.6269],
        to: [21.938, 11.652],
    },
    IconPathCommand::CubicTo {
        control_a: [22.0213, 11.8765],
        control_b: [22.0213, 12.1235],
        to: [21.938, 12.348],
    },
    IconPathCommand::CubicTo {
        control_a: [20.278, 16.3731],
        control_b: [16.354, 18.9994],
        to: [12.0, 18.9994],
    },
    IconPathCommand::CubicTo {
        control_a: [7.646, 18.9994],
        control_b: [3.722, 16.3731],
        to: [2.062, 12.348],
    },
];
static EYE_SHAPES: &[IconShape] = &[
    IconShape::Path(EYE_PATH_0),
    IconShape::Circle {
        center: [12.0, 12.0],
        radius: 3.0,
    },
];
static EYE: IconData = IconData {
    name: "eye",
    shapes: EYE_SHAPES,
};

static FILE_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([15.0, 2.0]),
    IconPathCommand::LineTo([6.0, 2.0]),
    IconPathCommand::CubicTo {
        control_a: [4.8954, 2.0],
        control_b: [4.0, 2.8954],
        to: [4.0, 4.0],
    },
    IconPathCommand::LineTo([4.0, 20.0]),
    IconPathCommand::CubicTo {
        control_a: [4.0, 21.1046],
        control_b: [4.8954, 22.0],
        to: [6.0, 22.0],
    },
    IconPathCommand::LineTo([18.0, 22.0]),
    IconPathCommand::CubicTo {
        control_a: [19.1046, 22.0],
        control_b: [20.0, 21.1046],
        to: [20.0, 20.0],
    },
    IconPathCommand::LineTo([20.0, 7.0]),
    IconPathCommand::Close,
];
static FILE_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([14.0, 2.0]),
    IconPathCommand::LineTo([14.0, 6.0]),
    IconPathCommand::CubicTo {
        control_a: [14.0, 7.1046],
        control_b: [14.8954, 8.0],
        to: [16.0, 8.0],
    },
    IconPathCommand::LineTo([20.0, 8.0]),
];
static FILE_SHAPES: &[IconShape] = &[IconShape::Path(FILE_PATH_0), IconShape::Path(FILE_PATH_1)];
static FILE: IconData = IconData {
    name: "file",
    shapes: FILE_SHAPES,
};

static FOLDER_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([20.0, 20.0]),
    IconPathCommand::CubicTo {
        control_a: [21.1046, 20.0],
        control_b: [22.0, 19.1046],
        to: [22.0, 18.0],
    },
    IconPathCommand::LineTo([22.0, 8.0]),
    IconPathCommand::CubicTo {
        control_a: [22.0, 6.8954],
        control_b: [21.1046, 6.0],
        to: [20.0, 6.0],
    },
    IconPathCommand::LineTo([12.1, 6.0]),
    IconPathCommand::CubicTo {
        control_a: [11.4203, 6.0067],
        control_b: [10.7838, 5.6677],
        to: [10.41, 5.1],
    },
    IconPathCommand::LineTo([9.6, 3.9]),
    IconPathCommand::CubicTo {
        control_a: [9.2301, 3.3383],
        control_b: [8.6026, 3.0001],
        to: [7.93, 3.0],
    },
    IconPathCommand::LineTo([4.0, 3.0]),
    IconPathCommand::CubicTo {
        control_a: [2.8954, 3.0],
        control_b: [2.0, 3.8954],
        to: [2.0, 5.0],
    },
    IconPathCommand::LineTo([2.0, 18.0]),
    IconPathCommand::CubicTo {
        control_a: [2.0, 19.1046],
        control_b: [2.8954, 20.0],
        to: [4.0, 20.0],
    },
    IconPathCommand::Close,
];
static FOLDER_SHAPES: &[IconShape] = &[IconShape::Path(FOLDER_PATH_0)];
static FOLDER: IconData = IconData {
    name: "folder",
    shapes: FOLDER_SHAPES,
};

static GIT_BRANCH_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([6.0, 3.0]),
    IconPathCommand::LineTo([6.0, 15.0]),
];
static GIT_BRANCH_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([18.0, 9.0]),
    IconPathCommand::CubicTo {
        control_a: [18.0, 13.9706],
        control_b: [13.9706, 18.0],
        to: [9.0, 18.0],
    },
];
static GIT_BRANCH_SHAPES: &[IconShape] = &[
    IconShape::Path(GIT_BRANCH_PATH_0),
    IconShape::Circle {
        center: [18.0, 6.0],
        radius: 3.0,
    },
    IconShape::Circle {
        center: [6.0, 18.0],
        radius: 3.0,
    },
    IconShape::Path(GIT_BRANCH_PATH_1),
];
static GIT_BRANCH: IconData = IconData {
    name: "git-branch",
    shapes: GIT_BRANCH_SHAPES,
};

static MAXIMIZE_SHAPES: &[IconShape] = &[IconShape::RoundedRect {
    origin: [3.0, 3.0],
    size: [18.0, 18.0],
    radius: 2.0,
}];
static MAXIMIZE: IconData = IconData {
    name: "square",
    shapes: MAXIMIZE_SHAPES,
};

static MESSAGE_SQUARE_PLUS_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([22.0, 17.0]),
    IconPathCommand::CubicTo {
        control_a: [22.0, 18.1046],
        control_b: [21.1046, 19.0],
        to: [20.0, 19.0],
    },
    IconPathCommand::LineTo([6.828, 19.0]),
    IconPathCommand::CubicTo {
        control_a: [6.2976, 19.0001],
        control_b: [5.789, 19.2109],
        to: [5.414, 19.586],
    },
    IconPathCommand::LineTo([3.212, 21.788]),
    IconPathCommand::CubicTo {
        control_a: [3.0089, 21.991],
        control_b: [2.7036, 22.0517],
        to: [2.4383, 21.9419],
    },
    IconPathCommand::CubicTo {
        control_a: [2.173, 21.832],
        control_b: [2.0, 21.5731],
        to: [2.0, 21.286],
    },
    IconPathCommand::LineTo([2.0, 5.0]),
    IconPathCommand::CubicTo {
        control_a: [2.0, 3.8954],
        control_b: [2.8954, 3.0],
        to: [4.0, 3.0],
    },
    IconPathCommand::LineTo([20.0, 3.0]),
    IconPathCommand::CubicTo {
        control_a: [21.1046, 3.0],
        control_b: [22.0, 3.8954],
        to: [22.0, 5.0],
    },
    IconPathCommand::Close,
];
static MESSAGE_SQUARE_PLUS_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([12.0, 8.0]),
    IconPathCommand::LineTo([12.0, 14.0]),
];
static MESSAGE_SQUARE_PLUS_PATH_2: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([9.0, 11.0]),
    IconPathCommand::LineTo([15.0, 11.0]),
];
static MESSAGE_SQUARE_PLUS_SHAPES: &[IconShape] = &[
    IconShape::Path(MESSAGE_SQUARE_PLUS_PATH_0),
    IconShape::Path(MESSAGE_SQUARE_PLUS_PATH_1),
    IconShape::Path(MESSAGE_SQUARE_PLUS_PATH_2),
];
static MESSAGE_SQUARE_PLUS: IconData = IconData {
    name: "message-square-plus",
    shapes: MESSAGE_SQUARE_PLUS_SHAPES,
};

static MINIMIZE_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([5.0, 12.0]),
    IconPathCommand::LineTo([19.0, 12.0]),
];
static MINIMIZE_SHAPES: &[IconShape] = &[IconShape::Path(MINIMIZE_PATH_0)];
static MINIMIZE: IconData = IconData {
    name: "minus",
    shapes: MINIMIZE_SHAPES,
};

static MOON_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([20.985, 12.486]),
    IconPathCommand::CubicTo {
        control_a: [20.7239, 17.3235],
        control_b: [16.6804, 21.0863],
        to: [11.8366, 20.9994],
    },
    IconPathCommand::CubicTo {
        control_a: [6.9929, 20.9125],
        control_b: [3.087, 17.007],
        to: [2.9996, 12.1633],
    },
    IconPathCommand::CubicTo {
        control_a: [2.9121, 7.3195],
        control_b: [6.6745, 3.2757],
        to: [11.512, 3.014],
    },
    IconPathCommand::CubicTo {
        control_a: [11.917, 2.992],
        control_b: [12.129, 3.474],
        to: [11.914, 3.817],
    },
    IconPathCommand::CubicTo {
        control_a: [10.4332, 6.1863],
        control_b: [10.7837, 9.2641],
        to: [12.7593, 11.2397],
    },
    IconPathCommand::CubicTo {
        control_a: [14.7349, 13.2153],
        control_b: [17.8127, 13.5658],
        to: [20.182, 12.085],
    },
    IconPathCommand::CubicTo {
        control_a: [20.526, 11.87],
        control_b: [21.007, 12.081],
        to: [20.985, 12.486],
    },
];
static MOON_SHAPES: &[IconShape] = &[IconShape::Path(MOON_PATH_0)];
static MOON: IconData = IconData {
    name: "moon",
    shapes: MOON_SHAPES,
};

static NODES_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([8.59, 13.51]),
    IconPathCommand::LineTo([15.42, 17.49]),
];
static NODES_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([15.41, 6.51]),
    IconPathCommand::LineTo([8.59, 10.49]),
];
static NODES_SHAPES: &[IconShape] = &[
    IconShape::Circle {
        center: [18.0, 5.0],
        radius: 3.0,
    },
    IconShape::Circle {
        center: [6.0, 12.0],
        radius: 3.0,
    },
    IconShape::Circle {
        center: [18.0, 19.0],
        radius: 3.0,
    },
    IconShape::Path(NODES_PATH_0),
    IconShape::Path(NODES_PATH_1),
];
static NODES: IconData = IconData {
    name: "share-2",
    shapes: NODES_SHAPES,
};

static PAPERCLIP_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([16.0, 6.0]),
    IconPathCommand::LineTo([7.586, 14.586]),
    IconPathCommand::CubicTo {
        control_a: [6.8048, 15.3672],
        control_b: [6.8048, 16.6338],
        to: [7.586, 17.415],
    },
    IconPathCommand::CubicTo {
        control_a: [8.3672, 18.1962],
        control_b: [9.6338, 18.1962],
        to: [10.415, 17.415],
    },
    IconPathCommand::LineTo([18.829, 8.829]),
    IconPathCommand::CubicTo {
        control_a: [19.8395, 7.8185],
        control_b: [20.2342, 6.3456],
        to: [19.8643, 4.9652],
    },
    IconPathCommand::CubicTo {
        control_a: [19.4944, 3.5848],
        control_b: [18.4162, 2.5066],
        to: [17.0358, 2.1367],
    },
    IconPathCommand::CubicTo {
        control_a: [15.6554, 1.7668],
        control_b: [14.1825, 2.1615],
        to: [13.172, 3.172],
    },
    IconPathCommand::LineTo([4.793, 11.723]),
    IconPathCommand::CubicTo {
        control_a: [3.2567, 13.2345],
        control_b: [2.649, 15.4539],
        to: [3.2012, 17.5372],
    },
    IconPathCommand::CubicTo {
        control_a: [3.7534, 19.6205],
        control_b: [5.3805, 21.2476],
        to: [7.4638, 21.7998],
    },
    IconPathCommand::CubicTo {
        control_a: [9.5471, 22.352],
        control_b: [11.7665, 21.7443],
        to: [13.278, 20.208],
    },
    IconPathCommand::LineTo([21.657, 11.657]),
];
static PAPERCLIP_SHAPES: &[IconShape] = &[IconShape::Path(PAPERCLIP_PATH_0)];
static PAPERCLIP: IconData = IconData {
    name: "paperclip",
    shapes: PAPERCLIP_SHAPES,
};

static RESTORE_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([4.0, 16.0]),
    IconPathCommand::CubicTo {
        control_a: [2.9, 16.0],
        control_b: [2.0, 15.1],
        to: [2.0, 14.0],
    },
    IconPathCommand::LineTo([2.0, 4.0]),
    IconPathCommand::CubicTo {
        control_a: [2.0, 2.9],
        control_b: [2.9, 2.0],
        to: [4.0, 2.0],
    },
    IconPathCommand::LineTo([14.0, 2.0]),
    IconPathCommand::CubicTo {
        control_a: [15.1, 2.0],
        control_b: [16.0, 2.9],
        to: [16.0, 4.0],
    },
];
static RESTORE_SHAPES: &[IconShape] = &[
    IconShape::RoundedRect {
        origin: [8.0, 8.0],
        size: [14.0, 14.0],
        radius: 2.0,
    },
    IconShape::Path(RESTORE_PATH_0),
];
static RESTORE: IconData = IconData {
    name: "copy",
    shapes: RESTORE_SHAPES,
};

static SEARCH_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([21.0, 21.0]),
    IconPathCommand::LineTo([16.66, 16.66]),
];
static SEARCH_SHAPES: &[IconShape] = &[
    IconShape::Path(SEARCH_PATH_0),
    IconShape::Circle {
        center: [11.0, 11.0],
        radius: 8.0,
    },
];
static SEARCH: IconData = IconData {
    name: "search",
    shapes: SEARCH_SHAPES,
};

static SETTINGS_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([9.671, 4.136]),
    IconPathCommand::CubicTo {
        control_a: [9.7852, 2.9348],
        control_b: [10.7939, 2.0174],
        to: [12.0005, 2.0174],
    },
    IconPathCommand::CubicTo {
        control_a: [13.2071, 2.0174],
        control_b: [14.2158, 2.9348],
        to: [14.33, 4.136],
    },
    IconPathCommand::CubicTo {
        control_a: [14.3972, 4.8959],
        control_b: [14.8307, 5.5754],
        to: [15.4915, 5.9567],
    },
    IconPathCommand::CubicTo {
        control_a: [16.1523, 6.3379],
        control_b: [16.9574, 6.3731],
        to: [17.649, 6.051],
    },
    IconPathCommand::CubicTo {
        control_a: [18.7452, 5.5533],
        control_b: [20.0402, 5.9686],
        to: [20.6425, 7.0111],
    },
    IconPathCommand::CubicTo {
        control_a: [21.2448, 8.0536],
        control_b: [20.9577, 9.3829],
        to: [19.979, 10.084],
    },
    IconPathCommand::CubicTo {
        control_a: [19.3547, 10.522],
        control_b: [18.983, 11.2369],
        to: [18.983, 11.9995],
    },
    IconPathCommand::CubicTo {
        control_a: [18.983, 12.7621],
        control_b: [19.3547, 13.477],
        to: [19.979, 13.915],
    },
    IconPathCommand::CubicTo {
        control_a: [20.9577, 14.6161],
        control_b: [21.2448, 15.9454],
        to: [20.6425, 16.9879],
    },
    IconPathCommand::CubicTo {
        control_a: [20.0402, 18.0304],
        control_b: [18.7452, 18.4457],
        to: [17.649, 17.948],
    },
    IconPathCommand::CubicTo {
        control_a: [16.9574, 17.6259],
        control_b: [16.1523, 17.6611],
        to: [15.4915, 18.0423],
    },
    IconPathCommand::CubicTo {
        control_a: [14.8307, 18.4236],
        control_b: [14.3972, 19.1031],
        to: [14.33, 19.863],
    },
    IconPathCommand::CubicTo {
        control_a: [14.2158, 21.0642],
        control_b: [13.2071, 21.9816],
        to: [12.0005, 21.9816],
    },
    IconPathCommand::CubicTo {
        control_a: [10.7939, 21.9816],
        control_b: [9.7852, 21.0642],
        to: [9.671, 19.863],
    },
    IconPathCommand::CubicTo {
        control_a: [9.6039, 19.1028],
        control_b: [9.1703, 18.423],
        to: [8.5092, 18.0417],
    },
    IconPathCommand::CubicTo {
        control_a: [7.8481, 17.6604],
        control_b: [7.0427, 17.6254],
        to: [6.351, 17.948],
    },
    IconPathCommand::CubicTo {
        control_a: [5.2548, 18.4457],
        control_b: [3.9598, 18.0304],
        to: [3.3575, 16.9879],
    },
    IconPathCommand::CubicTo {
        control_a: [2.7552, 15.9454],
        control_b: [3.0423, 14.6161],
        to: [4.021, 13.915],
    },
    IconPathCommand::CubicTo {
        control_a: [4.6453, 13.477],
        control_b: [5.017, 12.7621],
        to: [5.017, 11.9995],
    },
    IconPathCommand::CubicTo {
        control_a: [5.017, 11.2369],
        control_b: [4.6453, 10.522],
        to: [4.021, 10.084],
    },
    IconPathCommand::CubicTo {
        control_a: [3.0437, 9.3826],
        control_b: [2.7574, 8.0544],
        to: [3.359, 7.0127],
    },
    IconPathCommand::CubicTo {
        control_a: [3.9606, 5.971],
        control_b: [5.254, 5.5551],
        to: [6.35, 6.051],
    },
    IconPathCommand::CubicTo {
        control_a: [7.0416, 6.3731],
        control_b: [7.8467, 6.3379],
        to: [8.5075, 5.9567],
    },
    IconPathCommand::CubicTo {
        control_a: [9.1683, 5.5754],
        control_b: [9.6018, 4.8959],
        to: [9.669, 4.136],
    },
];
static SETTINGS_SHAPES: &[IconShape] = &[
    IconShape::Path(SETTINGS_PATH_0),
    IconShape::Circle {
        center: [12.0, 12.0],
        radius: 3.0,
    },
];
static SETTINGS: IconData = IconData {
    name: "settings",
    shapes: SETTINGS_SHAPES,
};

static SHIELD_CHECK_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([20.0, 13.0]),
    IconPathCommand::CubicTo {
        control_a: [20.0, 18.0],
        control_b: [16.5, 20.5],
        to: [12.34, 21.95],
    },
    IconPathCommand::CubicTo {
        control_a: [12.1222, 22.0238],
        control_b: [11.8855, 22.0203],
        to: [11.67, 21.94],
    },
    IconPathCommand::CubicTo {
        control_a: [7.5, 20.5],
        control_b: [4.0, 18.0],
        to: [4.0, 13.0],
    },
    IconPathCommand::LineTo([4.0, 6.0]),
    IconPathCommand::CubicTo {
        control_a: [4.0, 5.4477],
        control_b: [4.4477, 5.0],
        to: [5.0, 5.0],
    },
    IconPathCommand::CubicTo {
        control_a: [7.0, 5.0],
        control_b: [9.5, 3.8],
        to: [11.24, 2.28],
    },
    IconPathCommand::CubicTo {
        control_a: [11.6777, 1.9061],
        control_b: [12.3223, 1.9061],
        to: [12.76, 2.28],
    },
    IconPathCommand::CubicTo {
        control_a: [14.51, 3.81],
        control_b: [17.0, 5.0],
        to: [19.0, 5.0],
    },
    IconPathCommand::CubicTo {
        control_a: [19.5523, 5.0],
        control_b: [20.0, 5.4477],
        to: [20.0, 6.0],
    },
    IconPathCommand::Close,
];
static SHIELD_CHECK_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([9.0, 12.0]),
    IconPathCommand::LineTo([11.0, 14.0]),
    IconPathCommand::LineTo([15.0, 10.0]),
];
static SHIELD_CHECK_SHAPES: &[IconShape] = &[
    IconShape::Path(SHIELD_CHECK_PATH_0),
    IconShape::Path(SHIELD_CHECK_PATH_1),
];
static SHIELD_CHECK: IconData = IconData {
    name: "shield-check",
    shapes: SHIELD_CHECK_SHAPES,
};

static SIDEBAR_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([9.0, 3.0]),
    IconPathCommand::LineTo([9.0, 21.0]),
];
static SIDEBAR_SHAPES: &[IconShape] = &[
    IconShape::RoundedRect {
        origin: [3.0, 3.0],
        size: [18.0, 18.0],
        radius: 2.0,
    },
    IconShape::Path(SIDEBAR_PATH_0),
];
static SIDEBAR: IconData = IconData {
    name: "panel-left",
    shapes: SIDEBAR_SHAPES,
};

static SPARKLES_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([11.017, 2.814]),
    IconPathCommand::CubicTo {
        control_a: [11.1054, 2.3407],
        control_b: [11.5185, 1.9976],
        to: [12.0, 1.9976],
    },
    IconPathCommand::CubicTo {
        control_a: [12.4815, 1.9976],
        control_b: [12.8946, 2.3407],
        to: [12.983, 2.814],
    },
    IconPathCommand::LineTo([14.034, 8.372]),
    IconPathCommand::CubicTo {
        control_a: [14.1868, 9.1807],
        control_b: [14.8193, 9.8132],
        to: [15.628, 9.966],
    },
    IconPathCommand::LineTo([21.186, 11.017]),
    IconPathCommand::CubicTo {
        control_a: [21.6593, 11.1054],
        control_b: [22.0024, 11.5185],
        to: [22.0024, 12.0],
    },
    IconPathCommand::CubicTo {
        control_a: [22.0024, 12.4815],
        control_b: [21.6593, 12.8946],
        to: [21.186, 12.983],
    },
    IconPathCommand::LineTo([15.628, 14.034]),
    IconPathCommand::CubicTo {
        control_a: [14.8193, 14.1868],
        control_b: [14.1868, 14.8193],
        to: [14.034, 15.628],
    },
    IconPathCommand::LineTo([12.983, 21.186]),
    IconPathCommand::CubicTo {
        control_a: [12.8946, 21.6593],
        control_b: [12.4815, 22.0024],
        to: [12.0, 22.0024],
    },
    IconPathCommand::CubicTo {
        control_a: [11.5185, 22.0024],
        control_b: [11.1054, 21.6593],
        to: [11.017, 21.186],
    },
    IconPathCommand::LineTo([9.966, 15.628]),
    IconPathCommand::CubicTo {
        control_a: [9.8132, 14.8193],
        control_b: [9.1807, 14.1868],
        to: [8.372, 14.034],
    },
    IconPathCommand::LineTo([2.814, 12.983]),
    IconPathCommand::CubicTo {
        control_a: [2.3407, 12.8946],
        control_b: [1.9976, 12.4815],
        to: [1.9976, 12.0],
    },
    IconPathCommand::CubicTo {
        control_a: [1.9976, 11.5185],
        control_b: [2.3407, 11.1054],
        to: [2.814, 11.017],
    },
    IconPathCommand::LineTo([8.372, 9.966]),
    IconPathCommand::CubicTo {
        control_a: [9.1807, 9.8132],
        control_b: [9.8132, 9.1807],
        to: [9.966, 8.372],
    },
    IconPathCommand::Close,
];
static SPARKLES_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([20.0, 2.0]),
    IconPathCommand::LineTo([20.0, 6.0]),
];
static SPARKLES_PATH_2: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([22.0, 4.0]),
    IconPathCommand::LineTo([18.0, 4.0]),
];
static SPARKLES_SHAPES: &[IconShape] = &[
    IconShape::Path(SPARKLES_PATH_0),
    IconShape::Path(SPARKLES_PATH_1),
    IconShape::Path(SPARKLES_PATH_2),
    IconShape::Circle {
        center: [4.0, 20.0],
        radius: 2.0,
    },
];
static SPARKLES: IconData = IconData {
    name: "sparkles",
    shapes: SPARKLES_SHAPES,
};

static WORKSPACE_SHAPES: &[IconShape] = &[
    IconShape::RoundedRect {
        origin: [3.0, 3.0],
        size: [7.0, 9.0],
        radius: 1.0,
    },
    IconShape::RoundedRect {
        origin: [14.0, 3.0],
        size: [7.0, 5.0],
        radius: 1.0,
    },
    IconShape::RoundedRect {
        origin: [14.0, 12.0],
        size: [7.0, 9.0],
        radius: 1.0,
    },
    IconShape::RoundedRect {
        origin: [3.0, 16.0],
        size: [7.0, 5.0],
        radius: 1.0,
    },
];
static WORKSPACE: IconData = IconData {
    name: "layout-dashboard",
    shapes: WORKSPACE_SHAPES,
};

static ACTIVITY_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([22.0, 12.0]),
    IconPathCommand::LineTo([19.52, 12.0]),
    IconPathCommand::CubicTo {
        control_a: [18.6218, 11.9981],
        control_b: [17.8325, 12.5952],
        to: [17.59, 13.46],
    },
    IconPathCommand::LineTo([15.24, 21.82]),
    IconPathCommand::CubicTo {
        control_a: [15.2089, 21.9267],
        control_b: [15.1111, 22.0],
        to: [15.0, 22.0],
    },
    IconPathCommand::CubicTo {
        control_a: [14.8889, 22.0],
        control_b: [14.7911, 21.9267],
        to: [14.76, 21.82],
    },
    IconPathCommand::LineTo([9.24, 2.18]),
    IconPathCommand::CubicTo {
        control_a: [9.2089, 2.0733],
        control_b: [9.1111, 2.0],
        to: [9.0, 2.0],
    },
    IconPathCommand::CubicTo {
        control_a: [8.8889, 2.0],
        control_b: [8.7911, 2.0733],
        to: [8.76, 2.18],
    },
    IconPathCommand::LineTo([6.41, 10.54]),
    IconPathCommand::CubicTo {
        control_a: [6.1685, 11.4013],
        control_b: [5.3845, 11.9974],
        to: [4.49, 12.0],
    },
    IconPathCommand::LineTo([2.0, 12.0]),
];
static ACTIVITY_SHAPES: &[IconShape] = &[IconShape::Path(ACTIVITY_PATH_0)];
static ACTIVITY: IconData = IconData {
    name: "activity",
    shapes: ACTIVITY_SHAPES,
};

static ATOM_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([20.2, 20.2]),
    IconPathCommand::CubicTo {
        control_a: [22.24, 18.17],
        control_b: [20.22, 12.84],
        to: [15.7, 8.3],
    },
    IconPathCommand::CubicTo {
        control_a: [11.16, 3.78],
        control_b: [5.83, 1.76],
        to: [3.8, 3.8],
    },
    IconPathCommand::CubicTo {
        control_a: [1.76, 5.83],
        control_b: [3.78, 11.16],
        to: [8.3, 15.7],
    },
    IconPathCommand::CubicTo {
        control_a: [12.84, 20.22],
        control_b: [18.17, 22.24],
        to: [20.2, 20.2],
    },
    IconPathCommand::Close,
];
static ATOM_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([15.7, 15.7]),
    IconPathCommand::CubicTo {
        control_a: [20.22, 11.16],
        control_b: [22.24, 5.83],
        to: [20.2, 3.8],
    },
    IconPathCommand::CubicTo {
        control_a: [18.17, 1.76],
        control_b: [12.84, 3.78],
        to: [8.3, 8.3],
    },
    IconPathCommand::CubicTo {
        control_a: [3.78, 12.84],
        control_b: [1.76, 18.17],
        to: [3.8, 20.2],
    },
    IconPathCommand::CubicTo {
        control_a: [5.83, 22.24],
        control_b: [11.16, 20.22],
        to: [15.7, 15.7],
    },
    IconPathCommand::Close,
];
static ATOM_SHAPES: &[IconShape] = &[
    IconShape::Circle {
        center: [12.0, 12.0],
        radius: 1.0,
    },
    IconShape::Path(ATOM_PATH_0),
    IconShape::Path(ATOM_PATH_1),
];
static ATOM: IconData = IconData {
    name: "atom",
    shapes: ATOM_SHAPES,
};

static BLEND_SHAPES: &[IconShape] = &[
    IconShape::Circle {
        center: [9.0, 9.0],
        radius: 7.0,
    },
    IconShape::Circle {
        center: [15.0, 15.0],
        radius: 7.0,
    },
];
static BLEND: IconData = IconData {
    name: "blend",
    shapes: BLEND_SHAPES,
};

static BUG_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([12.0, 20.0]),
    IconPathCommand::LineTo([12.0, 11.0]),
];
static BUG_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([14.0, 7.0]),
    IconPathCommand::CubicTo {
        control_a: [16.2091, 7.0],
        control_b: [18.0, 8.7909],
        to: [18.0, 11.0],
    },
    IconPathCommand::LineTo([18.0, 14.0]),
    IconPathCommand::CubicTo {
        control_a: [18.0, 17.3137],
        control_b: [15.3137, 20.0],
        to: [12.0, 20.0],
    },
    IconPathCommand::CubicTo {
        control_a: [8.6863, 20.0],
        control_b: [6.0, 17.3137],
        to: [6.0, 14.0],
    },
    IconPathCommand::LineTo([6.0, 11.0]),
    IconPathCommand::CubicTo {
        control_a: [6.0, 8.7909],
        control_b: [7.7909, 7.0],
        to: [10.0, 7.0],
    },
    IconPathCommand::Close,
];
static BUG_PATH_2: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([14.12, 3.88]),
    IconPathCommand::LineTo([16.0, 2.0]),
];
static BUG_PATH_3: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([21.0, 21.0]),
    IconPathCommand::CubicTo {
        control_a: [21.0024, 18.863],
        control_b: [19.3246, 17.1015],
        to: [17.19, 17.0],
    },
];
static BUG_PATH_4: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([21.0, 5.0]),
    IconPathCommand::CubicTo {
        control_a: [20.9977, 7.0333],
        control_b: [19.4704, 8.7413],
        to: [17.45, 8.97],
    },
];
static BUG_PATH_5: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([22.0, 13.0]),
    IconPathCommand::LineTo([18.0, 13.0]),
];
static BUG_PATH_6: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([3.0, 21.0]),
    IconPathCommand::CubicTo {
        control_a: [2.9976, 18.863],
        control_b: [4.6754, 17.1015],
        to: [6.81, 17.0],
    },
];
static BUG_PATH_7: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([3.0, 5.0]),
    IconPathCommand::CubicTo {
        control_a: [3.0023, 7.0333],
        control_b: [4.5296, 8.7413],
        to: [6.55, 8.97],
    },
];
static BUG_PATH_8: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([6.0, 13.0]),
    IconPathCommand::LineTo([2.0, 13.0]),
];
static BUG_PATH_9: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([8.0, 2.0]),
    IconPathCommand::LineTo([9.88, 3.88]),
];
static BUG_PATH_10: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([9.0, 7.13]),
    IconPathCommand::LineTo([9.0, 6.0]),
    IconPathCommand::CubicTo {
        control_a: [9.0, 4.3431],
        control_b: [10.3431, 3.0],
        to: [12.0, 3.0],
    },
    IconPathCommand::CubicTo {
        control_a: [13.6569, 3.0],
        control_b: [15.0, 4.3431],
        to: [15.0, 6.0],
    },
    IconPathCommand::LineTo([15.0, 7.13]),
];
static BUG_SHAPES: &[IconShape] = &[
    IconShape::Path(BUG_PATH_0),
    IconShape::Path(BUG_PATH_1),
    IconShape::Path(BUG_PATH_2),
    IconShape::Path(BUG_PATH_3),
    IconShape::Path(BUG_PATH_4),
    IconShape::Path(BUG_PATH_5),
    IconShape::Path(BUG_PATH_6),
    IconShape::Path(BUG_PATH_7),
    IconShape::Path(BUG_PATH_8),
    IconShape::Path(BUG_PATH_9),
    IconShape::Path(BUG_PATH_10),
];
static BUG: IconData = IconData {
    name: "bug",
    shapes: BUG_SHAPES,
};

static CLAPPERBOARD_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([20.2, 6.0]),
    IconPathCommand::LineTo([3.0, 11.0]),
    IconPathCommand::LineTo([2.1, 8.6]),
    IconPathCommand::CubicTo {
        control_a: [1.8, 7.5],
        control_b: [2.4, 6.4],
        to: [3.4, 6.1],
    },
    IconPathCommand::LineTo([16.9, 2.1]),
    IconPathCommand::CubicTo {
        control_a: [18.0, 1.8],
        control_b: [19.1, 2.4],
        to: [19.4, 3.4],
    },
    IconPathCommand::Close,
];
static CLAPPERBOARD_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([6.2, 5.3]),
    IconPathCommand::LineTo([9.3, 9.2]),
];
static CLAPPERBOARD_PATH_2: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([12.4, 3.4]),
    IconPathCommand::LineTo([15.5, 7.4]),
];
static CLAPPERBOARD_PATH_3: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([3.0, 11.0]),
    IconPathCommand::LineTo([21.0, 11.0]),
    IconPathCommand::LineTo([21.0, 19.0]),
    IconPathCommand::CubicTo {
        control_a: [21.0, 20.1046],
        control_b: [20.1046, 21.0],
        to: [19.0, 21.0],
    },
    IconPathCommand::LineTo([5.0, 21.0]),
    IconPathCommand::CubicTo {
        control_a: [3.8954, 21.0],
        control_b: [3.0, 20.1046],
        to: [3.0, 19.0],
    },
    IconPathCommand::Close,
];
static CLAPPERBOARD_SHAPES: &[IconShape] = &[
    IconShape::Path(CLAPPERBOARD_PATH_0),
    IconShape::Path(CLAPPERBOARD_PATH_1),
    IconShape::Path(CLAPPERBOARD_PATH_2),
    IconShape::Path(CLAPPERBOARD_PATH_3),
];
static CLAPPERBOARD: IconData = IconData {
    name: "clapperboard",
    shapes: CLAPPERBOARD_SHAPES,
};

static CPU_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([12.0, 20.0]),
    IconPathCommand::LineTo([12.0, 22.0]),
];
static CPU_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([12.0, 2.0]),
    IconPathCommand::LineTo([12.0, 4.0]),
];
static CPU_PATH_2: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([17.0, 20.0]),
    IconPathCommand::LineTo([17.0, 22.0]),
];
static CPU_PATH_3: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([17.0, 2.0]),
    IconPathCommand::LineTo([17.0, 4.0]),
];
static CPU_PATH_4: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([2.0, 12.0]),
    IconPathCommand::LineTo([4.0, 12.0]),
];
static CPU_PATH_5: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([2.0, 17.0]),
    IconPathCommand::LineTo([4.0, 17.0]),
];
static CPU_PATH_6: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([2.0, 7.0]),
    IconPathCommand::LineTo([4.0, 7.0]),
];
static CPU_PATH_7: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([20.0, 12.0]),
    IconPathCommand::LineTo([22.0, 12.0]),
];
static CPU_PATH_8: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([20.0, 17.0]),
    IconPathCommand::LineTo([22.0, 17.0]),
];
static CPU_PATH_9: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([20.0, 7.0]),
    IconPathCommand::LineTo([22.0, 7.0]),
];
static CPU_PATH_10: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([7.0, 20.0]),
    IconPathCommand::LineTo([7.0, 22.0]),
];
static CPU_PATH_11: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([7.0, 2.0]),
    IconPathCommand::LineTo([7.0, 4.0]),
];
static CPU_SHAPES: &[IconShape] = &[
    IconShape::Path(CPU_PATH_0),
    IconShape::Path(CPU_PATH_1),
    IconShape::Path(CPU_PATH_2),
    IconShape::Path(CPU_PATH_3),
    IconShape::Path(CPU_PATH_4),
    IconShape::Path(CPU_PATH_5),
    IconShape::Path(CPU_PATH_6),
    IconShape::Path(CPU_PATH_7),
    IconShape::Path(CPU_PATH_8),
    IconShape::Path(CPU_PATH_9),
    IconShape::Path(CPU_PATH_10),
    IconShape::Path(CPU_PATH_11),
    IconShape::RoundedRect {
        origin: [4.0, 4.0],
        size: [16.0, 16.0],
        radius: 2.0,
    },
    IconShape::RoundedRect {
        origin: [8.0, 8.0],
        size: [8.0, 8.0],
        radius: 1.0,
    },
];
static CPU: IconData = IconData {
    name: "cpu",
    shapes: CPU_SHAPES,
};

static GAMEPAD2_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([6.0, 11.0]),
    IconPathCommand::LineTo([10.0, 11.0]),
];
static GAMEPAD2_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([8.0, 9.0]),
    IconPathCommand::LineTo([8.0, 13.0]),
];
static GAMEPAD2_PATH_2: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([15.0, 12.0]),
    IconPathCommand::LineTo([15.01, 12.0]),
];
static GAMEPAD2_PATH_3: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([18.0, 10.0]),
    IconPathCommand::LineTo([18.01, 10.0]),
];
static GAMEPAD2_PATH_4: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([17.32, 5.0]),
    IconPathCommand::LineTo([6.68, 5.0]),
    IconPathCommand::CubicTo {
        control_a: [4.63, 5.0005],
        control_b: [2.9121, 6.5508],
        to: [2.702, 8.59],
    },
    IconPathCommand::CubicTo {
        control_a: [2.696, 8.642],
        control_b: [2.692, 8.691],
        to: [2.685, 8.742],
    },
    IconPathCommand::CubicTo {
        control_a: [2.604, 9.416],
        control_b: [2.0, 14.456],
        to: [2.0, 16.0],
    },
    IconPathCommand::CubicTo {
        control_a: [2.0, 17.6569],
        control_b: [3.3431, 19.0],
        to: [5.0, 19.0],
    },
    IconPathCommand::CubicTo {
        control_a: [6.0, 19.0],
        control_b: [6.5, 18.5],
        to: [7.0, 18.0],
    },
    IconPathCommand::LineTo([8.414, 16.586]),
    IconPathCommand::CubicTo {
        control_a: [8.789, 16.2109],
        control_b: [9.2976, 16.0001],
        to: [9.828, 16.0],
    },
    IconPathCommand::LineTo([14.172, 16.0]),
    IconPathCommand::CubicTo {
        control_a: [14.7024, 16.0001],
        control_b: [15.211, 16.2109],
        to: [15.586, 16.586],
    },
    IconPathCommand::LineTo([17.0, 18.0]),
    IconPathCommand::CubicTo {
        control_a: [17.5, 18.5],
        control_b: [18.0, 19.0],
        to: [19.0, 19.0],
    },
    IconPathCommand::CubicTo {
        control_a: [20.6569, 19.0],
        control_b: [22.0, 17.6569],
        to: [22.0, 16.0],
    },
    IconPathCommand::CubicTo {
        control_a: [22.0, 14.455],
        control_b: [21.396, 9.416],
        to: [21.315, 8.742],
    },
    IconPathCommand::CubicTo {
        control_a: [21.308, 8.692],
        control_b: [21.304, 8.642],
        to: [21.298, 8.591],
    },
    IconPathCommand::CubicTo {
        control_a: [21.0883, 6.5514],
        control_b: [19.3704, 5.0005],
        to: [17.32, 5.0],
    },
    IconPathCommand::Close,
];
static GAMEPAD2_SHAPES: &[IconShape] = &[
    IconShape::Path(GAMEPAD2_PATH_0),
    IconShape::Path(GAMEPAD2_PATH_1),
    IconShape::Path(GAMEPAD2_PATH_2),
    IconShape::Path(GAMEPAD2_PATH_3),
    IconShape::Path(GAMEPAD2_PATH_4),
];
static GAMEPAD2: IconData = IconData {
    name: "gamepad-2",
    shapes: GAMEPAD2_SHAPES,
};

static MONITOR_PLAY_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([15.033, 9.44]),
    IconPathCommand::CubicTo {
        control_a: [15.2329, 9.5557],
        control_b: [15.3559, 9.7691],
        to: [15.3559, 10.0],
    },
    IconPathCommand::CubicTo {
        control_a: [15.3559, 10.2309],
        control_b: [15.2329, 10.4443],
        to: [15.033, 10.56],
    },
    IconPathCommand::LineTo([10.968, 12.912]),
    IconPathCommand::CubicTo {
        control_a: [10.7682, 13.0276],
        control_b: [10.5218, 13.0276],
        to: [10.322, 12.912],
    },
    IconPathCommand::CubicTo {
        control_a: [10.1222, 12.7964],
        control_b: [9.9994, 12.5828],
        to: [10.0, 12.352],
    },
    IconPathCommand::LineTo([10.0, 7.648]),
    IconPathCommand::CubicTo {
        control_a: [9.9996, 7.4175],
        control_b: [10.1223, 7.2042],
        to: [10.3218, 7.0887],
    },
    IconPathCommand::CubicTo {
        control_a: [10.5213, 6.9732],
        control_b: [10.7672, 6.9729],
        to: [10.967, 7.088],
    },
    IconPathCommand::Close,
];
static MONITOR_PLAY_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([12.0, 17.0]),
    IconPathCommand::LineTo([12.0, 21.0]),
];
static MONITOR_PLAY_PATH_2: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([8.0, 21.0]),
    IconPathCommand::LineTo([16.0, 21.0]),
];
static MONITOR_PLAY_SHAPES: &[IconShape] = &[
    IconShape::Path(MONITOR_PLAY_PATH_0),
    IconShape::Path(MONITOR_PLAY_PATH_1),
    IconShape::Path(MONITOR_PLAY_PATH_2),
    IconShape::RoundedRect {
        origin: [2.0, 3.0],
        size: [20.0, 14.0],
        radius: 2.0,
    },
];
static MONITOR_PLAY: IconData = IconData {
    name: "monitor-play",
    shapes: MONITOR_PLAY_SHAPES,
};

static PACKAGE_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([11.0, 21.73]),
    IconPathCommand::CubicTo {
        control_a: [11.6188, 22.0873],
        control_b: [12.3812, 22.0873],
        to: [13.0, 21.73],
    },
    IconPathCommand::LineTo([20.0, 17.73]),
    IconPathCommand::CubicTo {
        control_a: [20.6182, 17.3731],
        control_b: [20.9993, 16.7138],
        to: [21.0, 16.0],
    },
    IconPathCommand::LineTo([21.0, 8.0]),
    IconPathCommand::CubicTo {
        control_a: [20.9993, 7.2862],
        control_b: [20.6182, 6.6269],
        to: [20.0, 6.27],
    },
    IconPathCommand::LineTo([13.0, 2.27]),
    IconPathCommand::CubicTo {
        control_a: [12.3812, 1.9127],
        control_b: [11.6188, 1.9127],
        to: [11.0, 2.27],
    },
    IconPathCommand::LineTo([4.0, 6.27]),
    IconPathCommand::CubicTo {
        control_a: [3.3818, 6.6269],
        control_b: [3.0007, 7.2862],
        to: [3.0, 8.0],
    },
    IconPathCommand::LineTo([3.0, 16.0]),
    IconPathCommand::CubicTo {
        control_a: [3.0007, 16.7138],
        control_b: [3.3818, 17.3731],
        to: [4.0, 17.73],
    },
    IconPathCommand::Close,
];
static PACKAGE_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([12.0, 22.0]),
    IconPathCommand::LineTo([12.0, 12.0]),
];
static PACKAGE_PATH_2: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([3.29, 7.0]),
    IconPathCommand::LineTo([12.0, 12.0]),
    IconPathCommand::LineTo([20.71, 7.0]),
];
static PACKAGE_PATH_3: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([7.5, 4.27]),
    IconPathCommand::LineTo([16.5, 9.42]),
];
static PACKAGE_SHAPES: &[IconShape] = &[
    IconShape::Path(PACKAGE_PATH_0),
    IconShape::Path(PACKAGE_PATH_1),
    IconShape::Path(PACKAGE_PATH_2),
    IconShape::Path(PACKAGE_PATH_3),
];
static PACKAGE: IconData = IconData {
    name: "package",
    shapes: PACKAGE_SHAPES,
};

static PALETTE_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([12.0, 22.0]),
    IconPathCommand::CubicTo {
        control_a: [6.4772, 22.0],
        control_b: [2.0, 17.5228],
        to: [2.0, 12.0],
    },
    IconPathCommand::CubicTo {
        control_a: [2.0, 6.4772],
        control_b: [6.4772, 2.0],
        to: [12.0, 2.0],
    },
    IconPathCommand::CubicTo {
        control_a: [17.5228, 2.0],
        control_b: [22.0, 6.0294],
        to: [22.0, 11.0],
    },
    IconPathCommand::CubicTo {
        control_a: [22.0, 13.7614],
        control_b: [19.7614, 16.0],
        to: [17.0, 16.0],
    },
    IconPathCommand::LineTo([14.75, 16.0]),
    IconPathCommand::CubicTo {
        control_a: [14.0871, 16.0],
        control_b: [13.4812, 16.3745],
        to: [13.1848, 16.9674],
    },
    IconPathCommand::CubicTo {
        control_a: [12.8883, 17.5602],
        control_b: [12.9523, 18.2697],
        to: [13.35, 18.8],
    },
    IconPathCommand::LineTo([13.65, 19.2]),
    IconPathCommand::CubicTo {
        control_a: [14.0477, 19.7303],
        control_b: [14.1117, 20.4398],
        to: [13.8152, 21.0326],
    },
    IconPathCommand::CubicTo {
        control_a: [13.5188, 21.6255],
        control_b: [12.9129, 22.0],
        to: [12.25, 22.0],
    },
    IconPathCommand::Close,
];
static PALETTE_SHAPES: &[IconShape] = &[
    IconShape::Path(PALETTE_PATH_0),
    IconShape::Circle {
        center: [13.5, 6.5],
        radius: 0.5,
    },
    IconShape::Circle {
        center: [17.5, 10.5],
        radius: 0.5,
    },
    IconShape::Circle {
        center: [6.5, 12.5],
        radius: 0.5,
    },
    IconShape::Circle {
        center: [8.5, 7.5],
        radius: 0.5,
    },
];
static PALETTE: IconData = IconData {
    name: "palette",
    shapes: PALETTE_SHAPES,
};

static PUZZLE_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([15.39, 4.39]),
    IconPathCommand::CubicTo {
        control_a: [15.646, 4.6462],
        control_b: [16.0204, 4.744],
        to: [16.369, 4.6457],
    },
    IconPathCommand::CubicTo {
        control_a: [16.7176, 4.5473],
        control_b: [16.9857, 4.2682],
        to: [17.07, 3.916],
    },
    IconPathCommand::CubicTo {
        control_a: [17.3573, 2.7203],
        control_b: [18.4714, 1.911],
        to: [19.6974, 2.0077],
    },
    IconPathCommand::CubicTo {
        control_a: [20.9233, 2.1044],
        control_b: [21.8969, 3.0783],
        to: [21.9932, 4.3042],
    },
    IconPathCommand::CubicTo {
        control_a: [22.0894, 5.5302],
        control_b: [21.2798, 6.6441],
        to: [20.084, 6.931],
    },
    IconPathCommand::CubicTo {
        control_a: [19.7318, 7.0153],
        control_b: [19.4527, 7.2834],
        to: [19.3543, 7.632],
    },
    IconPathCommand::CubicTo {
        control_a: [19.256, 7.9806],
        control_b: [19.3538, 8.355],
        to: [19.61, 8.611],
    },
    IconPathCommand::LineTo([21.293, 10.293]),
    IconPathCommand::CubicTo {
        control_a: [21.7457, 10.7457],
        control_b: [22.0001, 11.3597],
        to: [22.0001, 12.0],
    },
    IconPathCommand::CubicTo {
        control_a: [22.0001, 12.6403],
        control_b: [21.7457, 13.2543],
        to: [21.293, 13.707],
    },
    IconPathCommand::LineTo([19.61, 15.39]),
    IconPathCommand::CubicTo {
        control_a: [19.354, 15.6462],
        control_b: [18.9796, 15.744],
        to: [18.631, 15.6457],
    },
    IconPathCommand::CubicTo {
        control_a: [18.2824, 15.5473],
        control_b: [18.0143, 15.2682],
        to: [17.93, 14.916],
    },
    IconPathCommand::CubicTo {
        control_a: [17.6427, 13.7203],
        control_b: [16.5286, 12.911],
        to: [15.3026, 13.0077],
    },
    IconPathCommand::CubicTo {
        control_a: [14.0767, 13.1044],
        control_b: [13.1031, 14.0783],
        to: [13.0068, 15.3042],
    },
    IconPathCommand::CubicTo {
        control_a: [12.9106, 16.5302],
        control_b: [13.7202, 17.6441],
        to: [14.916, 17.931],
    },
    IconPathCommand::CubicTo {
        control_a: [15.2682, 18.0153],
        control_b: [15.5473, 18.2834],
        to: [15.6457, 18.632],
    },
    IconPathCommand::CubicTo {
        control_a: [15.744, 18.9806],
        control_b: [15.6462, 19.355],
        to: [15.39, 19.611],
    },
    IconPathCommand::LineTo([13.707, 21.293]),
    IconPathCommand::CubicTo {
        control_a: [13.2543, 21.7457],
        control_b: [12.6403, 22.0001],
        to: [12.0, 22.0001],
    },
    IconPathCommand::CubicTo {
        control_a: [11.3597, 22.0001],
        control_b: [10.7457, 21.7457],
        to: [10.293, 21.293],
    },
    IconPathCommand::LineTo([8.61, 19.61]),
    IconPathCommand::CubicTo {
        control_a: [8.354, 19.3538],
        control_b: [7.9796, 19.256],
        to: [7.631, 19.3543],
    },
    IconPathCommand::CubicTo {
        control_a: [7.2824, 19.4527],
        control_b: [7.0143, 19.7318],
        to: [6.93, 20.084],
    },
    IconPathCommand::CubicTo {
        control_a: [6.6427, 21.2797],
        control_b: [5.5286, 22.089],
        to: [4.3026, 21.9923],
    },
    IconPathCommand::CubicTo {
        control_a: [3.0767, 21.8956],
        control_b: [2.1031, 20.9217],
        to: [2.0068, 19.6958],
    },
    IconPathCommand::CubicTo {
        control_a: [1.9106, 18.4698],
        control_b: [2.7202, 17.3559],
        to: [3.916, 17.069],
    },
    IconPathCommand::CubicTo {
        control_a: [4.2682, 16.9847],
        control_b: [4.5473, 16.7166],
        to: [4.6457, 16.368],
    },
    IconPathCommand::CubicTo {
        control_a: [4.744, 16.0194],
        control_b: [4.6462, 15.645],
        to: [4.39, 15.389],
    },
    IconPathCommand::LineTo([2.707, 13.707]),
    IconPathCommand::CubicTo {
        control_a: [2.2543, 13.2543],
        control_b: [1.9999, 12.6403],
        to: [1.9999, 12.0],
    },
    IconPathCommand::CubicTo {
        control_a: [1.9999, 11.3597],
        control_b: [2.2543, 10.7457],
        to: [2.707, 10.293],
    },
    IconPathCommand::LineTo([4.39, 8.61]),
    IconPathCommand::CubicTo {
        control_a: [4.646, 8.3538],
        control_b: [5.0204, 8.256],
        to: [5.369, 8.3543],
    },
    IconPathCommand::CubicTo {
        control_a: [5.7176, 8.4527],
        control_b: [5.9857, 8.7318],
        to: [6.07, 9.084],
    },
    IconPathCommand::CubicTo {
        control_a: [6.3573, 10.2797],
        control_b: [7.4714, 11.089],
        to: [8.6974, 10.9923],
    },
    IconPathCommand::CubicTo {
        control_a: [9.9233, 10.8956],
        control_b: [10.8969, 9.9217],
        to: [10.9932, 8.6958],
    },
    IconPathCommand::CubicTo {
        control_a: [11.0894, 7.4698],
        control_b: [10.2798, 6.3559],
        to: [9.084, 6.069],
    },
    IconPathCommand::CubicTo {
        control_a: [8.7318, 5.9847],
        control_b: [8.4527, 5.7166],
        to: [8.3543, 5.368],
    },
    IconPathCommand::CubicTo {
        control_a: [8.256, 5.0194],
        control_b: [8.3538, 4.645],
        to: [8.61, 4.389],
    },
    IconPathCommand::LineTo([10.293, 2.707]),
    IconPathCommand::CubicTo {
        control_a: [10.7457, 2.2543],
        control_b: [11.3597, 1.9999],
        to: [12.0, 1.9999],
    },
    IconPathCommand::CubicTo {
        control_a: [12.6403, 1.9999],
        control_b: [13.2543, 2.2543],
        to: [13.707, 2.707],
    },
    IconPathCommand::Close,
];
static PUZZLE_SHAPES: &[IconShape] = &[IconShape::Path(PUZZLE_PATH_0)];
static PUZZLE: IconData = IconData {
    name: "puzzle",
    shapes: PUZZLE_SHAPES,
};

static WEBCAM_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([7.0, 22.0]),
    IconPathCommand::LineTo([17.0, 22.0]),
];
static WEBCAM_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([12.0, 22.0]),
    IconPathCommand::LineTo([12.0, 18.0]),
];
static WEBCAM_SHAPES: &[IconShape] = &[
    IconShape::Circle {
        center: [12.0, 10.0],
        radius: 8.0,
    },
    IconShape::Circle {
        center: [12.0, 10.0],
        radius: 3.0,
    },
    IconShape::Path(WEBCAM_PATH_0),
    IconShape::Path(WEBCAM_PATH_1),
];
static WEBCAM: IconData = IconData {
    name: "webcam",
    shapes: WEBCAM_SHAPES,
};

static WIND_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([12.8, 19.6]),
    IconPathCommand::CubicTo {
        control_a: [13.4961, 20.1221],
        control_b: [14.45, 20.1342],
        to: [15.1591, 19.6298],
    },
    IconPathCommand::CubicTo {
        control_a: [15.8683, 19.1255],
        control_b: [16.1699, 18.2205],
        to: [15.9052, 17.3916],
    },
    IconPathCommand::CubicTo {
        control_a: [15.6405, 16.5627],
        control_b: [14.8702, 16.0],
        to: [14.0, 16.0],
    },
    IconPathCommand::LineTo([2.0, 16.0]),
];
static WIND_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([17.5, 8.0]),
    IconPathCommand::CubicTo {
        control_a: [18.2054, 7.0595],
        control_b: [19.4708, 6.7375],
        to: [20.5399, 7.2265],
    },
    IconPathCommand::CubicTo {
        control_a: [21.609, 7.7156],
        control_b: [22.193, 8.8834],
        to: [21.9427, 10.0321],
    },
    IconPathCommand::CubicTo {
        control_a: [21.6925, 11.1809],
        control_b: [20.6757, 12.0],
        to: [19.5, 12.0],
    },
    IconPathCommand::LineTo([2.0, 12.0]),
];
static WIND_PATH_2: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([9.8, 4.4]),
    IconPathCommand::CubicTo {
        control_a: [10.4961, 3.8779],
        control_b: [11.45, 3.8658],
        to: [12.1591, 4.3702],
    },
    IconPathCommand::CubicTo {
        control_a: [12.8683, 4.8745],
        control_b: [13.1699, 5.7795],
        to: [12.9052, 6.6084],
    },
    IconPathCommand::CubicTo {
        control_a: [12.6405, 7.4373],
        control_b: [11.8702, 8.0],
        to: [11.0, 8.0],
    },
    IconPathCommand::LineTo([2.0, 8.0]),
];
static WIND_SHAPES: &[IconShape] = &[
    IconShape::Path(WIND_PATH_0),
    IconShape::Path(WIND_PATH_1),
    IconShape::Path(WIND_PATH_2),
];
static WIND: IconData = IconData {
    name: "wind",
    shapes: WIND_SHAPES,
};

#[allow(non_upper_case_globals)]
impl Icon {
    pub const About: Self = Self(&ABOUT);
    pub const Add: Self = Self(&ADD);
    pub const Appearance: Self = Self(&APPEARANCE);
    pub const ArrowLeft: Self = Self(&ARROW_LEFT);
    pub const ArrowRight: Self = Self(&ARROW_RIGHT);
    pub const ArrowUp: Self = Self(&ARROW_UP);
    pub const Bot: Self = Self(&BOT);
    pub const ChevronDown: Self = Self(&CHEVRON_DOWN);
    pub const ChevronRight: Self = Self(&CHEVRON_RIGHT);
    pub const ChevronUp: Self = Self(&CHEVRON_UP);
    pub const Chart: Self = Self(&CHART);
    pub const Close: Self = Self(&CLOSE);
    pub const Eye: Self = Self(&EYE);
    pub const File: Self = Self(&FILE);
    pub const Folder: Self = Self(&FOLDER);
    pub const GitBranch: Self = Self(&GIT_BRANCH);
    pub const Maximize: Self = Self(&MAXIMIZE);
    pub const MessageSquarePlus: Self = Self(&MESSAGE_SQUARE_PLUS);
    pub const Minimize: Self = Self(&MINIMIZE);
    pub const Moon: Self = Self(&MOON);
    pub const Nodes: Self = Self(&NODES);
    pub const Paperclip: Self = Self(&PAPERCLIP);
    pub const Restore: Self = Self(&RESTORE);
    pub const Search: Self = Self(&SEARCH);
    pub const Settings: Self = Self(&SETTINGS);
    pub const ShieldCheck: Self = Self(&SHIELD_CHECK);
    pub const Sidebar: Self = Self(&SIDEBAR);
    pub const Sparkles: Self = Self(&SPARKLES);
    pub const Workspace: Self = Self(&WORKSPACE);
    pub const Activity: Self = Self(&ACTIVITY);
    pub const Atom: Self = Self(&ATOM);
    pub const Blend: Self = Self(&BLEND);
    pub const Bug: Self = Self(&BUG);
    pub const Clapperboard: Self = Self(&CLAPPERBOARD);
    pub const Cpu: Self = Self(&CPU);
    pub const Gamepad2: Self = Self(&GAMEPAD2);
    pub const MonitorPlay: Self = Self(&MONITOR_PLAY);
    pub const Package: Self = Self(&PACKAGE);
    pub const Palette: Self = Self(&PALETTE);
    pub const Puzzle: Self = Self(&PUZZLE);
    pub const Sun: Self = Self(&APPEARANCE);
    pub const Webcam: Self = Self(&WEBCAM);
    pub const Wind: Self = Self(&WIND);
}
