// @generated by scripts/generate_tabler_icons.py from @tabler/icons 3.46.0 (MIT).
// Do not edit by hand. Painters rasterize `svg`; shapes stay for tests.
use crate::icon::{Icon, IconData, IconPathCommand, IconShape};

static ABOUT_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([3.0, 12.0]),
    IconPathCommand::CubicTo {
        control_a: [3.0, 16.9706],
        control_b: [7.0294, 21.0],
        to: [12.0, 21.0],
    },
    IconPathCommand::CubicTo {
        control_a: [16.9706, 21.0],
        control_b: [21.0, 16.9706],
        to: [21.0, 12.0],
    },
    IconPathCommand::CubicTo {
        control_a: [21.0, 7.0294],
        control_b: [16.9706, 3.0],
        to: [12.0, 3.0],
    },
    IconPathCommand::CubicTo {
        control_a: [7.0294, 3.0],
        control_b: [3.0, 7.0294],
        to: [3.0, 12.0],
    },
];
static ABOUT_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([12.0, 9.0]),
    IconPathCommand::LineTo([12.01, 9.0]),
];
static ABOUT_PATH_2: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([11.0, 12.0]),
    IconPathCommand::LineTo([12.0, 12.0]),
    IconPathCommand::LineTo([12.0, 16.0]),
    IconPathCommand::LineTo([13.0, 16.0]),
];
static ABOUT_SHAPES: &[IconShape] = &[
    IconShape::Path(ABOUT_PATH_0),
    IconShape::Path(ABOUT_PATH_1),
    IconShape::Path(ABOUT_PATH_2),
];
static ABOUT_SVG: &str = r#"<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
  class="icon icon-tabler icons-tabler-outline icon-tabler-info-circle"
><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M3 12a9 9 0 1 0 18 0a9 9 0 0 0 -18 0" /><path d="M12 9h.01" /><path d="M11 12h1v4h1" /></svg>"#;
static ABOUT: IconData = IconData {
    name: "info-circle",
    shapes: ABOUT_SHAPES,
    svg: ABOUT_SVG,
};

static ADD_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([12.0, 5.0]),
    IconPathCommand::LineTo([12.0, 19.0]),
];
static ADD_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([5.0, 12.0]),
    IconPathCommand::LineTo([19.0, 12.0]),
];
static ADD_SHAPES: &[IconShape] = &[IconShape::Path(ADD_PATH_0), IconShape::Path(ADD_PATH_1)];
static ADD_SVG: &str = r#"<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
  class="icon icon-tabler icons-tabler-outline icon-tabler-plus"
><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M12 5l0 14" /><path d="M5 12l14 0" /></svg>"#;
static ADD: IconData = IconData {
    name: "plus",
    shapes: ADD_SHAPES,
    svg: ADD_SVG,
};

static APPEARANCE_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([8.0, 12.0]),
    IconPathCommand::CubicTo {
        control_a: [8.0, 14.2091],
        control_b: [9.7909, 16.0],
        to: [12.0, 16.0],
    },
    IconPathCommand::CubicTo {
        control_a: [14.2091, 16.0],
        control_b: [16.0, 14.2091],
        to: [16.0, 12.0],
    },
    IconPathCommand::CubicTo {
        control_a: [16.0, 9.7909],
        control_b: [14.2091, 8.0],
        to: [12.0, 8.0],
    },
    IconPathCommand::CubicTo {
        control_a: [9.7909, 8.0],
        control_b: [8.0, 9.7909],
        to: [8.0, 12.0],
    },
];
static APPEARANCE_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([3.0, 12.0]),
    IconPathCommand::LineTo([4.0, 12.0]),
    IconPathCommand::MoveTo([12.0, 3.0]),
    IconPathCommand::LineTo([12.0, 4.0]),
    IconPathCommand::MoveTo([20.0, 12.0]),
    IconPathCommand::LineTo([21.0, 12.0]),
    IconPathCommand::MoveTo([12.0, 20.0]),
    IconPathCommand::LineTo([12.0, 21.0]),
    IconPathCommand::MoveTo([5.6, 5.6]),
    IconPathCommand::LineTo([6.3, 6.3]),
    IconPathCommand::MoveTo([18.4, 5.6]),
    IconPathCommand::LineTo([17.7, 6.3]),
    IconPathCommand::MoveTo([17.7, 17.7]),
    IconPathCommand::LineTo([18.4, 18.4]),
    IconPathCommand::MoveTo([6.3, 17.7]),
    IconPathCommand::LineTo([5.6, 18.4]),
];
static APPEARANCE_SHAPES: &[IconShape] = &[
    IconShape::Path(APPEARANCE_PATH_0),
    IconShape::Path(APPEARANCE_PATH_1),
];
static APPEARANCE_SVG: &str = r#"<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
  class="icon icon-tabler icons-tabler-outline icon-tabler-sun"
><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M8 12a4 4 0 1 0 8 0a4 4 0 1 0 -8 0" /><path d="M3 12h1m8 -9v1m8 8h1m-9 8v1m-6.4 -15.4l.7 .7m12.1 -.7l-.7 .7m0 11.4l.7 .7m-12.1 -.7l-.7 .7" /></svg>"#;
static APPEARANCE: IconData = IconData {
    name: "sun",
    shapes: APPEARANCE_SHAPES,
    svg: APPEARANCE_SVG,
};

static ARROW_LEFT_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([5.0, 12.0]),
    IconPathCommand::LineTo([19.0, 12.0]),
];
static ARROW_LEFT_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([5.0, 12.0]),
    IconPathCommand::LineTo([11.0, 18.0]),
];
static ARROW_LEFT_PATH_2: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([5.0, 12.0]),
    IconPathCommand::LineTo([11.0, 6.0]),
];
static ARROW_LEFT_SHAPES: &[IconShape] = &[
    IconShape::Path(ARROW_LEFT_PATH_0),
    IconShape::Path(ARROW_LEFT_PATH_1),
    IconShape::Path(ARROW_LEFT_PATH_2),
];
static ARROW_LEFT_SVG: &str = r#"<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
  class="icon icon-tabler icons-tabler-outline icon-tabler-arrow-left"
><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M5 12l14 0" /><path d="M5 12l6 6" /><path d="M5 12l6 -6" /></svg>"#;
static ARROW_LEFT: IconData = IconData {
    name: "arrow-left",
    shapes: ARROW_LEFT_SHAPES,
    svg: ARROW_LEFT_SVG,
};

static ARROW_RIGHT_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([5.0, 12.0]),
    IconPathCommand::LineTo([19.0, 12.0]),
];
static ARROW_RIGHT_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([13.0, 18.0]),
    IconPathCommand::LineTo([19.0, 12.0]),
];
static ARROW_RIGHT_PATH_2: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([13.0, 6.0]),
    IconPathCommand::LineTo([19.0, 12.0]),
];
static ARROW_RIGHT_SHAPES: &[IconShape] = &[
    IconShape::Path(ARROW_RIGHT_PATH_0),
    IconShape::Path(ARROW_RIGHT_PATH_1),
    IconShape::Path(ARROW_RIGHT_PATH_2),
];
static ARROW_RIGHT_SVG: &str = r#"<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
  class="icon icon-tabler icons-tabler-outline icon-tabler-arrow-right"
><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M5 12l14 0" /><path d="M13 18l6 -6" /><path d="M13 6l6 6" /></svg>"#;
static ARROW_RIGHT: IconData = IconData {
    name: "arrow-right",
    shapes: ARROW_RIGHT_SHAPES,
    svg: ARROW_RIGHT_SVG,
};

static ARROW_UP_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([12.0, 5.0]),
    IconPathCommand::LineTo([12.0, 19.0]),
];
static ARROW_UP_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([18.0, 11.0]),
    IconPathCommand::LineTo([12.0, 5.0]),
];
static ARROW_UP_PATH_2: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([6.0, 11.0]),
    IconPathCommand::LineTo([12.0, 5.0]),
];
static ARROW_UP_SHAPES: &[IconShape] = &[
    IconShape::Path(ARROW_UP_PATH_0),
    IconShape::Path(ARROW_UP_PATH_1),
    IconShape::Path(ARROW_UP_PATH_2),
];
static ARROW_UP_SVG: &str = r#"<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
  class="icon icon-tabler icons-tabler-outline icon-tabler-arrow-up"
><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M12 5l0 14" /><path d="M18 11l-6 -6" /><path d="M6 11l6 -6" /></svg>"#;
static ARROW_UP: IconData = IconData {
    name: "arrow-up",
    shapes: ARROW_UP_SHAPES,
    svg: ARROW_UP_SVG,
};

static BOT_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([6.0, 6.0]),
    IconPathCommand::CubicTo {
        control_a: [6.0, 4.8954],
        control_b: [6.8954, 4.0],
        to: [8.0, 4.0],
    },
    IconPathCommand::LineTo([16.0, 4.0]),
    IconPathCommand::CubicTo {
        control_a: [17.1046, 4.0],
        control_b: [18.0, 4.8954],
        to: [18.0, 6.0],
    },
    IconPathCommand::LineTo([18.0, 10.0]),
    IconPathCommand::CubicTo {
        control_a: [18.0, 11.1046],
        control_b: [17.1046, 12.0],
        to: [16.0, 12.0],
    },
    IconPathCommand::LineTo([8.0, 12.0]),
    IconPathCommand::CubicTo {
        control_a: [6.8954, 12.0],
        control_b: [6.0, 11.1046],
        to: [6.0, 10.0],
    },
    IconPathCommand::LineTo([6.0, 6.0]),
];
static BOT_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([12.0, 2.0]),
    IconPathCommand::LineTo([12.0, 4.0]),
];
static BOT_PATH_2: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([9.0, 12.0]),
    IconPathCommand::LineTo([9.0, 21.0]),
];
static BOT_PATH_3: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([15.0, 12.0]),
    IconPathCommand::LineTo([15.0, 21.0]),
];
static BOT_PATH_4: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([5.0, 16.0]),
    IconPathCommand::LineTo([9.0, 14.0]),
];
static BOT_PATH_5: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([15.0, 14.0]),
    IconPathCommand::LineTo([19.0, 16.0]),
];
static BOT_PATH_6: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([9.0, 18.0]),
    IconPathCommand::LineTo([15.0, 18.0]),
];
static BOT_PATH_7: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([10.0, 8.0]),
    IconPathCommand::LineTo([10.0, 8.01]),
];
static BOT_PATH_8: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([14.0, 8.0]),
    IconPathCommand::LineTo([14.0, 8.01]),
];
static BOT_SHAPES: &[IconShape] = &[
    IconShape::Path(BOT_PATH_0),
    IconShape::Path(BOT_PATH_1),
    IconShape::Path(BOT_PATH_2),
    IconShape::Path(BOT_PATH_3),
    IconShape::Path(BOT_PATH_4),
    IconShape::Path(BOT_PATH_5),
    IconShape::Path(BOT_PATH_6),
    IconShape::Path(BOT_PATH_7),
    IconShape::Path(BOT_PATH_8),
];
static BOT_SVG: &str = r#"<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
  class="icon icon-tabler icons-tabler-outline icon-tabler-robot"
><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M6 6a2 2 0 0 1 2 -2h8a2 2 0 0 1 2 2v4a2 2 0 0 1 -2 2h-8a2 2 0 0 1 -2 -2l0 -4" /><path d="M12 2v2" /><path d="M9 12v9" /><path d="M15 12v9" /><path d="M5 16l4 -2" /><path d="M15 14l4 2" /><path d="M9 18h6" /><path d="M10 8v.01" /><path d="M14 8v.01" /></svg>"#;
static BOT: IconData = IconData {
    name: "robot",
    shapes: BOT_SHAPES,
    svg: BOT_SVG,
};

static CHEVRON_DOWN_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([6.0, 9.0]),
    IconPathCommand::LineTo([12.0, 15.0]),
    IconPathCommand::LineTo([18.0, 9.0]),
];
static CHEVRON_DOWN_SHAPES: &[IconShape] = &[IconShape::Path(CHEVRON_DOWN_PATH_0)];
static CHEVRON_DOWN_SVG: &str = r#"<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
  class="icon icon-tabler icons-tabler-outline icon-tabler-chevron-down"
><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M6 9l6 6l6 -6" /></svg>"#;
static CHEVRON_DOWN: IconData = IconData {
    name: "chevron-down",
    shapes: CHEVRON_DOWN_SHAPES,
    svg: CHEVRON_DOWN_SVG,
};

static CHEVRON_RIGHT_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([9.0, 6.0]),
    IconPathCommand::LineTo([15.0, 12.0]),
    IconPathCommand::LineTo([9.0, 18.0]),
];
static CHEVRON_RIGHT_SHAPES: &[IconShape] = &[IconShape::Path(CHEVRON_RIGHT_PATH_0)];
static CHEVRON_RIGHT_SVG: &str = r#"<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
  class="icon icon-tabler icons-tabler-outline icon-tabler-chevron-right"
><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M9 6l6 6l-6 6" /></svg>"#;
static CHEVRON_RIGHT: IconData = IconData {
    name: "chevron-right",
    shapes: CHEVRON_RIGHT_SHAPES,
    svg: CHEVRON_RIGHT_SVG,
};

static CHEVRON_UP_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([6.0, 15.0]),
    IconPathCommand::LineTo([12.0, 9.0]),
    IconPathCommand::LineTo([18.0, 15.0]),
];
static CHEVRON_UP_SHAPES: &[IconShape] = &[IconShape::Path(CHEVRON_UP_PATH_0)];
static CHEVRON_UP_SVG: &str = r#"<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
  class="icon icon-tabler icons-tabler-outline icon-tabler-chevron-up"
><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M6 15l6 -6l6 6" /></svg>"#;
static CHEVRON_UP: IconData = IconData {
    name: "chevron-up",
    shapes: CHEVRON_UP_SHAPES,
    svg: CHEVRON_UP_SVG,
};

static CHART_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([4.0, 19.0]),
    IconPathCommand::LineTo([20.0, 19.0]),
];
static CHART_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([4.0, 15.0]),
    IconPathCommand::LineTo([8.0, 9.0]),
    IconPathCommand::LineTo([12.0, 11.0]),
    IconPathCommand::LineTo([16.0, 6.0]),
    IconPathCommand::LineTo([20.0, 10.0]),
];
static CHART_SHAPES: &[IconShape] = &[IconShape::Path(CHART_PATH_0), IconShape::Path(CHART_PATH_1)];
static CHART_SVG: &str = r#"<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
  class="icon icon-tabler icons-tabler-outline icon-tabler-chart-line"
><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M4 19l16 0" /><path d="M4 15l4 -6l4 2l4 -5l4 4" /></svg>"#;
static CHART: IconData = IconData {
    name: "chart-line",
    shapes: CHART_SHAPES,
    svg: CHART_SVG,
};

static CLOSE_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([18.0, 6.0]),
    IconPathCommand::LineTo([6.0, 18.0]),
];
static CLOSE_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([6.0, 6.0]),
    IconPathCommand::LineTo([18.0, 18.0]),
];
static CLOSE_SHAPES: &[IconShape] = &[IconShape::Path(CLOSE_PATH_0), IconShape::Path(CLOSE_PATH_1)];
static CLOSE_SVG: &str = r#"<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
  class="icon icon-tabler icons-tabler-outline icon-tabler-x"
><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M18 6l-12 12" /><path d="M6 6l12 12" /></svg>"#;
static CLOSE: IconData = IconData {
    name: "x",
    shapes: CLOSE_SHAPES,
    svg: CLOSE_SVG,
};

static EYE_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([10.0, 12.0]),
    IconPathCommand::CubicTo {
        control_a: [10.0, 13.1046],
        control_b: [10.8954, 14.0],
        to: [12.0, 14.0],
    },
    IconPathCommand::CubicTo {
        control_a: [13.1046, 14.0],
        control_b: [14.0, 13.1046],
        to: [14.0, 12.0],
    },
    IconPathCommand::CubicTo {
        control_a: [14.0, 10.8954],
        control_b: [13.1046, 10.0],
        to: [12.0, 10.0],
    },
    IconPathCommand::CubicTo {
        control_a: [10.8954, 10.0],
        control_b: [10.0, 10.8954],
        to: [10.0, 12.0],
    },
];
static EYE_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([21.0, 12.0]),
    IconPathCommand::CubicTo {
        control_a: [18.6, 16.0],
        control_b: [15.6, 18.0],
        to: [12.0, 18.0],
    },
    IconPathCommand::CubicTo {
        control_a: [8.4, 18.0],
        control_b: [5.4, 16.0],
        to: [3.0, 12.0],
    },
    IconPathCommand::CubicTo {
        control_a: [5.4, 8.0],
        control_b: [8.4, 6.0],
        to: [12.0, 6.0],
    },
    IconPathCommand::CubicTo {
        control_a: [15.6, 6.0],
        control_b: [18.6, 8.0],
        to: [21.0, 12.0],
    },
];
static EYE_SHAPES: &[IconShape] = &[IconShape::Path(EYE_PATH_0), IconShape::Path(EYE_PATH_1)];
static EYE_SVG: &str = r#"<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
  class="icon icon-tabler icons-tabler-outline icon-tabler-eye"
><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M10 12a2 2 0 1 0 4 0a2 2 0 0 0 -4 0" /><path d="M21 12c-2.4 4 -5.4 6 -9 6c-3.6 0 -6.6 -2 -9 -6c2.4 -4 5.4 -6 9 -6c3.6 0 6.6 2 9 6" /></svg>"#;
static EYE: IconData = IconData {
    name: "eye",
    shapes: EYE_SHAPES,
    svg: EYE_SVG,
};

static FILE_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([14.0, 3.0]),
    IconPathCommand::LineTo([14.0, 7.0]),
    IconPathCommand::CubicTo {
        control_a: [14.0, 7.5523],
        control_b: [14.4477, 8.0],
        to: [15.0, 8.0],
    },
    IconPathCommand::LineTo([19.0, 8.0]),
];
static FILE_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([17.0, 21.0]),
    IconPathCommand::LineTo([7.0, 21.0]),
    IconPathCommand::CubicTo {
        control_a: [5.8954, 21.0],
        control_b: [5.0, 20.1046],
        to: [5.0, 19.0],
    },
    IconPathCommand::LineTo([5.0, 5.0]),
    IconPathCommand::CubicTo {
        control_a: [5.0, 3.8954],
        control_b: [5.8954, 3.0],
        to: [7.0, 3.0],
    },
    IconPathCommand::LineTo([14.0, 3.0]),
    IconPathCommand::LineTo([19.0, 8.0]),
    IconPathCommand::LineTo([19.0, 19.0]),
    IconPathCommand::CubicTo {
        control_a: [19.0, 20.1046],
        control_b: [18.1046, 21.0],
        to: [17.0, 21.0],
    },
];
static FILE_SHAPES: &[IconShape] = &[IconShape::Path(FILE_PATH_0), IconShape::Path(FILE_PATH_1)];
static FILE_SVG: &str = r#"<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
  class="icon icon-tabler icons-tabler-outline icon-tabler-file"
><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M14 3v4a1 1 0 0 0 1 1h4" /><path d="M17 21h-10a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2h7l5 5v11a2 2 0 0 1 -2 2" /></svg>"#;
static FILE: IconData = IconData {
    name: "file",
    shapes: FILE_SHAPES,
    svg: FILE_SVG,
};

static FOLDER_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([5.0, 4.0]),
    IconPathCommand::LineTo([9.0, 4.0]),
    IconPathCommand::LineTo([12.0, 7.0]),
    IconPathCommand::LineTo([19.0, 7.0]),
    IconPathCommand::CubicTo {
        control_a: [20.1046, 7.0],
        control_b: [21.0, 7.8954],
        to: [21.0, 9.0],
    },
    IconPathCommand::LineTo([21.0, 17.0]),
    IconPathCommand::CubicTo {
        control_a: [21.0, 18.1046],
        control_b: [20.1046, 19.0],
        to: [19.0, 19.0],
    },
    IconPathCommand::LineTo([5.0, 19.0]),
    IconPathCommand::CubicTo {
        control_a: [3.8954, 19.0],
        control_b: [3.0, 18.1046],
        to: [3.0, 17.0],
    },
    IconPathCommand::LineTo([3.0, 6.0]),
    IconPathCommand::CubicTo {
        control_a: [3.0, 4.8954],
        control_b: [3.8954, 4.0],
        to: [5.0, 4.0],
    },
];
static FOLDER_SHAPES: &[IconShape] = &[IconShape::Path(FOLDER_PATH_0)];
static FOLDER_SVG: &str = r#"<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
  class="icon icon-tabler icons-tabler-outline icon-tabler-folder"
><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M5 4h4l3 3h7a2 2 0 0 1 2 2v8a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-11a2 2 0 0 1 2 -2" /></svg>"#;
static FOLDER: IconData = IconData {
    name: "folder",
    shapes: FOLDER_SHAPES,
    svg: FOLDER_SVG,
};

static GIT_BRANCH_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([5.0, 18.0]),
    IconPathCommand::CubicTo {
        control_a: [5.0, 19.1046],
        control_b: [5.8954, 20.0],
        to: [7.0, 20.0],
    },
    IconPathCommand::CubicTo {
        control_a: [8.1046, 20.0],
        control_b: [9.0, 19.1046],
        to: [9.0, 18.0],
    },
    IconPathCommand::CubicTo {
        control_a: [9.0, 16.8954],
        control_b: [8.1046, 16.0],
        to: [7.0, 16.0],
    },
    IconPathCommand::CubicTo {
        control_a: [5.8954, 16.0],
        control_b: [5.0, 16.8954],
        to: [5.0, 18.0],
    },
];
static GIT_BRANCH_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([5.0, 6.0]),
    IconPathCommand::CubicTo {
        control_a: [5.0, 7.1046],
        control_b: [5.8954, 8.0],
        to: [7.0, 8.0],
    },
    IconPathCommand::CubicTo {
        control_a: [8.1046, 8.0],
        control_b: [9.0, 7.1046],
        to: [9.0, 6.0],
    },
    IconPathCommand::CubicTo {
        control_a: [9.0, 4.8954],
        control_b: [8.1046, 4.0],
        to: [7.0, 4.0],
    },
    IconPathCommand::CubicTo {
        control_a: [5.8954, 4.0],
        control_b: [5.0, 4.8954],
        to: [5.0, 6.0],
    },
];
static GIT_BRANCH_PATH_2: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([15.0, 6.0]),
    IconPathCommand::CubicTo {
        control_a: [15.0, 7.1046],
        control_b: [15.8954, 8.0],
        to: [17.0, 8.0],
    },
    IconPathCommand::CubicTo {
        control_a: [18.1046, 8.0],
        control_b: [19.0, 7.1046],
        to: [19.0, 6.0],
    },
    IconPathCommand::CubicTo {
        control_a: [19.0, 4.8954],
        control_b: [18.1046, 4.0],
        to: [17.0, 4.0],
    },
    IconPathCommand::CubicTo {
        control_a: [15.8954, 4.0],
        control_b: [15.0, 4.8954],
        to: [15.0, 6.0],
    },
];
static GIT_BRANCH_PATH_3: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([7.0, 8.0]),
    IconPathCommand::LineTo([7.0, 16.0]),
];
static GIT_BRANCH_PATH_4: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([9.0, 18.0]),
    IconPathCommand::LineTo([15.0, 18.0]),
    IconPathCommand::CubicTo {
        control_a: [16.1046, 18.0],
        control_b: [17.0, 17.1046],
        to: [17.0, 16.0],
    },
    IconPathCommand::LineTo([17.0, 11.0]),
];
static GIT_BRANCH_PATH_5: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([14.0, 14.0]),
    IconPathCommand::LineTo([17.0, 11.0]),
    IconPathCommand::LineTo([20.0, 14.0]),
];
static GIT_BRANCH_SHAPES: &[IconShape] = &[
    IconShape::Path(GIT_BRANCH_PATH_0),
    IconShape::Path(GIT_BRANCH_PATH_1),
    IconShape::Path(GIT_BRANCH_PATH_2),
    IconShape::Path(GIT_BRANCH_PATH_3),
    IconShape::Path(GIT_BRANCH_PATH_4),
    IconShape::Path(GIT_BRANCH_PATH_5),
];
static GIT_BRANCH_SVG: &str = r#"<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
  class="icon icon-tabler icons-tabler-outline icon-tabler-git-branch"
><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M5 18a2 2 0 1 0 4 0a2 2 0 1 0 -4 0" /><path d="M5 6a2 2 0 1 0 4 0a2 2 0 1 0 -4 0" /><path d="M15 6a2 2 0 1 0 4 0a2 2 0 1 0 -4 0" /><path d="M7 8l0 8" /><path d="M9 18h6a2 2 0 0 0 2 -2v-5" /><path d="M14 14l3 -3l3 3" /></svg>"#;
static GIT_BRANCH: IconData = IconData {
    name: "git-branch",
    shapes: GIT_BRANCH_SHAPES,
    svg: GIT_BRANCH_SVG,
};

static MAXIMIZE_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([3.0, 5.0]),
    IconPathCommand::CubicTo {
        control_a: [3.0, 3.8954],
        control_b: [3.8954, 3.0],
        to: [5.0, 3.0],
    },
    IconPathCommand::LineTo([19.0, 3.0]),
    IconPathCommand::CubicTo {
        control_a: [20.1046, 3.0],
        control_b: [21.0, 3.8954],
        to: [21.0, 5.0],
    },
    IconPathCommand::LineTo([21.0, 19.0]),
    IconPathCommand::CubicTo {
        control_a: [21.0, 20.1046],
        control_b: [20.1046, 21.0],
        to: [19.0, 21.0],
    },
    IconPathCommand::LineTo([5.0, 21.0]),
    IconPathCommand::CubicTo {
        control_a: [3.8954, 21.0],
        control_b: [3.0, 20.1046],
        to: [3.0, 19.0],
    },
    IconPathCommand::LineTo([3.0, 5.0]),
];
static MAXIMIZE_SHAPES: &[IconShape] = &[IconShape::Path(MAXIMIZE_PATH_0)];
static MAXIMIZE_SVG: &str = r#"<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
  class="icon icon-tabler icons-tabler-outline icon-tabler-square"
><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M3 5a2 2 0 0 1 2 -2h14a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-14" /></svg>"#;
static MAXIMIZE: IconData = IconData {
    name: "square",
    shapes: MAXIMIZE_SHAPES,
    svg: MAXIMIZE_SVG,
};

static MESSAGE_SQUARE_PLUS_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([8.0, 9.0]),
    IconPathCommand::LineTo([16.0, 9.0]),
];
static MESSAGE_SQUARE_PLUS_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([8.0, 13.0]),
    IconPathCommand::LineTo([14.0, 13.0]),
];
static MESSAGE_SQUARE_PLUS_PATH_2: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([12.01, 18.594]),
    IconPathCommand::LineTo([8.0, 21.0]),
    IconPathCommand::LineTo([8.0, 18.0]),
    IconPathCommand::LineTo([6.0, 18.0]),
    IconPathCommand::CubicTo {
        control_a: [4.3431, 18.0],
        control_b: [3.0, 16.6569],
        to: [3.0, 15.0],
    },
    IconPathCommand::LineTo([3.0, 7.0]),
    IconPathCommand::CubicTo {
        control_a: [3.0, 5.3431],
        control_b: [4.3431, 4.0],
        to: [6.0, 4.0],
    },
    IconPathCommand::LineTo([18.0, 4.0]),
    IconPathCommand::CubicTo {
        control_a: [19.6569, 4.0],
        control_b: [21.0, 5.3431],
        to: [21.0, 7.0],
    },
    IconPathCommand::LineTo([21.0, 12.5]),
];
static MESSAGE_SQUARE_PLUS_PATH_3: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([16.0, 19.0]),
    IconPathCommand::LineTo([22.0, 19.0]),
];
static MESSAGE_SQUARE_PLUS_PATH_4: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([19.0, 16.0]),
    IconPathCommand::LineTo([19.0, 22.0]),
];
static MESSAGE_SQUARE_PLUS_SHAPES: &[IconShape] = &[
    IconShape::Path(MESSAGE_SQUARE_PLUS_PATH_0),
    IconShape::Path(MESSAGE_SQUARE_PLUS_PATH_1),
    IconShape::Path(MESSAGE_SQUARE_PLUS_PATH_2),
    IconShape::Path(MESSAGE_SQUARE_PLUS_PATH_3),
    IconShape::Path(MESSAGE_SQUARE_PLUS_PATH_4),
];
static MESSAGE_SQUARE_PLUS_SVG: &str = r#"<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
  class="icon icon-tabler icons-tabler-outline icon-tabler-message-plus"
><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M8 9h8" /><path d="M8 13h6" /><path d="M12.01 18.594l-4.01 2.406v-3h-2a3 3 0 0 1 -3 -3v-8a3 3 0 0 1 3 -3h12a3 3 0 0 1 3 3v5.5" /><path d="M16 19h6" /><path d="M19 16v6" /></svg>"#;
static MESSAGE_SQUARE_PLUS: IconData = IconData {
    name: "message-plus",
    shapes: MESSAGE_SQUARE_PLUS_SHAPES,
    svg: MESSAGE_SQUARE_PLUS_SVG,
};

static MINIMIZE_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([5.0, 12.0]),
    IconPathCommand::LineTo([19.0, 12.0]),
];
static MINIMIZE_SHAPES: &[IconShape] = &[IconShape::Path(MINIMIZE_PATH_0)];
static MINIMIZE_SVG: &str = r#"<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
  class="icon icon-tabler icons-tabler-outline icon-tabler-minus"
><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M5 12l14 0" /></svg>"#;
static MINIMIZE: IconData = IconData {
    name: "minus",
    shapes: MINIMIZE_SHAPES,
    svg: MINIMIZE_SVG,
};

static MOON_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([12.0, 3.0]),
    IconPathCommand::CubicTo {
        control_a: [12.132, 3.0],
        control_b: [12.263, 3.0],
        to: [12.393, 3.0],
    },
    IconPathCommand::CubicTo {
        control_a: [9.7422, 5.4632],
        control_b: [9.228, 9.4678],
        to: [11.1707, 12.5207],
    },
    IconPathCommand::CubicTo {
        control_a: [13.1134, 15.5736],
        control_b: [16.9589, 16.8041],
        to: [20.313, 15.446],
    },
    IconPathCommand::CubicTo {
        control_a: [18.5803, 19.6151],
        control_b: [14.0268, 21.8553],
        to: [9.6666, 20.6837],
    },
    IconPathCommand::CubicTo {
        control_a: [5.3064, 19.5121],
        control_b: [2.4891, 15.2913],
        to: [3.0794, 10.8152],
    },
    IconPathCommand::CubicTo {
        control_a: [3.6698, 6.3391],
        control_b: [7.4851, 2.9931],
        to: [12.0, 2.992],
    },
    IconPathCommand::LineTo([12.0, 3.0]),
];
static MOON_SHAPES: &[IconShape] = &[IconShape::Path(MOON_PATH_0)];
static MOON_SVG: &str = r#"<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
  class="icon icon-tabler icons-tabler-outline icon-tabler-moon"
><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M12 3c.132 0 .263 0 .393 0a7.5 7.5 0 0 0 7.92 12.446a9 9 0 1 1 -8.313 -12.454l0 .008" /></svg>"#;
static MOON: IconData = IconData {
    name: "moon",
    shapes: MOON_SHAPES,
    svg: MOON_SVG,
};

static MORE_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([4.0, 12.0]),
    IconPathCommand::CubicTo {
        control_a: [4.0, 12.5523],
        control_b: [4.4477, 13.0],
        to: [5.0, 13.0],
    },
    IconPathCommand::CubicTo {
        control_a: [5.5523, 13.0],
        control_b: [6.0, 12.5523],
        to: [6.0, 12.0],
    },
    IconPathCommand::CubicTo {
        control_a: [6.0, 11.4477],
        control_b: [5.5523, 11.0],
        to: [5.0, 11.0],
    },
    IconPathCommand::CubicTo {
        control_a: [4.4477, 11.0],
        control_b: [4.0, 11.4477],
        to: [4.0, 12.0],
    },
];
static MORE_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([11.0, 12.0]),
    IconPathCommand::CubicTo {
        control_a: [11.0, 12.5523],
        control_b: [11.4477, 13.0],
        to: [12.0, 13.0],
    },
    IconPathCommand::CubicTo {
        control_a: [12.5523, 13.0],
        control_b: [13.0, 12.5523],
        to: [13.0, 12.0],
    },
    IconPathCommand::CubicTo {
        control_a: [13.0, 11.4477],
        control_b: [12.5523, 11.0],
        to: [12.0, 11.0],
    },
    IconPathCommand::CubicTo {
        control_a: [11.4477, 11.0],
        control_b: [11.0, 11.4477],
        to: [11.0, 12.0],
    },
];
static MORE_PATH_2: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([18.0, 12.0]),
    IconPathCommand::CubicTo {
        control_a: [18.0, 12.5523],
        control_b: [18.4477, 13.0],
        to: [19.0, 13.0],
    },
    IconPathCommand::CubicTo {
        control_a: [19.5523, 13.0],
        control_b: [20.0, 12.5523],
        to: [20.0, 12.0],
    },
    IconPathCommand::CubicTo {
        control_a: [20.0, 11.4477],
        control_b: [19.5523, 11.0],
        to: [19.0, 11.0],
    },
    IconPathCommand::CubicTo {
        control_a: [18.4477, 11.0],
        control_b: [18.0, 11.4477],
        to: [18.0, 12.0],
    },
];
static MORE_SHAPES: &[IconShape] = &[
    IconShape::Path(MORE_PATH_0),
    IconShape::Path(MORE_PATH_1),
    IconShape::Path(MORE_PATH_2),
];
static MORE_SVG: &str = r#"<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
  class="icon icon-tabler icons-tabler-outline icon-tabler-dots"
><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M4 12a1 1 0 1 0 2 0a1 1 0 1 0 -2 0" /><path d="M11 12a1 1 0 1 0 2 0a1 1 0 1 0 -2 0" /><path d="M18 12a1 1 0 1 0 2 0a1 1 0 1 0 -2 0" /></svg>"#;
static MORE: IconData = IconData {
    name: "dots",
    shapes: MORE_SHAPES,
    svg: MORE_SVG,
};

static NODES_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([6.0, 9.0]),
    IconPathCommand::CubicTo {
        control_a: [6.0, 12.3137],
        control_b: [8.6863, 15.0],
        to: [12.0, 15.0],
    },
    IconPathCommand::CubicTo {
        control_a: [15.3137, 15.0],
        control_b: [18.0, 12.3137],
        to: [18.0, 9.0],
    },
    IconPathCommand::CubicTo {
        control_a: [18.0, 5.6863],
        control_b: [15.3137, 3.0],
        to: [12.0, 3.0],
    },
    IconPathCommand::CubicTo {
        control_a: [8.6863, 3.0],
        control_b: [6.0, 5.6863],
        to: [6.0, 9.0],
    },
];
static NODES_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([12.0, 3.0]),
    IconPathCommand::CubicTo {
        control_a: [13.333, 3.333],
        control_b: [14.0, 5.333],
        to: [14.0, 9.0],
    },
    IconPathCommand::CubicTo {
        control_a: [14.0, 12.667],
        control_b: [13.333, 14.667],
        to: [12.0, 15.0],
    },
];
static NODES_PATH_2: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([12.0, 3.0]),
    IconPathCommand::CubicTo {
        control_a: [10.667, 3.333],
        control_b: [10.0, 5.333],
        to: [10.0, 9.0],
    },
    IconPathCommand::CubicTo {
        control_a: [10.0, 12.667],
        control_b: [10.667, 14.667],
        to: [12.0, 15.0],
    },
];
static NODES_PATH_3: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([6.0, 9.0]),
    IconPathCommand::LineTo([18.0, 9.0]),
];
static NODES_PATH_4: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([3.0, 20.0]),
    IconPathCommand::LineTo([10.0, 20.0]),
];
static NODES_PATH_5: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([14.0, 20.0]),
    IconPathCommand::LineTo([21.0, 20.0]),
];
static NODES_PATH_6: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([10.0, 20.0]),
    IconPathCommand::CubicTo {
        control_a: [10.0, 21.1046],
        control_b: [10.8954, 22.0],
        to: [12.0, 22.0],
    },
    IconPathCommand::CubicTo {
        control_a: [13.1046, 22.0],
        control_b: [14.0, 21.1046],
        to: [14.0, 20.0],
    },
    IconPathCommand::CubicTo {
        control_a: [14.0, 18.8954],
        control_b: [13.1046, 18.0],
        to: [12.0, 18.0],
    },
    IconPathCommand::CubicTo {
        control_a: [10.8954, 18.0],
        control_b: [10.0, 18.8954],
        to: [10.0, 20.0],
    },
];
static NODES_PATH_7: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([12.0, 15.0]),
    IconPathCommand::LineTo([12.0, 18.0]),
];
static NODES_SHAPES: &[IconShape] = &[
    IconShape::Path(NODES_PATH_0),
    IconShape::Path(NODES_PATH_1),
    IconShape::Path(NODES_PATH_2),
    IconShape::Path(NODES_PATH_3),
    IconShape::Path(NODES_PATH_4),
    IconShape::Path(NODES_PATH_5),
    IconShape::Path(NODES_PATH_6),
    IconShape::Path(NODES_PATH_7),
];
static NODES_SVG: &str = r#"<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
  class="icon icon-tabler icons-tabler-outline icon-tabler-network"
><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M6 9a6 6 0 1 0 12 0a6 6 0 0 0 -12 0" /><path d="M12 3c1.333 .333 2 2.333 2 6s-.667 5.667 -2 6" /><path d="M12 3c-1.333 .333 -2 2.333 -2 6s.667 5.667 2 6" /><path d="M6 9h12" /><path d="M3 20h7" /><path d="M14 20h7" /><path d="M10 20a2 2 0 1 0 4 0a2 2 0 0 0 -4 0" /><path d="M12 15v3" /></svg>"#;
static NODES: IconData = IconData {
    name: "network",
    shapes: NODES_SHAPES,
    svg: NODES_SVG,
};

static PAPERCLIP_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([15.0, 7.0]),
    IconPathCommand::LineTo([8.5, 13.5]),
    IconPathCommand::CubicTo {
        control_a: [7.6716, 14.3284],
        control_b: [7.6716, 15.6716],
        to: [8.5, 16.5],
    },
    IconPathCommand::CubicTo {
        control_a: [9.3284, 17.3284],
        control_b: [10.6716, 17.3284],
        to: [11.5, 16.5],
    },
    IconPathCommand::LineTo([18.0, 10.0]),
    IconPathCommand::CubicTo {
        control_a: [19.6569, 8.3431],
        control_b: [19.6569, 5.6569],
        to: [18.0, 4.0],
    },
    IconPathCommand::CubicTo {
        control_a: [16.3431, 2.3431],
        control_b: [13.6569, 2.3431],
        to: [12.0, 4.0],
    },
    IconPathCommand::LineTo([5.5, 10.5]),
    IconPathCommand::CubicTo {
        control_a: [3.0147, 12.9853],
        control_b: [3.0147, 17.0147],
        to: [5.5, 19.5],
    },
    IconPathCommand::CubicTo {
        control_a: [7.9853, 21.9853],
        control_b: [12.0147, 21.9853],
        to: [14.5, 19.5],
    },
    IconPathCommand::LineTo([21.0, 13.0]),
];
static PAPERCLIP_SHAPES: &[IconShape] = &[IconShape::Path(PAPERCLIP_PATH_0)];
static PAPERCLIP_SVG: &str = r#"<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
  class="icon icon-tabler icons-tabler-outline icon-tabler-paperclip"
><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M15 7l-6.5 6.5a1.5 1.5 0 0 0 3 3l6.5 -6.5a3 3 0 0 0 -6 -6l-6.5 6.5a4.5 4.5 0 0 0 9 9l6.5 -6.5" /></svg>"#;
static PAPERCLIP: IconData = IconData {
    name: "paperclip",
    shapes: PAPERCLIP_SHAPES,
    svg: PAPERCLIP_SVG,
};

static RESTORE_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([7.0, 9.667]),
    IconPathCommand::CubicTo {
        control_a: [7.0, 8.1941],
        control_b: [8.1941, 7.0],
        to: [9.667, 7.0],
    },
    IconPathCommand::LineTo([18.333, 7.0]),
    IconPathCommand::CubicTo {
        control_a: [19.8059, 7.0],
        control_b: [21.0, 8.1941],
        to: [21.0, 9.667],
    },
    IconPathCommand::LineTo([21.0, 18.333]),
    IconPathCommand::CubicTo {
        control_a: [21.0, 19.8059],
        control_b: [19.8059, 21.0],
        to: [18.333, 21.0],
    },
    IconPathCommand::LineTo([9.667, 21.0]),
    IconPathCommand::CubicTo {
        control_a: [8.1941, 21.0],
        control_b: [7.0, 19.8059],
        to: [7.0, 18.333],
    },
    IconPathCommand::LineTo([7.0, 9.667]),
];
static RESTORE_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([4.012, 16.737]),
    IconPathCommand::CubicTo {
        control_a: [3.3878, 16.3812],
        control_b: [3.0017, 15.7185],
        to: [3.0, 15.0],
    },
    IconPathCommand::LineTo([3.0, 5.0]),
    IconPathCommand::CubicTo {
        control_a: [3.0, 3.9],
        control_b: [3.9, 3.0],
        to: [5.0, 3.0],
    },
    IconPathCommand::LineTo([15.0, 3.0]),
    IconPathCommand::CubicTo {
        control_a: [15.75, 3.0],
        control_b: [16.158, 3.385],
        to: [16.5, 4.0],
    },
];
static RESTORE_SHAPES: &[IconShape] = &[
    IconShape::Path(RESTORE_PATH_0),
    IconShape::Path(RESTORE_PATH_1),
];
static RESTORE_SVG: &str = r#"<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
  class="icon icon-tabler icons-tabler-outline icon-tabler-copy"
><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M7 9.667a2.667 2.667 0 0 1 2.667 -2.667h8.666a2.667 2.667 0 0 1 2.667 2.667v8.666a2.667 2.667 0 0 1 -2.667 2.667h-8.666a2.667 2.667 0 0 1 -2.667 -2.667l0 -8.666" /><path d="M4.012 16.737a2.005 2.005 0 0 1 -1.012 -1.737v-10c0 -1.1 .9 -2 2 -2h10c.75 0 1.158 .385 1.5 1" /></svg>"#;
static RESTORE: IconData = IconData {
    name: "copy",
    shapes: RESTORE_SHAPES,
    svg: RESTORE_SVG,
};

static SEARCH_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([3.0, 10.0]),
    IconPathCommand::CubicTo {
        control_a: [3.0, 13.866],
        control_b: [6.134, 17.0],
        to: [10.0, 17.0],
    },
    IconPathCommand::CubicTo {
        control_a: [13.866, 17.0],
        control_b: [17.0, 13.866],
        to: [17.0, 10.0],
    },
    IconPathCommand::CubicTo {
        control_a: [17.0, 6.134],
        control_b: [13.866, 3.0],
        to: [10.0, 3.0],
    },
    IconPathCommand::CubicTo {
        control_a: [6.134, 3.0],
        control_b: [3.0, 6.134],
        to: [3.0, 10.0],
    },
];
static SEARCH_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([21.0, 21.0]),
    IconPathCommand::LineTo([15.0, 15.0]),
];
static SEARCH_SHAPES: &[IconShape] = &[
    IconShape::Path(SEARCH_PATH_0),
    IconShape::Path(SEARCH_PATH_1),
];
static SEARCH_SVG: &str = r#"<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
  class="icon icon-tabler icons-tabler-outline icon-tabler-search"
><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M3 10a7 7 0 1 0 14 0a7 7 0 1 0 -14 0" /><path d="M21 21l-6 -6" /></svg>"#;
static SEARCH: IconData = IconData {
    name: "search",
    shapes: SEARCH_SHAPES,
    svg: SEARCH_SVG,
};

static SETTINGS_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([10.325, 4.317]),
    IconPathCommand::CubicTo {
        control_a: [10.751, 2.561],
        control_b: [13.249, 2.561],
        to: [13.675, 4.317],
    },
    IconPathCommand::CubicTo {
        control_a: [13.8046, 4.8521],
        control_b: [14.182, 5.293],
        to: [14.6907, 5.5037],
    },
    IconPathCommand::CubicTo {
        control_a: [15.1993, 5.7145],
        control_b: [15.7779, 5.6696],
        to: [16.248, 5.383],
    },
    IconPathCommand::CubicTo {
        control_a: [17.791, 4.443],
        control_b: [19.558, 6.209],
        to: [18.618, 7.753],
    },
    IconPathCommand::CubicTo {
        control_a: [18.3318, 8.2229],
        control_b: [18.2871, 8.8011],
        to: [18.4975, 9.3094],
    },
    IconPathCommand::CubicTo {
        control_a: [18.708, 9.8177],
        control_b: [19.1484, 10.195],
        to: [19.683, 10.325],
    },
    IconPathCommand::CubicTo {
        control_a: [21.439, 10.751],
        control_b: [21.439, 13.249],
        to: [19.683, 13.675],
    },
    IconPathCommand::CubicTo {
        control_a: [19.1479, 13.8046],
        control_b: [18.707, 14.182],
        to: [18.4963, 14.6907],
    },
    IconPathCommand::CubicTo {
        control_a: [18.2855, 15.1993],
        control_b: [18.3304, 15.7779],
        to: [18.617, 16.248],
    },
    IconPathCommand::CubicTo {
        control_a: [19.557, 17.791],
        control_b: [17.791, 19.558],
        to: [16.247, 18.618],
    },
    IconPathCommand::CubicTo {
        control_a: [15.7771, 18.3318],
        control_b: [15.1989, 18.2871],
        to: [14.6906, 18.4975],
    },
    IconPathCommand::CubicTo {
        control_a: [14.1823, 18.708],
        control_b: [13.805, 19.1484],
        to: [13.675, 19.683],
    },
    IconPathCommand::CubicTo {
        control_a: [13.249, 21.439],
        control_b: [10.751, 21.439],
        to: [10.325, 19.683],
    },
    IconPathCommand::CubicTo {
        control_a: [10.1954, 19.1479],
        control_b: [9.818, 18.707],
        to: [9.3093, 18.4963],
    },
    IconPathCommand::CubicTo {
        control_a: [8.8007, 18.2855],
        control_b: [8.2221, 18.3304],
        to: [7.752, 18.617],
    },
    IconPathCommand::CubicTo {
        control_a: [6.209, 19.557],
        control_b: [4.442, 17.791],
        to: [5.382, 16.247],
    },
    IconPathCommand::CubicTo {
        control_a: [5.6682, 15.7771],
        control_b: [5.7129, 15.1989],
        to: [5.5025, 14.6906],
    },
    IconPathCommand::CubicTo {
        control_a: [5.292, 14.1823],
        control_b: [4.8516, 13.805],
        to: [4.317, 13.675],
    },
    IconPathCommand::CubicTo {
        control_a: [2.561, 13.249],
        control_b: [2.561, 10.751],
        to: [4.317, 10.325],
    },
    IconPathCommand::CubicTo {
        control_a: [4.8521, 10.1954],
        control_b: [5.293, 9.818],
        to: [5.5037, 9.3093],
    },
    IconPathCommand::CubicTo {
        control_a: [5.7145, 8.8007],
        control_b: [5.6696, 8.2221],
        to: [5.383, 7.752],
    },
    IconPathCommand::CubicTo {
        control_a: [4.443, 6.209],
        control_b: [6.209, 4.442],
        to: [7.753, 5.382],
    },
    IconPathCommand::CubicTo {
        control_a: [8.753, 5.99],
        control_b: [10.049, 5.452],
        to: [10.325, 4.317],
    },
];
static SETTINGS_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([9.0, 12.0]),
    IconPathCommand::CubicTo {
        control_a: [9.0, 13.6569],
        control_b: [10.3431, 15.0],
        to: [12.0, 15.0],
    },
    IconPathCommand::CubicTo {
        control_a: [13.6569, 15.0],
        control_b: [15.0, 13.6569],
        to: [15.0, 12.0],
    },
    IconPathCommand::CubicTo {
        control_a: [15.0, 10.3431],
        control_b: [13.6569, 9.0],
        to: [12.0, 9.0],
    },
    IconPathCommand::CubicTo {
        control_a: [10.3431, 9.0],
        control_b: [9.0, 10.3431],
        to: [9.0, 12.0],
    },
];
static SETTINGS_SHAPES: &[IconShape] = &[
    IconShape::Path(SETTINGS_PATH_0),
    IconShape::Path(SETTINGS_PATH_1),
];
static SETTINGS_SVG: &str = r#"<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
  class="icon icon-tabler icons-tabler-outline icon-tabler-settings"
><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M10.325 4.317c.426 -1.756 2.924 -1.756 3.35 0a1.724 1.724 0 0 0 2.573 1.066c1.543 -.94 3.31 .826 2.37 2.37a1.724 1.724 0 0 0 1.065 2.572c1.756 .426 1.756 2.924 0 3.35a1.724 1.724 0 0 0 -1.066 2.573c.94 1.543 -.826 3.31 -2.37 2.37a1.724 1.724 0 0 0 -2.572 1.065c-.426 1.756 -2.924 1.756 -3.35 0a1.724 1.724 0 0 0 -2.573 -1.066c-1.543 .94 -3.31 -.826 -2.37 -2.37a1.724 1.724 0 0 0 -1.065 -2.572c-1.756 -.426 -1.756 -2.924 0 -3.35a1.724 1.724 0 0 0 1.066 -2.573c-.94 -1.543 .826 -3.31 2.37 -2.37c1 .608 2.296 .07 2.572 -1.065" /><path d="M9 12a3 3 0 1 0 6 0a3 3 0 0 0 -6 0" /></svg>"#;
static SETTINGS: IconData = IconData {
    name: "settings",
    shapes: SETTINGS_SHAPES,
    svg: SETTINGS_SVG,
};

static SHIELD_CHECK_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([11.46, 20.846]),
    IconPathCommand::CubicTo {
        control_a: [5.1955, 18.9041],
        control_b: [1.6504, 12.2924],
        to: [3.5, 6.0],
    },
    IconPathCommand::CubicTo {
        control_a: [6.6155, 6.1426],
        control_b: [9.6642, 5.0666],
        to: [12.0, 3.0],
    },
    IconPathCommand::CubicTo {
        control_a: [14.3358, 5.0666],
        control_b: [17.3845, 6.1426],
        to: [20.5, 6.0],
    },
    IconPathCommand::CubicTo {
        control_a: [21.1787, 8.3091],
        control_b: [21.1473, 10.7689],
        to: [20.41, 13.06],
    },
];
static SHIELD_CHECK_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([15.0, 19.0]),
    IconPathCommand::LineTo([17.0, 21.0]),
    IconPathCommand::LineTo([21.0, 17.0]),
];
static SHIELD_CHECK_SHAPES: &[IconShape] = &[
    IconShape::Path(SHIELD_CHECK_PATH_0),
    IconShape::Path(SHIELD_CHECK_PATH_1),
];
static SHIELD_CHECK_SVG: &str = r#"<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
  class="icon icon-tabler icons-tabler-outline icon-tabler-shield-check"
><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M11.46 20.846a12 12 0 0 1 -7.96 -14.846a12 12 0 0 0 8.5 -3a12 12 0 0 0 8.5 3a12 12 0 0 1 -.09 7.06" /><path d="M15 19l2 2l4 -4" /></svg>"#;
static SHIELD_CHECK: IconData = IconData {
    name: "shield-check",
    shapes: SHIELD_CHECK_SHAPES,
    svg: SHIELD_CHECK_SVG,
};

static SIDEBAR_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([4.0, 6.0]),
    IconPathCommand::CubicTo {
        control_a: [4.0, 4.8954],
        control_b: [4.8954, 4.0],
        to: [6.0, 4.0],
    },
    IconPathCommand::LineTo([18.0, 4.0]),
    IconPathCommand::CubicTo {
        control_a: [19.1046, 4.0],
        control_b: [20.0, 4.8954],
        to: [20.0, 6.0],
    },
    IconPathCommand::LineTo([20.0, 18.0]),
    IconPathCommand::CubicTo {
        control_a: [20.0, 19.1046],
        control_b: [19.1046, 20.0],
        to: [18.0, 20.0],
    },
    IconPathCommand::LineTo([6.0, 20.0]),
    IconPathCommand::CubicTo {
        control_a: [4.8954, 20.0],
        control_b: [4.0, 19.1046],
        to: [4.0, 18.0],
    },
    IconPathCommand::LineTo([4.0, 6.0]),
];
static SIDEBAR_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([9.0, 4.0]),
    IconPathCommand::LineTo([9.0, 20.0]),
];
static SIDEBAR_SHAPES: &[IconShape] = &[
    IconShape::Path(SIDEBAR_PATH_0),
    IconShape::Path(SIDEBAR_PATH_1),
];
static SIDEBAR_SVG: &str = r#"<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
  class="icon icon-tabler icons-tabler-outline icon-tabler-layout-sidebar"
><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M4 6a2 2 0 0 1 2 -2h12a2 2 0 0 1 2 2v12a2 2 0 0 1 -2 2h-12a2 2 0 0 1 -2 -2l0 -12" /><path d="M9 4l0 16" /></svg>"#;
static SIDEBAR: IconData = IconData {
    name: "layout-sidebar",
    shapes: SIDEBAR_SHAPES,
    svg: SIDEBAR_SVG,
};

static SPARKLES_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([16.0, 18.0]),
    IconPathCommand::CubicTo {
        control_a: [17.1046, 18.0],
        control_b: [18.0, 18.8954],
        to: [18.0, 20.0],
    },
    IconPathCommand::CubicTo {
        control_a: [18.0, 18.8954],
        control_b: [18.8954, 18.0],
        to: [20.0, 18.0],
    },
    IconPathCommand::CubicTo {
        control_a: [18.8954, 18.0],
        control_b: [18.0, 17.1046],
        to: [18.0, 16.0],
    },
    IconPathCommand::CubicTo {
        control_a: [18.0, 17.1046],
        control_b: [17.1046, 18.0],
        to: [16.0, 18.0],
    },
    IconPathCommand::MoveTo([16.0, 6.0]),
    IconPathCommand::CubicTo {
        control_a: [17.1046, 6.0],
        control_b: [18.0, 6.8954],
        to: [18.0, 8.0],
    },
    IconPathCommand::CubicTo {
        control_a: [18.0, 6.8954],
        control_b: [18.8954, 6.0],
        to: [20.0, 6.0],
    },
    IconPathCommand::CubicTo {
        control_a: [18.8954, 6.0],
        control_b: [18.0, 5.1046],
        to: [18.0, 4.0],
    },
    IconPathCommand::CubicTo {
        control_a: [18.0, 5.1046],
        control_b: [17.1046, 6.0],
        to: [16.0, 6.0],
    },
    IconPathCommand::MoveTo([9.0, 18.0]),
    IconPathCommand::CubicTo {
        control_a: [9.0, 14.6863],
        control_b: [11.6863, 12.0],
        to: [15.0, 12.0],
    },
    IconPathCommand::CubicTo {
        control_a: [11.6863, 12.0],
        control_b: [9.0, 9.3137],
        to: [9.0, 6.0],
    },
    IconPathCommand::CubicTo {
        control_a: [9.0, 9.3137],
        control_b: [6.3137, 12.0],
        to: [3.0, 12.0],
    },
    IconPathCommand::CubicTo {
        control_a: [6.3137, 12.0],
        control_b: [9.0, 14.6863],
        to: [9.0, 18.0],
    },
];
static SPARKLES_SHAPES: &[IconShape] = &[IconShape::Path(SPARKLES_PATH_0)];
static SPARKLES_SVG: &str = r#"<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
  class="icon icon-tabler icons-tabler-outline icon-tabler-sparkles"
><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M16 18a2 2 0 0 1 2 2a2 2 0 0 1 2 -2a2 2 0 0 1 -2 -2a2 2 0 0 1 -2 2m0 -12a2 2 0 0 1 2 2a2 2 0 0 1 2 -2a2 2 0 0 1 -2 -2a2 2 0 0 1 -2 2m-7 12a6 6 0 0 1 6 -6a6 6 0 0 1 -6 -6a6 6 0 0 1 -6 6a6 6 0 0 1 6 6" /></svg>"#;
static SPARKLES: IconData = IconData {
    name: "sparkles",
    shapes: SPARKLES_SHAPES,
    svg: SPARKLES_SVG,
};

static WORKSPACE_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([5.0, 4.0]),
    IconPathCommand::LineTo([9.0, 4.0]),
    IconPathCommand::CubicTo {
        control_a: [9.5523, 4.0],
        control_b: [10.0, 4.4477],
        to: [10.0, 5.0],
    },
    IconPathCommand::LineTo([10.0, 11.0]),
    IconPathCommand::CubicTo {
        control_a: [10.0, 11.5523],
        control_b: [9.5523, 12.0],
        to: [9.0, 12.0],
    },
    IconPathCommand::LineTo([5.0, 12.0]),
    IconPathCommand::CubicTo {
        control_a: [4.4477, 12.0],
        control_b: [4.0, 11.5523],
        to: [4.0, 11.0],
    },
    IconPathCommand::LineTo([4.0, 5.0]),
    IconPathCommand::CubicTo {
        control_a: [4.0, 4.4477],
        control_b: [4.4477, 4.0],
        to: [5.0, 4.0],
    },
];
static WORKSPACE_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([5.0, 16.0]),
    IconPathCommand::LineTo([9.0, 16.0]),
    IconPathCommand::CubicTo {
        control_a: [9.5523, 16.0],
        control_b: [10.0, 16.4477],
        to: [10.0, 17.0],
    },
    IconPathCommand::LineTo([10.0, 19.0]),
    IconPathCommand::CubicTo {
        control_a: [10.0, 19.5523],
        control_b: [9.5523, 20.0],
        to: [9.0, 20.0],
    },
    IconPathCommand::LineTo([5.0, 20.0]),
    IconPathCommand::CubicTo {
        control_a: [4.4477, 20.0],
        control_b: [4.0, 19.5523],
        to: [4.0, 19.0],
    },
    IconPathCommand::LineTo([4.0, 17.0]),
    IconPathCommand::CubicTo {
        control_a: [4.0, 16.4477],
        control_b: [4.4477, 16.0],
        to: [5.0, 16.0],
    },
];
static WORKSPACE_PATH_2: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([15.0, 12.0]),
    IconPathCommand::LineTo([19.0, 12.0]),
    IconPathCommand::CubicTo {
        control_a: [19.5523, 12.0],
        control_b: [20.0, 12.4477],
        to: [20.0, 13.0],
    },
    IconPathCommand::LineTo([20.0, 19.0]),
    IconPathCommand::CubicTo {
        control_a: [20.0, 19.5523],
        control_b: [19.5523, 20.0],
        to: [19.0, 20.0],
    },
    IconPathCommand::LineTo([15.0, 20.0]),
    IconPathCommand::CubicTo {
        control_a: [14.4477, 20.0],
        control_b: [14.0, 19.5523],
        to: [14.0, 19.0],
    },
    IconPathCommand::LineTo([14.0, 13.0]),
    IconPathCommand::CubicTo {
        control_a: [14.0, 12.4477],
        control_b: [14.4477, 12.0],
        to: [15.0, 12.0],
    },
];
static WORKSPACE_PATH_3: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([15.0, 4.0]),
    IconPathCommand::LineTo([19.0, 4.0]),
    IconPathCommand::CubicTo {
        control_a: [19.5523, 4.0],
        control_b: [20.0, 4.4477],
        to: [20.0, 5.0],
    },
    IconPathCommand::LineTo([20.0, 7.0]),
    IconPathCommand::CubicTo {
        control_a: [20.0, 7.5523],
        control_b: [19.5523, 8.0],
        to: [19.0, 8.0],
    },
    IconPathCommand::LineTo([15.0, 8.0]),
    IconPathCommand::CubicTo {
        control_a: [14.4477, 8.0],
        control_b: [14.0, 7.5523],
        to: [14.0, 7.0],
    },
    IconPathCommand::LineTo([14.0, 5.0]),
    IconPathCommand::CubicTo {
        control_a: [14.0, 4.4477],
        control_b: [14.4477, 4.0],
        to: [15.0, 4.0],
    },
];
static WORKSPACE_SHAPES: &[IconShape] = &[
    IconShape::Path(WORKSPACE_PATH_0),
    IconShape::Path(WORKSPACE_PATH_1),
    IconShape::Path(WORKSPACE_PATH_2),
    IconShape::Path(WORKSPACE_PATH_3),
];
static WORKSPACE_SVG: &str = r#"<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
  class="icon icon-tabler icons-tabler-outline icon-tabler-layout-dashboard"
><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M5 4h4a1 1 0 0 1 1 1v6a1 1 0 0 1 -1 1h-4a1 1 0 0 1 -1 -1v-6a1 1 0 0 1 1 -1" /><path d="M5 16h4a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-4a1 1 0 0 1 -1 -1v-2a1 1 0 0 1 1 -1" /><path d="M15 12h4a1 1 0 0 1 1 1v6a1 1 0 0 1 -1 1h-4a1 1 0 0 1 -1 -1v-6a1 1 0 0 1 1 -1" /><path d="M15 4h4a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-4a1 1 0 0 1 -1 -1v-2a1 1 0 0 1 1 -1" /></svg>"#;
static WORKSPACE: IconData = IconData {
    name: "layout-dashboard",
    shapes: WORKSPACE_SHAPES,
    svg: WORKSPACE_SVG,
};

static ACTIVITY_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([3.0, 12.0]),
    IconPathCommand::LineTo([7.0, 12.0]),
    IconPathCommand::LineTo([10.0, 20.0]),
    IconPathCommand::LineTo([14.0, 4.0]),
    IconPathCommand::LineTo([17.0, 12.0]),
    IconPathCommand::LineTo([21.0, 12.0]),
];
static ACTIVITY_SHAPES: &[IconShape] = &[IconShape::Path(ACTIVITY_PATH_0)];
static ACTIVITY_SVG: &str = r#"<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
  class="icon icon-tabler icons-tabler-outline icon-tabler-activity"
><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M3 12h4l3 8l4 -16l3 8h4" /></svg>"#;
static ACTIVITY: IconData = IconData {
    name: "activity",
    shapes: ACTIVITY_SHAPES,
    svg: ACTIVITY_SVG,
};

static ATOM_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([12.0, 12.0]),
    IconPathCommand::LineTo([12.0, 12.01]),
];
static ATOM_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([19.071, 4.929]),
    IconPathCommand::CubicTo {
        control_a: [17.509, 3.367],
        control_b: [13.071, 5.266],
        to: [9.171, 9.172],
    },
    IconPathCommand::CubicTo {
        control_a: [5.266, 13.077],
        control_b: [3.367, 17.509],
        to: [4.929, 19.072],
    },
    IconPathCommand::CubicTo {
        control_a: [6.491, 20.633],
        control_b: [10.929, 18.734],
        to: [14.829, 14.828],
    },
    IconPathCommand::CubicTo {
        control_a: [18.734, 10.923],
        control_b: [20.633, 6.491],
        to: [19.071, 4.928],
    },
];
static ATOM_PATH_2: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([4.929, 4.929]),
    IconPathCommand::CubicTo {
        control_a: [3.367, 6.491],
        control_b: [5.266, 10.929],
        to: [9.172, 14.829],
    },
    IconPathCommand::CubicTo {
        control_a: [13.077, 18.734],
        control_b: [17.509, 20.633],
        to: [19.072, 19.071],
    },
    IconPathCommand::CubicTo {
        control_a: [20.633, 17.509],
        control_b: [18.734, 13.071],
        to: [14.828, 9.171],
    },
    IconPathCommand::CubicTo {
        control_a: [10.923, 5.266],
        control_b: [6.491, 3.367],
        to: [4.928, 4.929],
    },
];
static ATOM_SHAPES: &[IconShape] = &[
    IconShape::Path(ATOM_PATH_0),
    IconShape::Path(ATOM_PATH_1),
    IconShape::Path(ATOM_PATH_2),
];
static ATOM_SVG: &str = r#"<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
  class="icon icon-tabler icons-tabler-outline icon-tabler-atom"
><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M12 12v.01" /><path d="M19.071 4.929c-1.562 -1.562 -6 .337 -9.9 4.243c-3.905 3.905 -5.804 8.337 -4.242 9.9c1.562 1.561 6 -.338 9.9 -4.244c3.905 -3.905 5.804 -8.337 4.242 -9.9" /><path d="M4.929 4.929c-1.562 1.562 .337 6 4.243 9.9c3.905 3.905 8.337 5.804 9.9 4.242c1.561 -1.562 -.338 -6 -4.244 -9.9c-3.905 -3.905 -8.337 -5.804 -9.9 -4.242" /></svg>"#;
static ATOM: IconData = IconData {
    name: "atom",
    shapes: ATOM_SHAPES,
    svg: ATOM_SVG,
};

static BLEND_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([3.0, 12.0]),
    IconPathCommand::CubicTo {
        control_a: [3.0, 16.9706],
        control_b: [7.0294, 21.0],
        to: [12.0, 21.0],
    },
    IconPathCommand::CubicTo {
        control_a: [16.9706, 21.0],
        control_b: [21.0, 16.9706],
        to: [21.0, 12.0],
    },
    IconPathCommand::CubicTo {
        control_a: [21.0, 7.0294],
        control_b: [16.9706, 3.0],
        to: [12.0, 3.0],
    },
    IconPathCommand::CubicTo {
        control_a: [7.0294, 3.0],
        control_b: [3.0, 7.0294],
        to: [3.0, 12.0],
    },
];
static BLEND_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([12.0, 17.0]),
    IconPathCommand::CubicTo {
        control_a: [14.7614, 17.0],
        control_b: [17.0, 14.7614],
        to: [17.0, 12.0],
    },
    IconPathCommand::CubicTo {
        control_a: [17.0, 9.2386],
        control_b: [14.7614, 7.0],
        to: [12.0, 7.0],
    },
    IconPathCommand::LineTo([12.0, 17.0]),
];
static BLEND_SHAPES: &[IconShape] = &[IconShape::Path(BLEND_PATH_0), IconShape::Path(BLEND_PATH_1)];
static BLEND_SVG: &str = r#"<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
  class="icon icon-tabler icons-tabler-outline icon-tabler-contrast"
><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M3 12a9 9 0 1 0 18 0a9 9 0 1 0 -18 0" /><path d="M12 17a5 5 0 0 0 0 -10v10" /></svg>"#;
static BLEND: IconData = IconData {
    name: "contrast",
    shapes: BLEND_SHAPES,
    svg: BLEND_SVG,
};

static BUG_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([9.0, 9.0]),
    IconPathCommand::LineTo([9.0, 8.0]),
    IconPathCommand::CubicTo {
        control_a: [9.0, 6.3431],
        control_b: [10.3431, 5.0],
        to: [12.0, 5.0],
    },
    IconPathCommand::CubicTo {
        control_a: [13.6569, 5.0],
        control_b: [15.0, 6.3431],
        to: [15.0, 8.0],
    },
    IconPathCommand::LineTo([15.0, 9.0]),
];
static BUG_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([8.0, 9.0]),
    IconPathCommand::LineTo([16.0, 9.0]),
    IconPathCommand::CubicTo {
        control_a: [16.5956, 9.8926],
        control_b: [16.9409, 10.9286],
        to: [17.0, 12.0],
    },
    IconPathCommand::LineTo([17.0, 15.0]),
    IconPathCommand::CubicTo {
        control_a: [17.0, 17.7614],
        control_b: [14.7614, 20.0],
        to: [12.0, 20.0],
    },
    IconPathCommand::CubicTo {
        control_a: [9.2386, 20.0],
        control_b: [7.0, 17.7614],
        to: [7.0, 15.0],
    },
    IconPathCommand::LineTo([7.0, 12.0]),
    IconPathCommand::CubicTo {
        control_a: [7.0591, 10.9286],
        control_b: [7.4044, 9.8926],
        to: [8.0, 9.0],
    },
];
static BUG_PATH_2: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([3.0, 13.0]),
    IconPathCommand::LineTo([7.0, 13.0]),
];
static BUG_PATH_3: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([17.0, 13.0]),
    IconPathCommand::LineTo([21.0, 13.0]),
];
static BUG_PATH_4: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([12.0, 20.0]),
    IconPathCommand::LineTo([12.0, 14.0]),
];
static BUG_PATH_5: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([4.0, 19.0]),
    IconPathCommand::LineTo([7.35, 17.0]),
];
static BUG_PATH_6: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([20.0, 19.0]),
    IconPathCommand::LineTo([16.65, 17.0]),
];
static BUG_PATH_7: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([4.0, 7.0]),
    IconPathCommand::LineTo([7.75, 9.4]),
];
static BUG_PATH_8: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([20.0, 7.0]),
    IconPathCommand::LineTo([16.25, 9.4]),
];
static BUG_SHAPES: &[IconShape] = &[
    IconShape::Path(BUG_PATH_0),
    IconShape::Path(BUG_PATH_1),
    IconShape::Path(BUG_PATH_2),
    IconShape::Path(BUG_PATH_3),
    IconShape::Path(BUG_PATH_4),
    IconShape::Path(BUG_PATH_5),
    IconShape::Path(BUG_PATH_6),
    IconShape::Path(BUG_PATH_7),
    IconShape::Path(BUG_PATH_8),
];
static BUG_SVG: &str = r#"<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
  class="icon icon-tabler icons-tabler-outline icon-tabler-bug"
><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M9 9v-1a3 3 0 0 1 6 0v1" /><path d="M8 9h8a6 6 0 0 1 1 3v3a5 5 0 0 1 -10 0v-3a6 6 0 0 1 1 -3" /><path d="M3 13l4 0" /><path d="M17 13l4 0" /><path d="M12 20l0 -6" /><path d="M4 19l3.35 -2" /><path d="M20 19l-3.35 -2" /><path d="M4 7l3.75 2.4" /><path d="M20 7l-3.75 2.4" /></svg>"#;
static BUG: IconData = IconData {
    name: "bug",
    shapes: BUG_SHAPES,
    svg: BUG_SVG,
};

static CLAPPERBOARD_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([4.0, 6.0]),
    IconPathCommand::CubicTo {
        control_a: [4.0, 4.8954],
        control_b: [4.8954, 4.0],
        to: [6.0, 4.0],
    },
    IconPathCommand::LineTo([18.0, 4.0]),
    IconPathCommand::CubicTo {
        control_a: [19.1046, 4.0],
        control_b: [20.0, 4.8954],
        to: [20.0, 6.0],
    },
    IconPathCommand::LineTo([20.0, 18.0]),
    IconPathCommand::CubicTo {
        control_a: [20.0, 19.1046],
        control_b: [19.1046, 20.0],
        to: [18.0, 20.0],
    },
    IconPathCommand::LineTo([6.0, 20.0]),
    IconPathCommand::CubicTo {
        control_a: [4.8954, 20.0],
        control_b: [4.0, 19.1046],
        to: [4.0, 18.0],
    },
    IconPathCommand::LineTo([4.0, 6.0]),
];
static CLAPPERBOARD_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([8.0, 4.0]),
    IconPathCommand::LineTo([8.0, 20.0]),
];
static CLAPPERBOARD_PATH_2: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([16.0, 4.0]),
    IconPathCommand::LineTo([16.0, 20.0]),
];
static CLAPPERBOARD_PATH_3: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([4.0, 8.0]),
    IconPathCommand::LineTo([8.0, 8.0]),
];
static CLAPPERBOARD_PATH_4: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([4.0, 16.0]),
    IconPathCommand::LineTo([8.0, 16.0]),
];
static CLAPPERBOARD_PATH_5: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([4.0, 12.0]),
    IconPathCommand::LineTo([20.0, 12.0]),
];
static CLAPPERBOARD_PATH_6: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([16.0, 8.0]),
    IconPathCommand::LineTo([20.0, 8.0]),
];
static CLAPPERBOARD_PATH_7: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([16.0, 16.0]),
    IconPathCommand::LineTo([20.0, 16.0]),
];
static CLAPPERBOARD_SHAPES: &[IconShape] = &[
    IconShape::Path(CLAPPERBOARD_PATH_0),
    IconShape::Path(CLAPPERBOARD_PATH_1),
    IconShape::Path(CLAPPERBOARD_PATH_2),
    IconShape::Path(CLAPPERBOARD_PATH_3),
    IconShape::Path(CLAPPERBOARD_PATH_4),
    IconShape::Path(CLAPPERBOARD_PATH_5),
    IconShape::Path(CLAPPERBOARD_PATH_6),
    IconShape::Path(CLAPPERBOARD_PATH_7),
];
static CLAPPERBOARD_SVG: &str = r#"<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
  class="icon icon-tabler icons-tabler-outline icon-tabler-movie"
><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M4 6a2 2 0 0 1 2 -2h12a2 2 0 0 1 2 2v12a2 2 0 0 1 -2 2h-12a2 2 0 0 1 -2 -2l0 -12" /><path d="M8 4l0 16" /><path d="M16 4l0 16" /><path d="M4 8l4 0" /><path d="M4 16l4 0" /><path d="M4 12l16 0" /><path d="M16 8l4 0" /><path d="M16 16l4 0" /></svg>"#;
static CLAPPERBOARD: IconData = IconData {
    name: "movie",
    shapes: CLAPPERBOARD_SHAPES,
    svg: CLAPPERBOARD_SVG,
};

static CPU_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([5.0, 6.0]),
    IconPathCommand::CubicTo {
        control_a: [5.0, 5.4477],
        control_b: [5.4477, 5.0],
        to: [6.0, 5.0],
    },
    IconPathCommand::LineTo([18.0, 5.0]),
    IconPathCommand::CubicTo {
        control_a: [18.5523, 5.0],
        control_b: [19.0, 5.4477],
        to: [19.0, 6.0],
    },
    IconPathCommand::LineTo([19.0, 18.0]),
    IconPathCommand::CubicTo {
        control_a: [19.0, 18.5523],
        control_b: [18.5523, 19.0],
        to: [18.0, 19.0],
    },
    IconPathCommand::LineTo([6.0, 19.0]),
    IconPathCommand::CubicTo {
        control_a: [5.4477, 19.0],
        control_b: [5.0, 18.5523],
        to: [5.0, 18.0],
    },
    IconPathCommand::LineTo([5.0, 6.0]),
];
static CPU_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([9.0, 9.0]),
    IconPathCommand::LineTo([15.0, 9.0]),
    IconPathCommand::LineTo([15.0, 15.0]),
    IconPathCommand::LineTo([9.0, 15.0]),
    IconPathCommand::LineTo([9.0, 9.0]),
];
static CPU_PATH_2: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([3.0, 10.0]),
    IconPathCommand::LineTo([5.0, 10.0]),
];
static CPU_PATH_3: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([3.0, 14.0]),
    IconPathCommand::LineTo([5.0, 14.0]),
];
static CPU_PATH_4: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([10.0, 3.0]),
    IconPathCommand::LineTo([10.0, 5.0]),
];
static CPU_PATH_5: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([14.0, 3.0]),
    IconPathCommand::LineTo([14.0, 5.0]),
];
static CPU_PATH_6: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([21.0, 10.0]),
    IconPathCommand::LineTo([19.0, 10.0]),
];
static CPU_PATH_7: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([21.0, 14.0]),
    IconPathCommand::LineTo([19.0, 14.0]),
];
static CPU_PATH_8: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([14.0, 21.0]),
    IconPathCommand::LineTo([14.0, 19.0]),
];
static CPU_PATH_9: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([10.0, 21.0]),
    IconPathCommand::LineTo([10.0, 19.0]),
];
static CPU_SHAPES: &[IconShape] = &[
    IconShape::Path(CPU_PATH_0),
    IconShape::Path(CPU_PATH_1),
    IconShape::Path(CPU_PATH_2),
    IconShape::Path(CPU_PATH_3),
    IconShape::Path(CPU_PATH_4),
    IconShape::Path(CPU_PATH_5),
    IconShape::Path(CPU_PATH_6),
    IconShape::Path(CPU_PATH_7),
    IconShape::Path(CPU_PATH_8),
    IconShape::Path(CPU_PATH_9),
];
static CPU_SVG: &str = r#"<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
  class="icon icon-tabler icons-tabler-outline icon-tabler-cpu"
><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M5 6a1 1 0 0 1 1 -1h12a1 1 0 0 1 1 1v12a1 1 0 0 1 -1 1h-12a1 1 0 0 1 -1 -1l0 -12" /><path d="M9 9h6v6h-6l0 -6" /><path d="M3 10h2" /><path d="M3 14h2" /><path d="M10 3v2" /><path d="M14 3v2" /><path d="M21 10h-2" /><path d="M21 14h-2" /><path d="M14 21v-2" /><path d="M10 21v-2" /></svg>"#;
static CPU: IconData = IconData {
    name: "cpu",
    shapes: CPU_SHAPES,
    svg: CPU_SVG,
};

static GAMEPAD2_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([2.0, 8.0]),
    IconPathCommand::CubicTo {
        control_a: [2.0, 6.8954],
        control_b: [2.8954, 6.0],
        to: [4.0, 6.0],
    },
    IconPathCommand::LineTo([20.0, 6.0]),
    IconPathCommand::CubicTo {
        control_a: [21.1046, 6.0],
        control_b: [22.0, 6.8954],
        to: [22.0, 8.0],
    },
    IconPathCommand::LineTo([22.0, 16.0]),
    IconPathCommand::CubicTo {
        control_a: [22.0, 17.1046],
        control_b: [21.1046, 18.0],
        to: [20.0, 18.0],
    },
    IconPathCommand::LineTo([4.0, 18.0]),
    IconPathCommand::CubicTo {
        control_a: [2.8954, 18.0],
        control_b: [2.0, 17.1046],
        to: [2.0, 16.0],
    },
    IconPathCommand::LineTo([2.0, 8.0]),
];
static GAMEPAD2_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([6.0, 12.0]),
    IconPathCommand::LineTo([10.0, 12.0]),
    IconPathCommand::MoveTo([8.0, 10.0]),
    IconPathCommand::LineTo([8.0, 14.0]),
];
static GAMEPAD2_PATH_2: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([15.0, 11.0]),
    IconPathCommand::LineTo([15.0, 11.01]),
];
static GAMEPAD2_PATH_3: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([18.0, 13.0]),
    IconPathCommand::LineTo([18.0, 13.01]),
];
static GAMEPAD2_SHAPES: &[IconShape] = &[
    IconShape::Path(GAMEPAD2_PATH_0),
    IconShape::Path(GAMEPAD2_PATH_1),
    IconShape::Path(GAMEPAD2_PATH_2),
    IconShape::Path(GAMEPAD2_PATH_3),
];
static GAMEPAD2_SVG: &str = r#"<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
  class="icon icon-tabler icons-tabler-outline icon-tabler-device-gamepad"
><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M2 8a2 2 0 0 1 2 -2h16a2 2 0 0 1 2 2v8a2 2 0 0 1 -2 2h-16a2 2 0 0 1 -2 -2l0 -8" /><path d="M6 12h4m-2 -2v4" /><path d="M15 11l0 .01" /><path d="M18 13l0 .01" /></svg>"#;
static GAMEPAD2: IconData = IconData {
    name: "device-gamepad",
    shapes: GAMEPAD2_SHAPES,
    svg: GAMEPAD2_SVG,
};

static MONITOR_PLAY_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([3.0, 9.0]),
    IconPathCommand::CubicTo {
        control_a: [3.0, 7.8954],
        control_b: [3.8954, 7.0],
        to: [5.0, 7.0],
    },
    IconPathCommand::LineTo([19.0, 7.0]),
    IconPathCommand::CubicTo {
        control_a: [20.1046, 7.0],
        control_b: [21.0, 7.8954],
        to: [21.0, 9.0],
    },
    IconPathCommand::LineTo([21.0, 18.0]),
    IconPathCommand::CubicTo {
        control_a: [21.0, 19.1046],
        control_b: [20.1046, 20.0],
        to: [19.0, 20.0],
    },
    IconPathCommand::LineTo([5.0, 20.0]),
    IconPathCommand::CubicTo {
        control_a: [3.8954, 20.0],
        control_b: [3.0, 19.1046],
        to: [3.0, 18.0],
    },
    IconPathCommand::LineTo([3.0, 9.0]),
];
static MONITOR_PLAY_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([16.0, 3.0]),
    IconPathCommand::LineTo([12.0, 7.0]),
    IconPathCommand::LineTo([8.0, 3.0]),
];
static MONITOR_PLAY_SHAPES: &[IconShape] = &[
    IconShape::Path(MONITOR_PLAY_PATH_0),
    IconShape::Path(MONITOR_PLAY_PATH_1),
];
static MONITOR_PLAY_SVG: &str = r#"<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
  class="icon icon-tabler icons-tabler-outline icon-tabler-device-tv"
><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M3 9a2 2 0 0 1 2 -2h14a2 2 0 0 1 2 2v9a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2l0 -9" /><path d="M16 3l-4 4l-4 -4" /></svg>"#;
static MONITOR_PLAY: IconData = IconData {
    name: "device-tv",
    shapes: MONITOR_PLAY_SHAPES,
    svg: MONITOR_PLAY_SVG,
};

static PACKAGE_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([12.0, 3.0]),
    IconPathCommand::LineTo([20.0, 7.5]),
    IconPathCommand::LineTo([20.0, 16.5]),
    IconPathCommand::LineTo([12.0, 21.0]),
    IconPathCommand::LineTo([4.0, 16.5]),
    IconPathCommand::LineTo([4.0, 7.5]),
    IconPathCommand::LineTo([12.0, 3.0]),
];
static PACKAGE_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([12.0, 12.0]),
    IconPathCommand::LineTo([20.0, 7.5]),
];
static PACKAGE_PATH_2: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([12.0, 12.0]),
    IconPathCommand::LineTo([12.0, 21.0]),
];
static PACKAGE_PATH_3: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([12.0, 12.0]),
    IconPathCommand::LineTo([4.0, 7.5]),
];
static PACKAGE_PATH_4: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([16.0, 5.25]),
    IconPathCommand::LineTo([8.0, 9.75]),
];
static PACKAGE_SHAPES: &[IconShape] = &[
    IconShape::Path(PACKAGE_PATH_0),
    IconShape::Path(PACKAGE_PATH_1),
    IconShape::Path(PACKAGE_PATH_2),
    IconShape::Path(PACKAGE_PATH_3),
    IconShape::Path(PACKAGE_PATH_4),
];
static PACKAGE_SVG: &str = r#"<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
  class="icon icon-tabler icons-tabler-outline icon-tabler-package"
><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M12 3l8 4.5l0 9l-8 4.5l-8 -4.5l0 -9l8 -4.5" /><path d="M12 12l8 -4.5" /><path d="M12 12l0 9" /><path d="M12 12l-8 -4.5" /><path d="M16 5.25l-8 4.5" /></svg>"#;
static PACKAGE: IconData = IconData {
    name: "package",
    shapes: PACKAGE_SHAPES,
    svg: PACKAGE_SVG,
};

static PALETTE_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([12.0, 21.0]),
    IconPathCommand::CubicTo {
        control_a: [7.0294, 21.0],
        control_b: [3.0, 16.9706],
        to: [3.0, 12.0],
    },
    IconPathCommand::CubicTo {
        control_a: [3.0, 7.0294],
        control_b: [7.0294, 3.0],
        to: [12.0, 3.0],
    },
    IconPathCommand::CubicTo {
        control_a: [16.97, 3.0],
        control_b: [21.0, 6.582],
        to: [21.0, 11.0],
    },
    IconPathCommand::CubicTo {
        control_a: [21.0, 12.06],
        control_b: [20.526, 13.078],
        to: [19.682, 13.828],
    },
    IconPathCommand::CubicTo {
        control_a: [18.838, 14.578],
        control_b: [17.693, 15.0],
        to: [16.5, 15.0],
    },
    IconPathCommand::LineTo([14.0, 15.0]),
    IconPathCommand::CubicTo {
        control_a: [13.082, 14.9852],
        control_b: [12.2719, 15.5973],
        to: [12.0353, 16.4844],
    },
    IconPathCommand::CubicTo {
        control_a: [11.7987, 17.3715],
        control_b: [12.1965, 18.3057],
        to: [13.0, 18.75],
    },
    IconPathCommand::CubicTo {
        control_a: [13.4094, 19.1278],
        control_b: [13.5326, 19.7244],
        to: [13.3064, 20.2334],
    },
    IconPathCommand::CubicTo {
        control_a: [13.0801, 20.7424],
        control_b: [12.5547, 21.0507],
        to: [12.0, 21.0],
    },
];
static PALETTE_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([7.5, 10.5]),
    IconPathCommand::CubicTo {
        control_a: [7.5, 11.0523],
        control_b: [7.9477, 11.5],
        to: [8.5, 11.5],
    },
    IconPathCommand::CubicTo {
        control_a: [9.0523, 11.5],
        control_b: [9.5, 11.0523],
        to: [9.5, 10.5],
    },
    IconPathCommand::CubicTo {
        control_a: [9.5, 9.9477],
        control_b: [9.0523, 9.5],
        to: [8.5, 9.5],
    },
    IconPathCommand::CubicTo {
        control_a: [7.9477, 9.5],
        control_b: [7.5, 9.9477],
        to: [7.5, 10.5],
    },
];
static PALETTE_PATH_2: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([11.5, 7.5]),
    IconPathCommand::CubicTo {
        control_a: [11.5, 8.0523],
        control_b: [11.9477, 8.5],
        to: [12.5, 8.5],
    },
    IconPathCommand::CubicTo {
        control_a: [13.0523, 8.5],
        control_b: [13.5, 8.0523],
        to: [13.5, 7.5],
    },
    IconPathCommand::CubicTo {
        control_a: [13.5, 6.9477],
        control_b: [13.0523, 6.5],
        to: [12.5, 6.5],
    },
    IconPathCommand::CubicTo {
        control_a: [11.9477, 6.5],
        control_b: [11.5, 6.9477],
        to: [11.5, 7.5],
    },
];
static PALETTE_PATH_3: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([15.5, 10.5]),
    IconPathCommand::CubicTo {
        control_a: [15.5, 11.0523],
        control_b: [15.9477, 11.5],
        to: [16.5, 11.5],
    },
    IconPathCommand::CubicTo {
        control_a: [17.0523, 11.5],
        control_b: [17.5, 11.0523],
        to: [17.5, 10.5],
    },
    IconPathCommand::CubicTo {
        control_a: [17.5, 9.9477],
        control_b: [17.0523, 9.5],
        to: [16.5, 9.5],
    },
    IconPathCommand::CubicTo {
        control_a: [15.9477, 9.5],
        control_b: [15.5, 9.9477],
        to: [15.5, 10.5],
    },
];
static PALETTE_SHAPES: &[IconShape] = &[
    IconShape::Path(PALETTE_PATH_0),
    IconShape::Path(PALETTE_PATH_1),
    IconShape::Path(PALETTE_PATH_2),
    IconShape::Path(PALETTE_PATH_3),
];
static PALETTE_SVG: &str = r#"<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
  class="icon icon-tabler icons-tabler-outline icon-tabler-palette"
><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M12 21a9 9 0 0 1 0 -18c4.97 0 9 3.582 9 8c0 1.06 -.474 2.078 -1.318 2.828c-.844 .75 -1.989 1.172 -3.182 1.172h-2.5a2 2 0 0 0 -1 3.75a1.3 1.3 0 0 1 -1 2.25" /><path d="M7.5 10.5a1 1 0 1 0 2 0a1 1 0 1 0 -2 0" /><path d="M11.5 7.5a1 1 0 1 0 2 0a1 1 0 1 0 -2 0" /><path d="M15.5 10.5a1 1 0 1 0 2 0a1 1 0 1 0 -2 0" /></svg>"#;
static PALETTE: IconData = IconData {
    name: "palette",
    shapes: PALETTE_SHAPES,
    svg: PALETTE_SVG,
};

static PUZZLE_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([4.0, 7.0]),
    IconPathCommand::LineTo([7.0, 7.0]),
    IconPathCommand::CubicTo {
        control_a: [7.5523, 7.0],
        control_b: [8.0, 6.5523],
        to: [8.0, 6.0],
    },
    IconPathCommand::LineTo([8.0, 5.0]),
    IconPathCommand::CubicTo {
        control_a: [8.0, 3.8954],
        control_b: [8.8954, 3.0],
        to: [10.0, 3.0],
    },
    IconPathCommand::CubicTo {
        control_a: [11.1046, 3.0],
        control_b: [12.0, 3.8954],
        to: [12.0, 5.0],
    },
    IconPathCommand::LineTo([12.0, 6.0]),
    IconPathCommand::CubicTo {
        control_a: [12.0, 6.5523],
        control_b: [12.4477, 7.0],
        to: [13.0, 7.0],
    },
    IconPathCommand::LineTo([16.0, 7.0]),
    IconPathCommand::CubicTo {
        control_a: [16.5523, 7.0],
        control_b: [17.0, 7.4477],
        to: [17.0, 8.0],
    },
    IconPathCommand::LineTo([17.0, 11.0]),
    IconPathCommand::CubicTo {
        control_a: [17.0, 11.5523],
        control_b: [17.4477, 12.0],
        to: [18.0, 12.0],
    },
    IconPathCommand::LineTo([19.0, 12.0]),
    IconPathCommand::CubicTo {
        control_a: [20.1046, 12.0],
        control_b: [21.0, 12.8954],
        to: [21.0, 14.0],
    },
    IconPathCommand::CubicTo {
        control_a: [21.0, 15.1046],
        control_b: [20.1046, 16.0],
        to: [19.0, 16.0],
    },
    IconPathCommand::LineTo([18.0, 16.0]),
    IconPathCommand::CubicTo {
        control_a: [17.4477, 16.0],
        control_b: [17.0, 16.4477],
        to: [17.0, 17.0],
    },
    IconPathCommand::LineTo([17.0, 20.0]),
    IconPathCommand::CubicTo {
        control_a: [17.0, 20.5523],
        control_b: [16.5523, 21.0],
        to: [16.0, 21.0],
    },
    IconPathCommand::LineTo([13.0, 21.0]),
    IconPathCommand::CubicTo {
        control_a: [12.4477, 21.0],
        control_b: [12.0, 20.5523],
        to: [12.0, 20.0],
    },
    IconPathCommand::LineTo([12.0, 19.0]),
    IconPathCommand::CubicTo {
        control_a: [12.0, 17.8954],
        control_b: [11.1046, 17.0],
        to: [10.0, 17.0],
    },
    IconPathCommand::CubicTo {
        control_a: [8.8954, 17.0],
        control_b: [8.0, 17.8954],
        to: [8.0, 19.0],
    },
    IconPathCommand::LineTo([8.0, 20.0]),
    IconPathCommand::CubicTo {
        control_a: [8.0, 20.5523],
        control_b: [7.5523, 21.0],
        to: [7.0, 21.0],
    },
    IconPathCommand::LineTo([4.0, 21.0]),
    IconPathCommand::CubicTo {
        control_a: [3.4477, 21.0],
        control_b: [3.0, 20.5523],
        to: [3.0, 20.0],
    },
    IconPathCommand::LineTo([3.0, 17.0]),
    IconPathCommand::CubicTo {
        control_a: [3.0, 16.4477],
        control_b: [3.4477, 16.0],
        to: [4.0, 16.0],
    },
    IconPathCommand::LineTo([5.0, 16.0]),
    IconPathCommand::CubicTo {
        control_a: [6.1046, 16.0],
        control_b: [7.0, 15.1046],
        to: [7.0, 14.0],
    },
    IconPathCommand::CubicTo {
        control_a: [7.0, 12.8954],
        control_b: [6.1046, 12.0],
        to: [5.0, 12.0],
    },
    IconPathCommand::LineTo([4.0, 12.0]),
    IconPathCommand::CubicTo {
        control_a: [3.4477, 12.0],
        control_b: [3.0, 11.5523],
        to: [3.0, 11.0],
    },
    IconPathCommand::LineTo([3.0, 8.0]),
    IconPathCommand::CubicTo {
        control_a: [3.0, 7.4477],
        control_b: [3.4477, 7.0],
        to: [4.0, 7.0],
    },
];
static PUZZLE_SHAPES: &[IconShape] = &[IconShape::Path(PUZZLE_PATH_0)];
static PUZZLE_SVG: &str = r#"<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
  class="icon icon-tabler icons-tabler-outline icon-tabler-puzzle"
><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M4 7h3a1 1 0 0 0 1 -1v-1a2 2 0 0 1 4 0v1a1 1 0 0 0 1 1h3a1 1 0 0 1 1 1v3a1 1 0 0 0 1 1h1a2 2 0 0 1 0 4h-1a1 1 0 0 0 -1 1v3a1 1 0 0 1 -1 1h-3a1 1 0 0 1 -1 -1v-1a2 2 0 0 0 -4 0v1a1 1 0 0 1 -1 1h-3a1 1 0 0 1 -1 -1v-3a1 1 0 0 1 1 -1h1a2 2 0 0 0 0 -4h-1a1 1 0 0 1 -1 -1v-3a1 1 0 0 1 1 -1" /></svg>"#;
static PUZZLE: IconData = IconData {
    name: "puzzle",
    shapes: PUZZLE_SHAPES,
    svg: PUZZLE_SVG,
};

static WEBCAM_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([5.0, 10.0]),
    IconPathCommand::CubicTo {
        control_a: [5.0, 13.866],
        control_b: [8.134, 17.0],
        to: [12.0, 17.0],
    },
    IconPathCommand::CubicTo {
        control_a: [15.866, 17.0],
        control_b: [19.0, 13.866],
        to: [19.0, 10.0],
    },
    IconPathCommand::CubicTo {
        control_a: [19.0, 6.134],
        control_b: [15.866, 3.0],
        to: [12.0, 3.0],
    },
    IconPathCommand::CubicTo {
        control_a: [8.134, 3.0],
        control_b: [5.0, 6.134],
        to: [5.0, 10.0],
    },
];
static WEBCAM_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([9.0, 10.0]),
    IconPathCommand::CubicTo {
        control_a: [9.0, 11.6569],
        control_b: [10.3431, 13.0],
        to: [12.0, 13.0],
    },
    IconPathCommand::CubicTo {
        control_a: [13.6569, 13.0],
        control_b: [15.0, 11.6569],
        to: [15.0, 10.0],
    },
    IconPathCommand::CubicTo {
        control_a: [15.0, 8.3431],
        control_b: [13.6569, 7.0],
        to: [12.0, 7.0],
    },
    IconPathCommand::CubicTo {
        control_a: [10.3431, 7.0],
        control_b: [9.0, 8.3431],
        to: [9.0, 10.0],
    },
];
static WEBCAM_PATH_2: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([8.0, 16.0]),
    IconPathCommand::LineTo([5.909, 19.486]),
    IconPathCommand::CubicTo {
        control_a: [5.7239, 19.7948],
        control_b: [5.7192, 20.1793],
        to: [5.8965, 20.4926],
    },
    IconPathCommand::CubicTo {
        control_a: [6.0739, 20.8059],
        control_b: [6.406, 20.9997],
        to: [6.766, 21.0],
    },
    IconPathCommand::LineTo([17.234, 21.0]),
    IconPathCommand::CubicTo {
        control_a: [17.594, 20.9997],
        control_b: [17.9261, 20.8059],
        to: [18.1035, 20.4926],
    },
    IconPathCommand::CubicTo {
        control_a: [18.2808, 20.1793],
        control_b: [18.2761, 19.7948],
        to: [18.091, 19.486],
    },
    IconPathCommand::LineTo([16.0, 16.0]),
];
static WEBCAM_SHAPES: &[IconShape] = &[
    IconShape::Path(WEBCAM_PATH_0),
    IconShape::Path(WEBCAM_PATH_1),
    IconShape::Path(WEBCAM_PATH_2),
];
static WEBCAM_SVG: &str = r#"<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
  class="icon icon-tabler icons-tabler-outline icon-tabler-device-computer-camera"
><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M5 10a7 7 0 1 0 14 0a7 7 0 1 0 -14 0" /><path d="M9 10a3 3 0 1 0 6 0a3 3 0 1 0 -6 0" /><path d="M8 16l-2.091 3.486a1 1 0 0 0 .857 1.514h10.468a1 1 0 0 0 .857 -1.514l-2.091 -3.486" /></svg>"#;
static WEBCAM: IconData = IconData {
    name: "device-computer-camera",
    shapes: WEBCAM_SHAPES,
    svg: WEBCAM_SVG,
};

static WIND_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([5.0, 8.0]),
    IconPathCommand::LineTo([13.5, 8.0]),
    IconPathCommand::CubicTo {
        control_a: [14.7897, 8.0247],
        control_b: [15.8865, 7.064],
        to: [16.0319, 5.7823],
    },
    IconPathCommand::CubicTo {
        control_a: [16.1773, 4.5006],
        control_b: [15.3237, 3.3187],
        to: [14.0612, 3.0537],
    },
    IconPathCommand::CubicTo {
        control_a: [12.7988, 2.7888],
        control_b: [11.5421, 3.5279],
        to: [11.16, 4.76],
    },
];
static WIND_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([3.0, 12.0]),
    IconPathCommand::LineTo([18.5, 12.0]),
    IconPathCommand::CubicTo {
        control_a: [19.7897, 11.9753],
        control_b: [20.8865, 12.936],
        to: [21.0319, 14.2177],
    },
    IconPathCommand::CubicTo {
        control_a: [21.1773, 15.4994],
        control_b: [20.3237, 16.6813],
        to: [19.0612, 16.9463],
    },
    IconPathCommand::CubicTo {
        control_a: [17.7988, 17.2112],
        control_b: [16.5421, 16.4721],
        to: [16.16, 15.24],
    },
];
static WIND_PATH_2: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([4.0, 16.0]),
    IconPathCommand::LineTo([9.5, 16.0]),
    IconPathCommand::CubicTo {
        control_a: [10.7897, 15.9753],
        control_b: [11.8865, 16.936],
        to: [12.0319, 18.2177],
    },
    IconPathCommand::CubicTo {
        control_a: [12.1773, 19.4994],
        control_b: [11.3237, 20.6813],
        to: [10.0612, 20.9463],
    },
    IconPathCommand::CubicTo {
        control_a: [8.7988, 21.2112],
        control_b: [7.5421, 20.4721],
        to: [7.16, 19.24],
    },
];
static WIND_SHAPES: &[IconShape] = &[
    IconShape::Path(WIND_PATH_0),
    IconShape::Path(WIND_PATH_1),
    IconShape::Path(WIND_PATH_2),
];
static WIND_SVG: &str = r#"<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
  class="icon icon-tabler icons-tabler-outline icon-tabler-wind"
><path stroke="none" d="M0 0h24v24H0z" fill="none" /><path d="M5 8h8.5a2.5 2.5 0 1 0 -2.34 -3.24" /><path d="M3 12h15.5a2.5 2.5 0 1 1 -2.34 3.24" /><path d="M4 16h5.5a2.5 2.5 0 1 1 -2.34 3.24" /></svg>"#;
static WIND: IconData = IconData {
    name: "wind",
    shapes: WIND_SHAPES,
    svg: WIND_SVG,
};

#[allow(non_upper_case_globals)]
impl Icon {
    pub const About: Self = Self(&ABOUT);
    pub const Add: Self = Self(&ADD);
    pub const Appearance: Self = Self(&APPEARANCE);
    pub const ArrowLeft: Self = Self(&ARROW_LEFT);
    pub const ArrowRight: Self = Self(&ARROW_RIGHT);
    pub const ArrowUp: Self = Self(&ARROW_UP);
    pub const Bot: Self = Self(&BOT);
    pub const ChevronDown: Self = Self(&CHEVRON_DOWN);
    pub const ChevronRight: Self = Self(&CHEVRON_RIGHT);
    pub const ChevronUp: Self = Self(&CHEVRON_UP);
    pub const Chart: Self = Self(&CHART);
    pub const Close: Self = Self(&CLOSE);
    pub const Eye: Self = Self(&EYE);
    pub const File: Self = Self(&FILE);
    pub const Folder: Self = Self(&FOLDER);
    pub const GitBranch: Self = Self(&GIT_BRANCH);
    pub const Maximize: Self = Self(&MAXIMIZE);
    pub const MessageSquarePlus: Self = Self(&MESSAGE_SQUARE_PLUS);
    pub const Minimize: Self = Self(&MINIMIZE);
    pub const Moon: Self = Self(&MOON);
    pub const More: Self = Self(&MORE);
    pub const Nodes: Self = Self(&NODES);
    pub const Paperclip: Self = Self(&PAPERCLIP);
    pub const Restore: Self = Self(&RESTORE);
    pub const Search: Self = Self(&SEARCH);
    pub const Settings: Self = Self(&SETTINGS);
    pub const ShieldCheck: Self = Self(&SHIELD_CHECK);
    pub const Sidebar: Self = Self(&SIDEBAR);
    pub const Sparkles: Self = Self(&SPARKLES);
    pub const Workspace: Self = Self(&WORKSPACE);
    pub const Activity: Self = Self(&ACTIVITY);
    pub const Atom: Self = Self(&ATOM);
    pub const Blend: Self = Self(&BLEND);
    pub const Bug: Self = Self(&BUG);
    pub const Clapperboard: Self = Self(&CLAPPERBOARD);
    pub const Cpu: Self = Self(&CPU);
    pub const Gamepad2: Self = Self(&GAMEPAD2);
    pub const MonitorPlay: Self = Self(&MONITOR_PLAY);
    pub const Package: Self = Self(&PACKAGE);
    pub const Palette: Self = Self(&PALETTE);
    pub const Puzzle: Self = Self(&PUZZLE);
    pub const Sun: Self = Self(&APPEARANCE);
    pub const Webcam: Self = Self(&WEBCAM);
    pub const Wind: Self = Self(&WIND);
}
