// @generated by scripts/generate_lucide_icons.py from lucide-static 0.544.0.
// Do not edit by hand. Painters rasterize `svg`; shapes stay for tests.
use crate::icon::{Icon, IconData, IconPathCommand, IconShape};

static ABOUT_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([12.0, 16.0]),
    IconPathCommand::LineTo([12.0, 12.0]),
];
static ABOUT_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([12.0, 8.0]),
    IconPathCommand::LineTo([12.01, 8.0]),
];
static ABOUT_SHAPES: &[IconShape] = &[
    IconShape::Circle {
        center: [12.0, 12.0],
        radius: 10.0,
    },
    IconShape::Path(ABOUT_PATH_0),
    IconShape::Path(ABOUT_PATH_1),
];
static ABOUT_SVG: &str = r#"<!-- @license lucide-static v0.544.0 - ISC --><svg
  class="lucide lucide-info"
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
><circle cx="12" cy="12" r="10" /><path d="M12 16v-4" /><path d="M12 8h.01" /></svg>"#;
static ABOUT: IconData = IconData {
    name: "info",
    shapes: ABOUT_SHAPES,
    svg: ABOUT_SVG,
};

static ADD_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([5.0, 12.0]),
    IconPathCommand::LineTo([19.0, 12.0]),
];
static ADD_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([12.0, 5.0]),
    IconPathCommand::LineTo([12.0, 19.0]),
];
static ADD_SHAPES: &[IconShape] = &[IconShape::Path(ADD_PATH_0), IconShape::Path(ADD_PATH_1)];
static ADD_SVG: &str = r#"<!-- @license lucide-static v0.544.0 - ISC --><svg
  class="lucide lucide-plus"
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
><path d="M5 12h14" /><path d="M12 5v14" /></svg>"#;
static ADD: IconData = IconData {
    name: "plus",
    shapes: ADD_SHAPES,
    svg: ADD_SVG,
};

static APPEARANCE_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([12.0, 2.0]),
    IconPathCommand::LineTo([12.0, 4.0]),
];
static APPEARANCE_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([12.0, 20.0]),
    IconPathCommand::LineTo([12.0, 22.0]),
];
static APPEARANCE_PATH_2: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([4.93, 4.93]),
    IconPathCommand::LineTo([6.34, 6.34]),
];
static APPEARANCE_PATH_3: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([17.66, 17.66]),
    IconPathCommand::LineTo([19.07, 19.07]),
];
static APPEARANCE_PATH_4: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([2.0, 12.0]),
    IconPathCommand::LineTo([4.0, 12.0]),
];
static APPEARANCE_PATH_5: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([20.0, 12.0]),
    IconPathCommand::LineTo([22.0, 12.0]),
];
static APPEARANCE_PATH_6: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([6.34, 17.66]),
    IconPathCommand::LineTo([4.93, 19.07]),
];
static APPEARANCE_PATH_7: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([19.07, 4.93]),
    IconPathCommand::LineTo([17.66, 6.34]),
];
static APPEARANCE_SHAPES: &[IconShape] = &[
    IconShape::Circle {
        center: [12.0, 12.0],
        radius: 4.0,
    },
    IconShape::Path(APPEARANCE_PATH_0),
    IconShape::Path(APPEARANCE_PATH_1),
    IconShape::Path(APPEARANCE_PATH_2),
    IconShape::Path(APPEARANCE_PATH_3),
    IconShape::Path(APPEARANCE_PATH_4),
    IconShape::Path(APPEARANCE_PATH_5),
    IconShape::Path(APPEARANCE_PATH_6),
    IconShape::Path(APPEARANCE_PATH_7),
];
static APPEARANCE_SVG: &str = r#"<!-- @license lucide-static v0.544.0 - ISC --><svg
  class="lucide lucide-sun"
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
><circle cx="12" cy="12" r="4" /><path d="M12 2v2" /><path d="M12 20v2" /><path d="m4.93 4.93 1.41 1.41" /><path d="m17.66 17.66 1.41 1.41" /><path d="M2 12h2" /><path d="M20 12h2" /><path d="m6.34 17.66-1.41 1.41" /><path d="m19.07 4.93-1.41 1.41" /></svg>"#;
static APPEARANCE: IconData = IconData {
    name: "sun",
    shapes: APPEARANCE_SHAPES,
    svg: APPEARANCE_SVG,
};

static ARROW_LEFT_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([12.0, 19.0]),
    IconPathCommand::LineTo([5.0, 12.0]),
    IconPathCommand::LineTo([12.0, 5.0]),
];
static ARROW_LEFT_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([19.0, 12.0]),
    IconPathCommand::LineTo([5.0, 12.0]),
];
static ARROW_LEFT_SHAPES: &[IconShape] = &[
    IconShape::Path(ARROW_LEFT_PATH_0),
    IconShape::Path(ARROW_LEFT_PATH_1),
];
static ARROW_LEFT_SVG: &str = r#"<!-- @license lucide-static v0.544.0 - ISC --><svg
  class="lucide lucide-arrow-left"
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
><path d="m12 19-7-7 7-7" /><path d="M19 12H5" /></svg>"#;
static ARROW_LEFT: IconData = IconData {
    name: "arrow-left",
    shapes: ARROW_LEFT_SHAPES,
    svg: ARROW_LEFT_SVG,
};

static ARROW_RIGHT_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([5.0, 12.0]),
    IconPathCommand::LineTo([19.0, 12.0]),
];
static ARROW_RIGHT_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([12.0, 5.0]),
    IconPathCommand::LineTo([19.0, 12.0]),
    IconPathCommand::LineTo([12.0, 19.0]),
];
static ARROW_RIGHT_SHAPES: &[IconShape] = &[
    IconShape::Path(ARROW_RIGHT_PATH_0),
    IconShape::Path(ARROW_RIGHT_PATH_1),
];
static ARROW_RIGHT_SVG: &str = r#"<!-- @license lucide-static v0.544.0 - ISC --><svg
  class="lucide lucide-arrow-right"
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
><path d="M5 12h14" /><path d="m12 5 7 7-7 7" /></svg>"#;
static ARROW_RIGHT: IconData = IconData {
    name: "arrow-right",
    shapes: ARROW_RIGHT_SHAPES,
    svg: ARROW_RIGHT_SVG,
};

static ARROW_UP_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([5.0, 12.0]),
    IconPathCommand::LineTo([12.0, 5.0]),
    IconPathCommand::LineTo([19.0, 12.0]),
];
static ARROW_UP_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([12.0, 19.0]),
    IconPathCommand::LineTo([12.0, 5.0]),
];
static ARROW_UP_SHAPES: &[IconShape] = &[
    IconShape::Path(ARROW_UP_PATH_0),
    IconShape::Path(ARROW_UP_PATH_1),
];
static ARROW_UP_SVG: &str = r#"<!-- @license lucide-static v0.544.0 - ISC --><svg
  class="lucide lucide-arrow-up"
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
><path d="m5 12 7-7 7 7" /><path d="M12 19V5" /></svg>"#;
static ARROW_UP: IconData = IconData {
    name: "arrow-up",
    shapes: ARROW_UP_SHAPES,
    svg: ARROW_UP_SVG,
};

static BOT_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([12.0, 8.0]),
    IconPathCommand::LineTo([12.0, 4.0]),
    IconPathCommand::LineTo([8.0, 4.0]),
];
static BOT_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([2.0, 14.0]),
    IconPathCommand::LineTo([4.0, 14.0]),
];
static BOT_PATH_2: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([20.0, 14.0]),
    IconPathCommand::LineTo([22.0, 14.0]),
];
static BOT_PATH_3: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([15.0, 13.0]),
    IconPathCommand::LineTo([15.0, 15.0]),
];
static BOT_PATH_4: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([9.0, 13.0]),
    IconPathCommand::LineTo([9.0, 15.0]),
];
static BOT_SHAPES: &[IconShape] = &[
    IconShape::Path(BOT_PATH_0),
    IconShape::RoundedRect {
        origin: [4.0, 8.0],
        size: [16.0, 12.0],
        radius: 2.0,
    },
    IconShape::Path(BOT_PATH_1),
    IconShape::Path(BOT_PATH_2),
    IconShape::Path(BOT_PATH_3),
    IconShape::Path(BOT_PATH_4),
];
static BOT_SVG: &str = r#"<!-- @license lucide-static v0.544.0 - ISC --><svg
  class="lucide lucide-bot"
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
><path d="M12 8V4H8" /><rect width="16" height="12" x="4" y="8" rx="2" /><path d="M2 14h2" /><path d="M20 14h2" /><path d="M15 13v2" /><path d="M9 13v2" /></svg>"#;
static BOT: IconData = IconData {
    name: "bot",
    shapes: BOT_SHAPES,
    svg: BOT_SVG,
};

static CHEVRON_DOWN_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([6.0, 9.0]),
    IconPathCommand::LineTo([12.0, 15.0]),
    IconPathCommand::LineTo([18.0, 9.0]),
];
static CHEVRON_DOWN_SHAPES: &[IconShape] = &[IconShape::Path(CHEVRON_DOWN_PATH_0)];
static CHEVRON_DOWN_SVG: &str = r#"<!-- @license lucide-static v0.544.0 - ISC --><svg
  class="lucide lucide-chevron-down"
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
><path d="m6 9 6 6 6-6" /></svg>"#;
static CHEVRON_DOWN: IconData = IconData {
    name: "chevron-down",
    shapes: CHEVRON_DOWN_SHAPES,
    svg: CHEVRON_DOWN_SVG,
};

static CHEVRON_RIGHT_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([9.0, 18.0]),
    IconPathCommand::LineTo([15.0, 12.0]),
    IconPathCommand::LineTo([9.0, 6.0]),
];
static CHEVRON_RIGHT_SHAPES: &[IconShape] = &[IconShape::Path(CHEVRON_RIGHT_PATH_0)];
static CHEVRON_RIGHT_SVG: &str = r#"<!-- @license lucide-static v0.544.0 - ISC --><svg
  class="lucide lucide-chevron-right"
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
><path d="m9 18 6-6-6-6" /></svg>"#;
static CHEVRON_RIGHT: IconData = IconData {
    name: "chevron-right",
    shapes: CHEVRON_RIGHT_SHAPES,
    svg: CHEVRON_RIGHT_SVG,
};

static CHEVRON_UP_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([18.0, 15.0]),
    IconPathCommand::LineTo([12.0, 9.0]),
    IconPathCommand::LineTo([6.0, 15.0]),
];
static CHEVRON_UP_SHAPES: &[IconShape] = &[IconShape::Path(CHEVRON_UP_PATH_0)];
static CHEVRON_UP_SVG: &str = r#"<!-- @license lucide-static v0.544.0 - ISC --><svg
  class="lucide lucide-chevron-up"
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
><path d="m18 15-6-6-6 6" /></svg>"#;
static CHEVRON_UP: IconData = IconData {
    name: "chevron-up",
    shapes: CHEVRON_UP_SHAPES,
    svg: CHEVRON_UP_SVG,
};

static CHART_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([3.0, 3.0]),
    IconPathCommand::LineTo([3.0, 19.0]),
    IconPathCommand::CubicTo {
        control_a: [3.0, 20.1046],
        control_b: [3.8954, 21.0],
        to: [5.0, 21.0],
    },
    IconPathCommand::LineTo([21.0, 21.0]),
];
static CHART_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([19.0, 9.0]),
    IconPathCommand::LineTo([14.0, 14.0]),
    IconPathCommand::LineTo([10.0, 10.0]),
    IconPathCommand::LineTo([7.0, 13.0]),
];
static CHART_SHAPES: &[IconShape] = &[IconShape::Path(CHART_PATH_0), IconShape::Path(CHART_PATH_1)];
static CHART_SVG: &str = r#"<!-- @license lucide-static v0.544.0 - ISC --><svg
  class="lucide lucide-chart-line"
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
><path d="M3 3v16a2 2 0 0 0 2 2h16" /><path d="m19 9-5 5-4-4-3 3" /></svg>"#;
static CHART: IconData = IconData {
    name: "chart-line",
    shapes: CHART_SHAPES,
    svg: CHART_SVG,
};

static CLOSE_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([18.0, 6.0]),
    IconPathCommand::LineTo([6.0, 18.0]),
];
static CLOSE_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([6.0, 6.0]),
    IconPathCommand::LineTo([18.0, 18.0]),
];
static CLOSE_SHAPES: &[IconShape] = &[IconShape::Path(CLOSE_PATH_0), IconShape::Path(CLOSE_PATH_1)];
static CLOSE_SVG: &str = r#"<!-- @license lucide-static v0.544.0 - ISC --><svg
  class="lucide lucide-x"
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
><path d="M18 6 6 18" /><path d="m6 6 12 12" /></svg>"#;
static CLOSE: IconData = IconData {
    name: "x",
    shapes: CLOSE_SHAPES,
    svg: CLOSE_SVG,
};

static EYE_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([2.062, 12.348]),
    IconPathCommand::CubicTo {
        control_a: [1.9787, 12.1235],
        control_b: [1.9787, 11.8765],
        to: [2.062, 11.652],
    },
    IconPathCommand::CubicTo {
        control_a: [3.722, 7.6269],
        control_b: [7.646, 5.0006],
        to: [12.0, 5.0006],
    },
    IconPathCommand::CubicTo {
        control_a: [16.354, 5.0006],
        control_b: [20.278, 7.6269],
        to: [21.938, 11.652],
    },
    IconPathCommand::CubicTo {
        control_a: [22.0213, 11.8765],
        control_b: [22.0213, 12.1235],
        to: [21.938, 12.348],
    },
    IconPathCommand::CubicTo {
        control_a: [20.278, 16.3731],
        control_b: [16.354, 18.9994],
        to: [12.0, 18.9994],
    },
    IconPathCommand::CubicTo {
        control_a: [7.646, 18.9994],
        control_b: [3.722, 16.3731],
        to: [2.062, 12.348],
    },
];
static EYE_SHAPES: &[IconShape] = &[
    IconShape::Path(EYE_PATH_0),
    IconShape::Circle {
        center: [12.0, 12.0],
        radius: 3.0,
    },
];
static EYE_SVG: &str = r#"<!-- @license lucide-static v0.544.0 - ISC --><svg
  class="lucide lucide-eye"
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
><path d="M2.062 12.348a1 1 0 0 1 0-.696 10.75 10.75 0 0 1 19.876 0 1 1 0 0 1 0 .696 10.75 10.75 0 0 1-19.876 0" /><circle cx="12" cy="12" r="3" /></svg>"#;
static EYE: IconData = IconData {
    name: "eye",
    shapes: EYE_SHAPES,
    svg: EYE_SVG,
};

static FILE_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([15.0, 2.0]),
    IconPathCommand::LineTo([6.0, 2.0]),
    IconPathCommand::CubicTo {
        control_a: [4.8954, 2.0],
        control_b: [4.0, 2.8954],
        to: [4.0, 4.0],
    },
    IconPathCommand::LineTo([4.0, 20.0]),
    IconPathCommand::CubicTo {
        control_a: [4.0, 21.1046],
        control_b: [4.8954, 22.0],
        to: [6.0, 22.0],
    },
    IconPathCommand::LineTo([18.0, 22.0]),
    IconPathCommand::CubicTo {
        control_a: [19.1046, 22.0],
        control_b: [20.0, 21.1046],
        to: [20.0, 20.0],
    },
    IconPathCommand::LineTo([20.0, 7.0]),
    IconPathCommand::Close,
];
static FILE_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([14.0, 2.0]),
    IconPathCommand::LineTo([14.0, 6.0]),
    IconPathCommand::CubicTo {
        control_a: [14.0, 7.1046],
        control_b: [14.8954, 8.0],
        to: [16.0, 8.0],
    },
    IconPathCommand::LineTo([20.0, 8.0]),
];
static FILE_SHAPES: &[IconShape] = &[IconShape::Path(FILE_PATH_0), IconShape::Path(FILE_PATH_1)];
static FILE_SVG: &str = r#"<!-- @license lucide-static v0.544.0 - ISC --><svg
  class="lucide lucide-file"
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
><path d="M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7Z" /><path d="M14 2v4a2 2 0 0 0 2 2h4" /></svg>"#;
static FILE: IconData = IconData {
    name: "file",
    shapes: FILE_SHAPES,
    svg: FILE_SVG,
};

static FOLDER_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([20.0, 20.0]),
    IconPathCommand::CubicTo {
        control_a: [21.1046, 20.0],
        control_b: [22.0, 19.1046],
        to: [22.0, 18.0],
    },
    IconPathCommand::LineTo([22.0, 8.0]),
    IconPathCommand::CubicTo {
        control_a: [22.0, 6.8954],
        control_b: [21.1046, 6.0],
        to: [20.0, 6.0],
    },
    IconPathCommand::LineTo([12.1, 6.0]),
    IconPathCommand::CubicTo {
        control_a: [11.4203, 6.0067],
        control_b: [10.7838, 5.6677],
        to: [10.41, 5.1],
    },
    IconPathCommand::LineTo([9.6, 3.9]),
    IconPathCommand::CubicTo {
        control_a: [9.2301, 3.3383],
        control_b: [8.6026, 3.0001],
        to: [7.93, 3.0],
    },
    IconPathCommand::LineTo([4.0, 3.0]),
    IconPathCommand::CubicTo {
        control_a: [2.8954, 3.0],
        control_b: [2.0, 3.8954],
        to: [2.0, 5.0],
    },
    IconPathCommand::LineTo([2.0, 18.0]),
    IconPathCommand::CubicTo {
        control_a: [2.0, 19.1046],
        control_b: [2.8954, 20.0],
        to: [4.0, 20.0],
    },
    IconPathCommand::Close,
];
static FOLDER_SHAPES: &[IconShape] = &[IconShape::Path(FOLDER_PATH_0)];
static FOLDER_SVG: &str = r#"<!-- @license lucide-static v0.544.0 - ISC --><svg
  class="lucide lucide-folder"
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
><path d="M20 20a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.9a2 2 0 0 1-1.69-.9L9.6 3.9A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2Z" /></svg>"#;
static FOLDER: IconData = IconData {
    name: "folder",
    shapes: FOLDER_SHAPES,
    svg: FOLDER_SVG,
};

static GIT_BRANCH_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([6.0, 3.0]),
    IconPathCommand::LineTo([6.0, 15.0]),
];
static GIT_BRANCH_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([18.0, 9.0]),
    IconPathCommand::CubicTo {
        control_a: [18.0, 13.9706],
        control_b: [13.9706, 18.0],
        to: [9.0, 18.0],
    },
];
static GIT_BRANCH_SHAPES: &[IconShape] = &[
    IconShape::Path(GIT_BRANCH_PATH_0),
    IconShape::Circle {
        center: [18.0, 6.0],
        radius: 3.0,
    },
    IconShape::Circle {
        center: [6.0, 18.0],
        radius: 3.0,
    },
    IconShape::Path(GIT_BRANCH_PATH_1),
];
static GIT_BRANCH_SVG: &str = r#"<!-- @license lucide-static v0.544.0 - ISC --><svg
  class="lucide lucide-git-branch"
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
><line x1="6" x2="6" y1="3" y2="15" /><circle cx="18" cy="6" r="3" /><circle cx="6" cy="18" r="3" /><path d="M18 9a9 9 0 0 1-9 9" /></svg>"#;
static GIT_BRANCH: IconData = IconData {
    name: "git-branch",
    shapes: GIT_BRANCH_SHAPES,
    svg: GIT_BRANCH_SVG,
};

static MAXIMIZE_SHAPES: &[IconShape] = &[IconShape::RoundedRect {
    origin: [3.0, 3.0],
    size: [18.0, 18.0],
    radius: 2.0,
}];
static MAXIMIZE_SVG: &str = r#"<!-- @license lucide-static v0.544.0 - ISC --><svg
  class="lucide lucide-square"
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
><rect width="18" height="18" x="3" y="3" rx="2" /></svg>"#;
static MAXIMIZE: IconData = IconData {
    name: "square",
    shapes: MAXIMIZE_SHAPES,
    svg: MAXIMIZE_SVG,
};

static MESSAGE_SQUARE_PLUS_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([22.0, 17.0]),
    IconPathCommand::CubicTo {
        control_a: [22.0, 18.1046],
        control_b: [21.1046, 19.0],
        to: [20.0, 19.0],
    },
    IconPathCommand::LineTo([6.828, 19.0]),
    IconPathCommand::CubicTo {
        control_a: [6.2976, 19.0001],
        control_b: [5.789, 19.2109],
        to: [5.414, 19.586],
    },
    IconPathCommand::LineTo([3.212, 21.788]),
    IconPathCommand::CubicTo {
        control_a: [3.0089, 21.991],
        control_b: [2.7036, 22.0517],
        to: [2.4383, 21.9419],
    },
    IconPathCommand::CubicTo {
        control_a: [2.173, 21.832],
        control_b: [2.0, 21.5731],
        to: [2.0, 21.286],
    },
    IconPathCommand::LineTo([2.0, 5.0]),
    IconPathCommand::CubicTo {
        control_a: [2.0, 3.8954],
        control_b: [2.8954, 3.0],
        to: [4.0, 3.0],
    },
    IconPathCommand::LineTo([20.0, 3.0]),
    IconPathCommand::CubicTo {
        control_a: [21.1046, 3.0],
        control_b: [22.0, 3.8954],
        to: [22.0, 5.0],
    },
    IconPathCommand::Close,
];
static MESSAGE_SQUARE_PLUS_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([12.0, 8.0]),
    IconPathCommand::LineTo([12.0, 14.0]),
];
static MESSAGE_SQUARE_PLUS_PATH_2: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([9.0, 11.0]),
    IconPathCommand::LineTo([15.0, 11.0]),
];
static MESSAGE_SQUARE_PLUS_SHAPES: &[IconShape] = &[
    IconShape::Path(MESSAGE_SQUARE_PLUS_PATH_0),
    IconShape::Path(MESSAGE_SQUARE_PLUS_PATH_1),
    IconShape::Path(MESSAGE_SQUARE_PLUS_PATH_2),
];
static MESSAGE_SQUARE_PLUS_SVG: &str = r#"<!-- @license lucide-static v0.544.0 - ISC --><svg
  class="lucide lucide-message-square-plus"
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
><path d="M22 17a2 2 0 0 1-2 2H6.828a2 2 0 0 0-1.414.586l-2.202 2.202A.71.71 0 0 1 2 21.286V5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2z" /><path d="M12 8v6" /><path d="M9 11h6" /></svg>"#;
static MESSAGE_SQUARE_PLUS: IconData = IconData {
    name: "message-square-plus",
    shapes: MESSAGE_SQUARE_PLUS_SHAPES,
    svg: MESSAGE_SQUARE_PLUS_SVG,
};

static MINIMIZE_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([5.0, 12.0]),
    IconPathCommand::LineTo([19.0, 12.0]),
];
static MINIMIZE_SHAPES: &[IconShape] = &[IconShape::Path(MINIMIZE_PATH_0)];
static MINIMIZE_SVG: &str = r#"<!-- @license lucide-static v0.544.0 - ISC --><svg
  class="lucide lucide-minus"
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
><path d="M5 12h14" /></svg>"#;
static MINIMIZE: IconData = IconData {
    name: "minus",
    shapes: MINIMIZE_SHAPES,
    svg: MINIMIZE_SVG,
};

static MOON_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([20.985, 12.486]),
    IconPathCommand::CubicTo {
        control_a: [20.7239, 17.3235],
        control_b: [16.6804, 21.0863],
        to: [11.8366, 20.9994],
    },
    IconPathCommand::CubicTo {
        control_a: [6.9929, 20.9125],
        control_b: [3.087, 17.007],
        to: [2.9996, 12.1633],
    },
    IconPathCommand::CubicTo {
        control_a: [2.9121, 7.3195],
        control_b: [6.6745, 3.2757],
        to: [11.512, 3.014],
    },
    IconPathCommand::CubicTo {
        control_a: [11.917, 2.992],
        control_b: [12.129, 3.474],
        to: [11.914, 3.817],
    },
    IconPathCommand::CubicTo {
        control_a: [10.4332, 6.1863],
        control_b: [10.7837, 9.2641],
        to: [12.7593, 11.2397],
    },
    IconPathCommand::CubicTo {
        control_a: [14.7349, 13.2153],
        control_b: [17.8127, 13.5658],
        to: [20.182, 12.085],
    },
    IconPathCommand::CubicTo {
        control_a: [20.526, 11.87],
        control_b: [21.007, 12.081],
        to: [20.985, 12.486],
    },
];
static MOON_SHAPES: &[IconShape] = &[IconShape::Path(MOON_PATH_0)];
static MOON_SVG: &str = r#"<!-- @license lucide-static v0.544.0 - ISC --><svg
  class="lucide lucide-moon"
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
><path d="M20.985 12.486a9 9 0 1 1-9.473-9.472c.405-.022.617.46.402.803a6 6 0 0 0 8.268 8.268c.344-.215.825-.004.803.401" /></svg>"#;
static MOON: IconData = IconData {
    name: "moon",
    shapes: MOON_SHAPES,
    svg: MOON_SVG,
};

static NODES_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([8.59, 13.51]),
    IconPathCommand::LineTo([15.42, 17.49]),
];
static NODES_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([15.41, 6.51]),
    IconPathCommand::LineTo([8.59, 10.49]),
];
static NODES_SHAPES: &[IconShape] = &[
    IconShape::Circle {
        center: [18.0, 5.0],
        radius: 3.0,
    },
    IconShape::Circle {
        center: [6.0, 12.0],
        radius: 3.0,
    },
    IconShape::Circle {
        center: [18.0, 19.0],
        radius: 3.0,
    },
    IconShape::Path(NODES_PATH_0),
    IconShape::Path(NODES_PATH_1),
];
static NODES_SVG: &str = r#"<!-- @license lucide-static v0.544.0 - ISC --><svg
  class="lucide lucide-share-2"
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
><circle cx="18" cy="5" r="3" /><circle cx="6" cy="12" r="3" /><circle cx="18" cy="19" r="3" /><line x1="8.59" x2="15.42" y1="13.51" y2="17.49" /><line x1="15.41" x2="8.59" y1="6.51" y2="10.49" /></svg>"#;
static NODES: IconData = IconData {
    name: "share-2",
    shapes: NODES_SHAPES,
    svg: NODES_SVG,
};

static PAPERCLIP_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([16.0, 6.0]),
    IconPathCommand::LineTo([7.586, 14.586]),
    IconPathCommand::CubicTo {
        control_a: [6.8048, 15.3672],
        control_b: [6.8048, 16.6338],
        to: [7.586, 17.415],
    },
    IconPathCommand::CubicTo {
        control_a: [8.3672, 18.1962],
        control_b: [9.6338, 18.1962],
        to: [10.415, 17.415],
    },
    IconPathCommand::LineTo([18.829, 8.829]),
    IconPathCommand::CubicTo {
        control_a: [19.8395, 7.8185],
        control_b: [20.2342, 6.3456],
        to: [19.8643, 4.9652],
    },
    IconPathCommand::CubicTo {
        control_a: [19.4944, 3.5848],
        control_b: [18.4162, 2.5066],
        to: [17.0358, 2.1367],
    },
    IconPathCommand::CubicTo {
        control_a: [15.6554, 1.7668],
        control_b: [14.1825, 2.1615],
        to: [13.172, 3.172],
    },
    IconPathCommand::LineTo([4.793, 11.723]),
    IconPathCommand::CubicTo {
        control_a: [3.2567, 13.2345],
        control_b: [2.649, 15.4539],
        to: [3.2012, 17.5372],
    },
    IconPathCommand::CubicTo {
        control_a: [3.7534, 19.6205],
        control_b: [5.3805, 21.2476],
        to: [7.4638, 21.7998],
    },
    IconPathCommand::CubicTo {
        control_a: [9.5471, 22.352],
        control_b: [11.7665, 21.7443],
        to: [13.278, 20.208],
    },
    IconPathCommand::LineTo([21.657, 11.657]),
];
static PAPERCLIP_SHAPES: &[IconShape] = &[IconShape::Path(PAPERCLIP_PATH_0)];
static PAPERCLIP_SVG: &str = r#"<!-- @license lucide-static v0.544.0 - ISC --><svg
  class="lucide lucide-paperclip"
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
><path d="m16 6-8.414 8.586a2 2 0 0 0 2.829 2.829l8.414-8.586a4 4 0 1 0-5.657-5.657l-8.379 8.551a6 6 0 1 0 8.485 8.485l8.379-8.551" /></svg>"#;
static PAPERCLIP: IconData = IconData {
    name: "paperclip",
    shapes: PAPERCLIP_SHAPES,
    svg: PAPERCLIP_SVG,
};

static RESTORE_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([4.0, 16.0]),
    IconPathCommand::CubicTo {
        control_a: [2.9, 16.0],
        control_b: [2.0, 15.1],
        to: [2.0, 14.0],
    },
    IconPathCommand::LineTo([2.0, 4.0]),
    IconPathCommand::CubicTo {
        control_a: [2.0, 2.9],
        control_b: [2.9, 2.0],
        to: [4.0, 2.0],
    },
    IconPathCommand::LineTo([14.0, 2.0]),
    IconPathCommand::CubicTo {
        control_a: [15.1, 2.0],
        control_b: [16.0, 2.9],
        to: [16.0, 4.0],
    },
];
static RESTORE_SHAPES: &[IconShape] = &[
    IconShape::RoundedRect {
        origin: [8.0, 8.0],
        size: [14.0, 14.0],
        radius: 2.0,
    },
    IconShape::Path(RESTORE_PATH_0),
];
static RESTORE_SVG: &str = r#"<!-- @license lucide-static v0.544.0 - ISC --><svg
  class="lucide lucide-copy"
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
><rect width="14" height="14" x="8" y="8" rx="2" ry="2" /><path d="M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2" /></svg>"#;
static RESTORE: IconData = IconData {
    name: "copy",
    shapes: RESTORE_SHAPES,
    svg: RESTORE_SVG,
};

static SEARCH_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([21.0, 21.0]),
    IconPathCommand::LineTo([16.66, 16.66]),
];
static SEARCH_SHAPES: &[IconShape] = &[
    IconShape::Path(SEARCH_PATH_0),
    IconShape::Circle {
        center: [11.0, 11.0],
        radius: 8.0,
    },
];
static SEARCH_SVG: &str = r#"<!-- @license lucide-static v0.544.0 - ISC --><svg
  class="lucide lucide-search"
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
><path d="m21 21-4.34-4.34" /><circle cx="11" cy="11" r="8" /></svg>"#;
static SEARCH: IconData = IconData {
    name: "search",
    shapes: SEARCH_SHAPES,
    svg: SEARCH_SVG,
};

static SETTINGS_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([9.671, 4.136]),
    IconPathCommand::CubicTo {
        control_a: [9.7852, 2.9348],
        control_b: [10.7939, 2.0174],
        to: [12.0005, 2.0174],
    },
    IconPathCommand::CubicTo {
        control_a: [13.2071, 2.0174],
        control_b: [14.2158, 2.9348],
        to: [14.33, 4.136],
    },
    IconPathCommand::CubicTo {
        control_a: [14.3972, 4.8959],
        control_b: [14.8307, 5.5754],
        to: [15.4915, 5.9567],
    },
    IconPathCommand::CubicTo {
        control_a: [16.1523, 6.3379],
        control_b: [16.9574, 6.3731],
        to: [17.649, 6.051],
    },
    IconPathCommand::CubicTo {
        control_a: [18.7452, 5.5533],
        control_b: [20.0402, 5.9686],
        to: [20.6425, 7.0111],
    },
    IconPathCommand::CubicTo {
        control_a: [21.2448, 8.0536],
        control_b: [20.9577, 9.3829],
        to: [19.979, 10.084],
    },
    IconPathCommand::CubicTo {
        control_a: [19.3547, 10.522],
        control_b: [18.983, 11.2369],
        to: [18.983, 11.9995],
    },
    IconPathCommand::CubicTo {
        control_a: [18.983, 12.7621],
        control_b: [19.3547, 13.477],
        to: [19.979, 13.915],
    },
    IconPathCommand::CubicTo {
        control_a: [20.9577, 14.6161],
        control_b: [21.2448, 15.9454],
        to: [20.6425, 16.9879],
    },
    IconPathCommand::CubicTo {
        control_a: [20.0402, 18.0304],
        control_b: [18.7452, 18.4457],
        to: [17.649, 17.948],
    },
    IconPathCommand::CubicTo {
        control_a: [16.9574, 17.6259],
        control_b: [16.1523, 17.6611],
        to: [15.4915, 18.0423],
    },
    IconPathCommand::CubicTo {
        control_a: [14.8307, 18.4236],
        control_b: [14.3972, 19.1031],
        to: [14.33, 19.863],
    },
    IconPathCommand::CubicTo {
        control_a: [14.2158, 21.0642],
        control_b: [13.2071, 21.9816],
        to: [12.0005, 21.9816],
    },
    IconPathCommand::CubicTo {
        control_a: [10.7939, 21.9816],
        control_b: [9.7852, 21.0642],
        to: [9.671, 19.863],
    },
    IconPathCommand::CubicTo {
        control_a: [9.6039, 19.1028],
        control_b: [9.1703, 18.423],
        to: [8.5092, 18.0417],
    },
    IconPathCommand::CubicTo {
        control_a: [7.8481, 17.6604],
        control_b: [7.0427, 17.6254],
        to: [6.351, 17.948],
    },
    IconPathCommand::CubicTo {
        control_a: [5.2548, 18.4457],
        control_b: [3.9598, 18.0304],
        to: [3.3575, 16.9879],
    },
    IconPathCommand::CubicTo {
        control_a: [2.7552, 15.9454],
        control_b: [3.0423, 14.6161],
        to: [4.021, 13.915],
    },
    IconPathCommand::CubicTo {
        control_a: [4.6453, 13.477],
        control_b: [5.017, 12.7621],
        to: [5.017, 11.9995],
    },
    IconPathCommand::CubicTo {
        control_a: [5.017, 11.2369],
        control_b: [4.6453, 10.522],
        to: [4.021, 10.084],
    },
    IconPathCommand::CubicTo {
        control_a: [3.0437, 9.3826],
        control_b: [2.7574, 8.0544],
        to: [3.359, 7.0127],
    },
    IconPathCommand::CubicTo {
        control_a: [3.9606, 5.971],
        control_b: [5.254, 5.5551],
        to: [6.35, 6.051],
    },
    IconPathCommand::CubicTo {
        control_a: [7.0416, 6.3731],
        control_b: [7.8467, 6.3379],
        to: [8.5075, 5.9567],
    },
    IconPathCommand::CubicTo {
        control_a: [9.1683, 5.5754],
        control_b: [9.6018, 4.8959],
        to: [9.669, 4.136],
    },
];
static SETTINGS_SHAPES: &[IconShape] = &[
    IconShape::Path(SETTINGS_PATH_0),
    IconShape::Circle {
        center: [12.0, 12.0],
        radius: 3.0,
    },
];
static SETTINGS_SVG: &str = r#"<!-- @license lucide-static v0.544.0 - ISC --><svg
  class="lucide lucide-settings"
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
><path d="M9.671 4.136a2.34 2.34 0 0 1 4.659 0 2.34 2.34 0 0 0 3.319 1.915 2.34 2.34 0 0 1 2.33 4.033 2.34 2.34 0 0 0 0 3.831 2.34 2.34 0 0 1-2.33 4.033 2.34 2.34 0 0 0-3.319 1.915 2.34 2.34 0 0 1-4.659 0 2.34 2.34 0 0 0-3.32-1.915 2.34 2.34 0 0 1-2.33-4.033 2.34 2.34 0 0 0 0-3.831A2.34 2.34 0 0 1 6.35 6.051a2.34 2.34 0 0 0 3.319-1.915" /><circle cx="12" cy="12" r="3" /></svg>"#;
static SETTINGS: IconData = IconData {
    name: "settings",
    shapes: SETTINGS_SHAPES,
    svg: SETTINGS_SVG,
};

static SHIELD_CHECK_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([20.0, 13.0]),
    IconPathCommand::CubicTo {
        control_a: [20.0, 18.0],
        control_b: [16.5, 20.5],
        to: [12.34, 21.95],
    },
    IconPathCommand::CubicTo {
        control_a: [12.1222, 22.0238],
        control_b: [11.8855, 22.0203],
        to: [11.67, 21.94],
    },
    IconPathCommand::CubicTo {
        control_a: [7.5, 20.5],
        control_b: [4.0, 18.0],
        to: [4.0, 13.0],
    },
    IconPathCommand::LineTo([4.0, 6.0]),
    IconPathCommand::CubicTo {
        control_a: [4.0, 5.4477],
        control_b: [4.4477, 5.0],
        to: [5.0, 5.0],
    },
    IconPathCommand::CubicTo {
        control_a: [7.0, 5.0],
        control_b: [9.5, 3.8],
        to: [11.24, 2.28],
    },
    IconPathCommand::CubicTo {
        control_a: [11.6777, 1.9061],
        control_b: [12.3223, 1.9061],
        to: [12.76, 2.28],
    },
    IconPathCommand::CubicTo {
        control_a: [14.51, 3.81],
        control_b: [17.0, 5.0],
        to: [19.0, 5.0],
    },
    IconPathCommand::CubicTo {
        control_a: [19.5523, 5.0],
        control_b: [20.0, 5.4477],
        to: [20.0, 6.0],
    },
    IconPathCommand::Close,
];
static SHIELD_CHECK_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([9.0, 12.0]),
    IconPathCommand::LineTo([11.0, 14.0]),
    IconPathCommand::LineTo([15.0, 10.0]),
];
static SHIELD_CHECK_SHAPES: &[IconShape] = &[
    IconShape::Path(SHIELD_CHECK_PATH_0),
    IconShape::Path(SHIELD_CHECK_PATH_1),
];
static SHIELD_CHECK_SVG: &str = r#"<!-- @license lucide-static v0.544.0 - ISC --><svg
  class="lucide lucide-shield-check"
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
><path d="M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z" /><path d="m9 12 2 2 4-4" /></svg>"#;
static SHIELD_CHECK: IconData = IconData {
    name: "shield-check",
    shapes: SHIELD_CHECK_SHAPES,
    svg: SHIELD_CHECK_SVG,
};

static SIDEBAR_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([9.0, 3.0]),
    IconPathCommand::LineTo([9.0, 21.0]),
];
static SIDEBAR_SHAPES: &[IconShape] = &[
    IconShape::RoundedRect {
        origin: [3.0, 3.0],
        size: [18.0, 18.0],
        radius: 2.0,
    },
    IconShape::Path(SIDEBAR_PATH_0),
];
static SIDEBAR_SVG: &str = r#"<!-- @license lucide-static v0.544.0 - ISC --><svg
  class="lucide lucide-panel-left"
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
><rect width="18" height="18" x="3" y="3" rx="2" /><path d="M9 3v18" /></svg>"#;
static SIDEBAR: IconData = IconData {
    name: "panel-left",
    shapes: SIDEBAR_SHAPES,
    svg: SIDEBAR_SVG,
};

static SPARKLES_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([11.017, 2.814]),
    IconPathCommand::CubicTo {
        control_a: [11.1054, 2.3407],
        control_b: [11.5185, 1.9976],
        to: [12.0, 1.9976],
    },
    IconPathCommand::CubicTo {
        control_a: [12.4815, 1.9976],
        control_b: [12.8946, 2.3407],
        to: [12.983, 2.814],
    },
    IconPathCommand::LineTo([14.034, 8.372]),
    IconPathCommand::CubicTo {
        control_a: [14.1868, 9.1807],
        control_b: [14.8193, 9.8132],
        to: [15.628, 9.966],
    },
    IconPathCommand::LineTo([21.186, 11.017]),
    IconPathCommand::CubicTo {
        control_a: [21.6593, 11.1054],
        control_b: [22.0024, 11.5185],
        to: [22.0024, 12.0],
    },
    IconPathCommand::CubicTo {
        control_a: [22.0024, 12.4815],
        control_b: [21.6593, 12.8946],
        to: [21.186, 12.983],
    },
    IconPathCommand::LineTo([15.628, 14.034]),
    IconPathCommand::CubicTo {
        control_a: [14.8193, 14.1868],
        control_b: [14.1868, 14.8193],
        to: [14.034, 15.628],
    },
    IconPathCommand::LineTo([12.983, 21.186]),
    IconPathCommand::CubicTo {
        control_a: [12.8946, 21.6593],
        control_b: [12.4815, 22.0024],
        to: [12.0, 22.0024],
    },
    IconPathCommand::CubicTo {
        control_a: [11.5185, 22.0024],
        control_b: [11.1054, 21.6593],
        to: [11.017, 21.186],
    },
    IconPathCommand::LineTo([9.966, 15.628]),
    IconPathCommand::CubicTo {
        control_a: [9.8132, 14.8193],
        control_b: [9.1807, 14.1868],
        to: [8.372, 14.034],
    },
    IconPathCommand::LineTo([2.814, 12.983]),
    IconPathCommand::CubicTo {
        control_a: [2.3407, 12.8946],
        control_b: [1.9976, 12.4815],
        to: [1.9976, 12.0],
    },
    IconPathCommand::CubicTo {
        control_a: [1.9976, 11.5185],
        control_b: [2.3407, 11.1054],
        to: [2.814, 11.017],
    },
    IconPathCommand::LineTo([8.372, 9.966]),
    IconPathCommand::CubicTo {
        control_a: [9.1807, 9.8132],
        control_b: [9.8132, 9.1807],
        to: [9.966, 8.372],
    },
    IconPathCommand::Close,
];
static SPARKLES_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([20.0, 2.0]),
    IconPathCommand::LineTo([20.0, 6.0]),
];
static SPARKLES_PATH_2: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([22.0, 4.0]),
    IconPathCommand::LineTo([18.0, 4.0]),
];
static SPARKLES_SHAPES: &[IconShape] = &[
    IconShape::Path(SPARKLES_PATH_0),
    IconShape::Path(SPARKLES_PATH_1),
    IconShape::Path(SPARKLES_PATH_2),
    IconShape::Circle {
        center: [4.0, 20.0],
        radius: 2.0,
    },
];
static SPARKLES_SVG: &str = r#"<!-- @license lucide-static v0.544.0 - ISC --><svg
  class="lucide lucide-sparkles"
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
><path d="M11.017 2.814a1 1 0 0 1 1.966 0l1.051 5.558a2 2 0 0 0 1.594 1.594l5.558 1.051a1 1 0 0 1 0 1.966l-5.558 1.051a2 2 0 0 0-1.594 1.594l-1.051 5.558a1 1 0 0 1-1.966 0l-1.051-5.558a2 2 0 0 0-1.594-1.594l-5.558-1.051a1 1 0 0 1 0-1.966l5.558-1.051a2 2 0 0 0 1.594-1.594z" /><path d="M20 2v4" /><path d="M22 4h-4" /><circle cx="4" cy="20" r="2" /></svg>"#;
static SPARKLES: IconData = IconData {
    name: "sparkles",
    shapes: SPARKLES_SHAPES,
    svg: SPARKLES_SVG,
};

static WORKSPACE_SHAPES: &[IconShape] = &[
    IconShape::RoundedRect {
        origin: [3.0, 3.0],
        size: [7.0, 9.0],
        radius: 1.0,
    },
    IconShape::RoundedRect {
        origin: [14.0, 3.0],
        size: [7.0, 5.0],
        radius: 1.0,
    },
    IconShape::RoundedRect {
        origin: [14.0, 12.0],
        size: [7.0, 9.0],
        radius: 1.0,
    },
    IconShape::RoundedRect {
        origin: [3.0, 16.0],
        size: [7.0, 5.0],
        radius: 1.0,
    },
];
static WORKSPACE_SVG: &str = r#"<!-- @license lucide-static v0.544.0 - ISC --><svg
  class="lucide lucide-layout-dashboard"
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
><rect width="7" height="9" x="3" y="3" rx="1" /><rect width="7" height="5" x="14" y="3" rx="1" /><rect width="7" height="9" x="14" y="12" rx="1" /><rect width="7" height="5" x="3" y="16" rx="1" /></svg>"#;
static WORKSPACE: IconData = IconData {
    name: "layout-dashboard",
    shapes: WORKSPACE_SHAPES,
    svg: WORKSPACE_SVG,
};

static ACTIVITY_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([22.0, 12.0]),
    IconPathCommand::LineTo([19.52, 12.0]),
    IconPathCommand::CubicTo {
        control_a: [18.6218, 11.9981],
        control_b: [17.8325, 12.5952],
        to: [17.59, 13.46],
    },
    IconPathCommand::LineTo([15.24, 21.82]),
    IconPathCommand::CubicTo {
        control_a: [15.2089, 21.9267],
        control_b: [15.1111, 22.0],
        to: [15.0, 22.0],
    },
    IconPathCommand::CubicTo {
        control_a: [14.8889, 22.0],
        control_b: [14.7911, 21.9267],
        to: [14.76, 21.82],
    },
    IconPathCommand::LineTo([9.24, 2.18]),
    IconPathCommand::CubicTo {
        control_a: [9.2089, 2.0733],
        control_b: [9.1111, 2.0],
        to: [9.0, 2.0],
    },
    IconPathCommand::CubicTo {
        control_a: [8.8889, 2.0],
        control_b: [8.7911, 2.0733],
        to: [8.76, 2.18],
    },
    IconPathCommand::LineTo([6.41, 10.54]),
    IconPathCommand::CubicTo {
        control_a: [6.1685, 11.4013],
        control_b: [5.3845, 11.9974],
        to: [4.49, 12.0],
    },
    IconPathCommand::LineTo([2.0, 12.0]),
];
static ACTIVITY_SHAPES: &[IconShape] = &[IconShape::Path(ACTIVITY_PATH_0)];
static ACTIVITY_SVG: &str = r#"<!-- @license lucide-static v0.544.0 - ISC --><svg
  class="lucide lucide-activity"
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
><path d="M22 12h-2.48a2 2 0 0 0-1.93 1.46l-2.35 8.36a.25.25 0 0 1-.48 0L9.24 2.18a.25.25 0 0 0-.48 0l-2.35 8.36A2 2 0 0 1 4.49 12H2" /></svg>"#;
static ACTIVITY: IconData = IconData {
    name: "activity",
    shapes: ACTIVITY_SHAPES,
    svg: ACTIVITY_SVG,
};

static ATOM_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([20.2, 20.2]),
    IconPathCommand::CubicTo {
        control_a: [22.24, 18.17],
        control_b: [20.22, 12.84],
        to: [15.7, 8.3],
    },
    IconPathCommand::CubicTo {
        control_a: [11.16, 3.78],
        control_b: [5.83, 1.76],
        to: [3.8, 3.8],
    },
    IconPathCommand::CubicTo {
        control_a: [1.76, 5.83],
        control_b: [3.78, 11.16],
        to: [8.3, 15.7],
    },
    IconPathCommand::CubicTo {
        control_a: [12.84, 20.22],
        control_b: [18.17, 22.24],
        to: [20.2, 20.2],
    },
    IconPathCommand::Close,
];
static ATOM_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([15.7, 15.7]),
    IconPathCommand::CubicTo {
        control_a: [20.22, 11.16],
        control_b: [22.24, 5.83],
        to: [20.2, 3.8],
    },
    IconPathCommand::CubicTo {
        control_a: [18.17, 1.76],
        control_b: [12.84, 3.78],
        to: [8.3, 8.3],
    },
    IconPathCommand::CubicTo {
        control_a: [3.78, 12.84],
        control_b: [1.76, 18.17],
        to: [3.8, 20.2],
    },
    IconPathCommand::CubicTo {
        control_a: [5.83, 22.24],
        control_b: [11.16, 20.22],
        to: [15.7, 15.7],
    },
    IconPathCommand::Close,
];
static ATOM_SHAPES: &[IconShape] = &[
    IconShape::Circle {
        center: [12.0, 12.0],
        radius: 1.0,
    },
    IconShape::Path(ATOM_PATH_0),
    IconShape::Path(ATOM_PATH_1),
];
static ATOM_SVG: &str = r#"<!-- @license lucide-static v0.544.0 - ISC --><svg
  class="lucide lucide-atom"
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
><circle cx="12" cy="12" r="1" /><path d="M20.2 20.2c2.04-2.03.02-7.36-4.5-11.9-4.54-4.52-9.87-6.54-11.9-4.5-2.04 2.03-.02 7.36 4.5 11.9 4.54 4.52 9.87 6.54 11.9 4.5Z" /><path d="M15.7 15.7c4.52-4.54 6.54-9.87 4.5-11.9-2.03-2.04-7.36-.02-11.9 4.5-4.52 4.54-6.54 9.87-4.5 11.9 2.03 2.04 7.36.02 11.9-4.5Z" /></svg>"#;
static ATOM: IconData = IconData {
    name: "atom",
    shapes: ATOM_SHAPES,
    svg: ATOM_SVG,
};

static BLEND_SHAPES: &[IconShape] = &[
    IconShape::Circle {
        center: [9.0, 9.0],
        radius: 7.0,
    },
    IconShape::Circle {
        center: [15.0, 15.0],
        radius: 7.0,
    },
];
static BLEND_SVG: &str = r#"<!-- @license lucide-static v0.544.0 - ISC --><svg
  class="lucide lucide-blend"
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
><circle cx="9" cy="9" r="7" /><circle cx="15" cy="15" r="7" /></svg>"#;
static BLEND: IconData = IconData {
    name: "blend",
    shapes: BLEND_SHAPES,
    svg: BLEND_SVG,
};

static BUG_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([12.0, 20.0]),
    IconPathCommand::LineTo([12.0, 11.0]),
];
static BUG_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([14.0, 7.0]),
    IconPathCommand::CubicTo {
        control_a: [16.2091, 7.0],
        control_b: [18.0, 8.7909],
        to: [18.0, 11.0],
    },
    IconPathCommand::LineTo([18.0, 14.0]),
    IconPathCommand::CubicTo {
        control_a: [18.0, 17.3137],
        control_b: [15.3137, 20.0],
        to: [12.0, 20.0],
    },
    IconPathCommand::CubicTo {
        control_a: [8.6863, 20.0],
        control_b: [6.0, 17.3137],
        to: [6.0, 14.0],
    },
    IconPathCommand::LineTo([6.0, 11.0]),
    IconPathCommand::CubicTo {
        control_a: [6.0, 8.7909],
        control_b: [7.7909, 7.0],
        to: [10.0, 7.0],
    },
    IconPathCommand::Close,
];
static BUG_PATH_2: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([14.12, 3.88]),
    IconPathCommand::LineTo([16.0, 2.0]),
];
static BUG_PATH_3: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([21.0, 21.0]),
    IconPathCommand::CubicTo {
        control_a: [21.0024, 18.863],
        control_b: [19.3246, 17.1015],
        to: [17.19, 17.0],
    },
];
static BUG_PATH_4: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([21.0, 5.0]),
    IconPathCommand::CubicTo {
        control_a: [20.9977, 7.0333],
        control_b: [19.4704, 8.7413],
        to: [17.45, 8.97],
    },
];
static BUG_PATH_5: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([22.0, 13.0]),
    IconPathCommand::LineTo([18.0, 13.0]),
];
static BUG_PATH_6: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([3.0, 21.0]),
    IconPathCommand::CubicTo {
        control_a: [2.9976, 18.863],
        control_b: [4.6754, 17.1015],
        to: [6.81, 17.0],
    },
];
static BUG_PATH_7: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([3.0, 5.0]),
    IconPathCommand::CubicTo {
        control_a: [3.0023, 7.0333],
        control_b: [4.5296, 8.7413],
        to: [6.55, 8.97],
    },
];
static BUG_PATH_8: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([6.0, 13.0]),
    IconPathCommand::LineTo([2.0, 13.0]),
];
static BUG_PATH_9: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([8.0, 2.0]),
    IconPathCommand::LineTo([9.88, 3.88]),
];
static BUG_PATH_10: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([9.0, 7.13]),
    IconPathCommand::LineTo([9.0, 6.0]),
    IconPathCommand::CubicTo {
        control_a: [9.0, 4.3431],
        control_b: [10.3431, 3.0],
        to: [12.0, 3.0],
    },
    IconPathCommand::CubicTo {
        control_a: [13.6569, 3.0],
        control_b: [15.0, 4.3431],
        to: [15.0, 6.0],
    },
    IconPathCommand::LineTo([15.0, 7.13]),
];
static BUG_SHAPES: &[IconShape] = &[
    IconShape::Path(BUG_PATH_0),
    IconShape::Path(BUG_PATH_1),
    IconShape::Path(BUG_PATH_2),
    IconShape::Path(BUG_PATH_3),
    IconShape::Path(BUG_PATH_4),
    IconShape::Path(BUG_PATH_5),
    IconShape::Path(BUG_PATH_6),
    IconShape::Path(BUG_PATH_7),
    IconShape::Path(BUG_PATH_8),
    IconShape::Path(BUG_PATH_9),
    IconShape::Path(BUG_PATH_10),
];
static BUG_SVG: &str = r#"<!-- @license lucide-static v0.544.0 - ISC --><svg
  class="lucide lucide-bug"
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
><path d="M12 20v-9" /><path d="M14 7a4 4 0 0 1 4 4v3a6 6 0 0 1-12 0v-3a4 4 0 0 1 4-4z" /><path d="M14.12 3.88 16 2" /><path d="M21 21a4 4 0 0 0-3.81-4" /><path d="M21 5a4 4 0 0 1-3.55 3.97" /><path d="M22 13h-4" /><path d="M3 21a4 4 0 0 1 3.81-4" /><path d="M3 5a4 4 0 0 0 3.55 3.97" /><path d="M6 13H2" /><path d="m8 2 1.88 1.88" /><path d="M9 7.13V6a3 3 0 1 1 6 0v1.13" /></svg>"#;
static BUG: IconData = IconData {
    name: "bug",
    shapes: BUG_SHAPES,
    svg: BUG_SVG,
};

static CLAPPERBOARD_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([20.2, 6.0]),
    IconPathCommand::LineTo([3.0, 11.0]),
    IconPathCommand::LineTo([2.1, 8.6]),
    IconPathCommand::CubicTo {
        control_a: [1.8, 7.5],
        control_b: [2.4, 6.4],
        to: [3.4, 6.1],
    },
    IconPathCommand::LineTo([16.9, 2.1]),
    IconPathCommand::CubicTo {
        control_a: [18.0, 1.8],
        control_b: [19.1, 2.4],
        to: [19.4, 3.4],
    },
    IconPathCommand::Close,
];
static CLAPPERBOARD_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([6.2, 5.3]),
    IconPathCommand::LineTo([9.3, 9.2]),
];
static CLAPPERBOARD_PATH_2: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([12.4, 3.4]),
    IconPathCommand::LineTo([15.5, 7.4]),
];
static CLAPPERBOARD_PATH_3: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([3.0, 11.0]),
    IconPathCommand::LineTo([21.0, 11.0]),
    IconPathCommand::LineTo([21.0, 19.0]),
    IconPathCommand::CubicTo {
        control_a: [21.0, 20.1046],
        control_b: [20.1046, 21.0],
        to: [19.0, 21.0],
    },
    IconPathCommand::LineTo([5.0, 21.0]),
    IconPathCommand::CubicTo {
        control_a: [3.8954, 21.0],
        control_b: [3.0, 20.1046],
        to: [3.0, 19.0],
    },
    IconPathCommand::Close,
];
static CLAPPERBOARD_SHAPES: &[IconShape] = &[
    IconShape::Path(CLAPPERBOARD_PATH_0),
    IconShape::Path(CLAPPERBOARD_PATH_1),
    IconShape::Path(CLAPPERBOARD_PATH_2),
    IconShape::Path(CLAPPERBOARD_PATH_3),
];
static CLAPPERBOARD_SVG: &str = r#"<!-- @license lucide-static v0.544.0 - ISC --><svg
  class="lucide lucide-clapperboard"
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
><path d="M20.2 6 3 11l-.9-2.4c-.3-1.1.3-2.2 1.3-2.5l13.5-4c1.1-.3 2.2.3 2.5 1.3Z" /><path d="m6.2 5.3 3.1 3.9" /><path d="m12.4 3.4 3.1 4" /><path d="M3 11h18v8a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2Z" /></svg>"#;
static CLAPPERBOARD: IconData = IconData {
    name: "clapperboard",
    shapes: CLAPPERBOARD_SHAPES,
    svg: CLAPPERBOARD_SVG,
};

static CPU_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([12.0, 20.0]),
    IconPathCommand::LineTo([12.0, 22.0]),
];
static CPU_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([12.0, 2.0]),
    IconPathCommand::LineTo([12.0, 4.0]),
];
static CPU_PATH_2: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([17.0, 20.0]),
    IconPathCommand::LineTo([17.0, 22.0]),
];
static CPU_PATH_3: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([17.0, 2.0]),
    IconPathCommand::LineTo([17.0, 4.0]),
];
static CPU_PATH_4: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([2.0, 12.0]),
    IconPathCommand::LineTo([4.0, 12.0]),
];
static CPU_PATH_5: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([2.0, 17.0]),
    IconPathCommand::LineTo([4.0, 17.0]),
];
static CPU_PATH_6: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([2.0, 7.0]),
    IconPathCommand::LineTo([4.0, 7.0]),
];
static CPU_PATH_7: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([20.0, 12.0]),
    IconPathCommand::LineTo([22.0, 12.0]),
];
static CPU_PATH_8: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([20.0, 17.0]),
    IconPathCommand::LineTo([22.0, 17.0]),
];
static CPU_PATH_9: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([20.0, 7.0]),
    IconPathCommand::LineTo([22.0, 7.0]),
];
static CPU_PATH_10: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([7.0, 20.0]),
    IconPathCommand::LineTo([7.0, 22.0]),
];
static CPU_PATH_11: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([7.0, 2.0]),
    IconPathCommand::LineTo([7.0, 4.0]),
];
static CPU_SHAPES: &[IconShape] = &[
    IconShape::Path(CPU_PATH_0),
    IconShape::Path(CPU_PATH_1),
    IconShape::Path(CPU_PATH_2),
    IconShape::Path(CPU_PATH_3),
    IconShape::Path(CPU_PATH_4),
    IconShape::Path(CPU_PATH_5),
    IconShape::Path(CPU_PATH_6),
    IconShape::Path(CPU_PATH_7),
    IconShape::Path(CPU_PATH_8),
    IconShape::Path(CPU_PATH_9),
    IconShape::Path(CPU_PATH_10),
    IconShape::Path(CPU_PATH_11),
    IconShape::RoundedRect {
        origin: [4.0, 4.0],
        size: [16.0, 16.0],
        radius: 2.0,
    },
    IconShape::RoundedRect {
        origin: [8.0, 8.0],
        size: [8.0, 8.0],
        radius: 1.0,
    },
];
static CPU_SVG: &str = r#"<!-- @license lucide-static v0.544.0 - ISC --><svg
  class="lucide lucide-cpu"
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
><path d="M12 20v2" /><path d="M12 2v2" /><path d="M17 20v2" /><path d="M17 2v2" /><path d="M2 12h2" /><path d="M2 17h2" /><path d="M2 7h2" /><path d="M20 12h2" /><path d="M20 17h2" /><path d="M20 7h2" /><path d="M7 20v2" /><path d="M7 2v2" /><rect x="4" y="4" width="16" height="16" rx="2" /><rect x="8" y="8" width="8" height="8" rx="1" /></svg>"#;
static CPU: IconData = IconData {
    name: "cpu",
    shapes: CPU_SHAPES,
    svg: CPU_SVG,
};

static GAMEPAD2_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([6.0, 11.0]),
    IconPathCommand::LineTo([10.0, 11.0]),
];
static GAMEPAD2_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([8.0, 9.0]),
    IconPathCommand::LineTo([8.0, 13.0]),
];
static GAMEPAD2_PATH_2: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([15.0, 12.0]),
    IconPathCommand::LineTo([15.01, 12.0]),
];
static GAMEPAD2_PATH_3: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([18.0, 10.0]),
    IconPathCommand::LineTo([18.01, 10.0]),
];
static GAMEPAD2_PATH_4: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([17.32, 5.0]),
    IconPathCommand::LineTo([6.68, 5.0]),
    IconPathCommand::CubicTo {
        control_a: [4.63, 5.0005],
        control_b: [2.9121, 6.5508],
        to: [2.702, 8.59],
    },
    IconPathCommand::CubicTo {
        control_a: [2.696, 8.642],
        control_b: [2.692, 8.691],
        to: [2.685, 8.742],
    },
    IconPathCommand::CubicTo {
        control_a: [2.604, 9.416],
        control_b: [2.0, 14.456],
        to: [2.0, 16.0],
    },
    IconPathCommand::CubicTo {
        control_a: [2.0, 17.6569],
        control_b: [3.3431, 19.0],
        to: [5.0, 19.0],
    },
    IconPathCommand::CubicTo {
        control_a: [6.0, 19.0],
        control_b: [6.5, 18.5],
        to: [7.0, 18.0],
    },
    IconPathCommand::LineTo([8.414, 16.586]),
    IconPathCommand::CubicTo {
        control_a: [8.789, 16.2109],
        control_b: [9.2976, 16.0001],
        to: [9.828, 16.0],
    },
    IconPathCommand::LineTo([14.172, 16.0]),
    IconPathCommand::CubicTo {
        control_a: [14.7024, 16.0001],
        control_b: [15.211, 16.2109],
        to: [15.586, 16.586],
    },
    IconPathCommand::LineTo([17.0, 18.0]),
    IconPathCommand::CubicTo {
        control_a: [17.5, 18.5],
        control_b: [18.0, 19.0],
        to: [19.0, 19.0],
    },
    IconPathCommand::CubicTo {
        control_a: [20.6569, 19.0],
        control_b: [22.0, 17.6569],
        to: [22.0, 16.0],
    },
    IconPathCommand::CubicTo {
        control_a: [22.0, 14.455],
        control_b: [21.396, 9.416],
        to: [21.315, 8.742],
    },
    IconPathCommand::CubicTo {
        control_a: [21.308, 8.692],
        control_b: [21.304, 8.642],
        to: [21.298, 8.591],
    },
    IconPathCommand::CubicTo {
        control_a: [21.0883, 6.5514],
        control_b: [19.3704, 5.0005],
        to: [17.32, 5.0],
    },
    IconPathCommand::Close,
];
static GAMEPAD2_SHAPES: &[IconShape] = &[
    IconShape::Path(GAMEPAD2_PATH_0),
    IconShape::Path(GAMEPAD2_PATH_1),
    IconShape::Path(GAMEPAD2_PATH_2),
    IconShape::Path(GAMEPAD2_PATH_3),
    IconShape::Path(GAMEPAD2_PATH_4),
];
static GAMEPAD2_SVG: &str = r#"<!-- @license lucide-static v0.544.0 - ISC --><svg
  class="lucide lucide-gamepad-2"
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
><line x1="6" x2="10" y1="11" y2="11" /><line x1="8" x2="8" y1="9" y2="13" /><line x1="15" x2="15.01" y1="12" y2="12" /><line x1="18" x2="18.01" y1="10" y2="10" /><path d="M17.32 5H6.68a4 4 0 0 0-3.978 3.59c-.006.052-.01.101-.017.152C2.604 9.416 2 14.456 2 16a3 3 0 0 0 3 3c1 0 1.5-.5 2-1l1.414-1.414A2 2 0 0 1 9.828 16h4.344a2 2 0 0 1 1.414.586L17 18c.5.5 1 1 2 1a3 3 0 0 0 3-3c0-1.545-.604-6.584-.685-7.258-.007-.05-.011-.1-.017-.151A4 4 0 0 0 17.32 5z" /></svg>"#;
static GAMEPAD2: IconData = IconData {
    name: "gamepad-2",
    shapes: GAMEPAD2_SHAPES,
    svg: GAMEPAD2_SVG,
};

static MONITOR_PLAY_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([15.033, 9.44]),
    IconPathCommand::CubicTo {
        control_a: [15.2329, 9.5557],
        control_b: [15.3559, 9.7691],
        to: [15.3559, 10.0],
    },
    IconPathCommand::CubicTo {
        control_a: [15.3559, 10.2309],
        control_b: [15.2329, 10.4443],
        to: [15.033, 10.56],
    },
    IconPathCommand::LineTo([10.968, 12.912]),
    IconPathCommand::CubicTo {
        control_a: [10.7682, 13.0276],
        control_b: [10.5218, 13.0276],
        to: [10.322, 12.912],
    },
    IconPathCommand::CubicTo {
        control_a: [10.1222, 12.7964],
        control_b: [9.9994, 12.5828],
        to: [10.0, 12.352],
    },
    IconPathCommand::LineTo([10.0, 7.648]),
    IconPathCommand::CubicTo {
        control_a: [9.9996, 7.4175],
        control_b: [10.1223, 7.2042],
        to: [10.3218, 7.0887],
    },
    IconPathCommand::CubicTo {
        control_a: [10.5213, 6.9732],
        control_b: [10.7672, 6.9729],
        to: [10.967, 7.088],
    },
    IconPathCommand::Close,
];
static MONITOR_PLAY_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([12.0, 17.0]),
    IconPathCommand::LineTo([12.0, 21.0]),
];
static MONITOR_PLAY_PATH_2: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([8.0, 21.0]),
    IconPathCommand::LineTo([16.0, 21.0]),
];
static MONITOR_PLAY_SHAPES: &[IconShape] = &[
    IconShape::Path(MONITOR_PLAY_PATH_0),
    IconShape::Path(MONITOR_PLAY_PATH_1),
    IconShape::Path(MONITOR_PLAY_PATH_2),
    IconShape::RoundedRect {
        origin: [2.0, 3.0],
        size: [20.0, 14.0],
        radius: 2.0,
    },
];
static MONITOR_PLAY_SVG: &str = r#"<!-- @license lucide-static v0.544.0 - ISC --><svg
  class="lucide lucide-monitor-play"
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
><path d="M15.033 9.44a.647.647 0 0 1 0 1.12l-4.065 2.352a.645.645 0 0 1-.968-.56V7.648a.645.645 0 0 1 .967-.56z" /><path d="M12 17v4" /><path d="M8 21h8" /><rect x="2" y="3" width="20" height="14" rx="2" /></svg>"#;
static MONITOR_PLAY: IconData = IconData {
    name: "monitor-play",
    shapes: MONITOR_PLAY_SHAPES,
    svg: MONITOR_PLAY_SVG,
};

static PACKAGE_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([11.0, 21.73]),
    IconPathCommand::CubicTo {
        control_a: [11.6188, 22.0873],
        control_b: [12.3812, 22.0873],
        to: [13.0, 21.73],
    },
    IconPathCommand::LineTo([20.0, 17.73]),
    IconPathCommand::CubicTo {
        control_a: [20.6182, 17.3731],
        control_b: [20.9993, 16.7138],
        to: [21.0, 16.0],
    },
    IconPathCommand::LineTo([21.0, 8.0]),
    IconPathCommand::CubicTo {
        control_a: [20.9993, 7.2862],
        control_b: [20.6182, 6.6269],
        to: [20.0, 6.27],
    },
    IconPathCommand::LineTo([13.0, 2.27]),
    IconPathCommand::CubicTo {
        control_a: [12.3812, 1.9127],
        control_b: [11.6188, 1.9127],
        to: [11.0, 2.27],
    },
    IconPathCommand::LineTo([4.0, 6.27]),
    IconPathCommand::CubicTo {
        control_a: [3.3818, 6.6269],
        control_b: [3.0007, 7.2862],
        to: [3.0, 8.0],
    },
    IconPathCommand::LineTo([3.0, 16.0]),
    IconPathCommand::CubicTo {
        control_a: [3.0007, 16.7138],
        control_b: [3.3818, 17.3731],
        to: [4.0, 17.73],
    },
    IconPathCommand::Close,
];
static PACKAGE_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([12.0, 22.0]),
    IconPathCommand::LineTo([12.0, 12.0]),
];
static PACKAGE_PATH_2: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([3.29, 7.0]),
    IconPathCommand::LineTo([12.0, 12.0]),
    IconPathCommand::LineTo([20.71, 7.0]),
];
static PACKAGE_PATH_3: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([7.5, 4.27]),
    IconPathCommand::LineTo([16.5, 9.42]),
];
static PACKAGE_SHAPES: &[IconShape] = &[
    IconShape::Path(PACKAGE_PATH_0),
    IconShape::Path(PACKAGE_PATH_1),
    IconShape::Path(PACKAGE_PATH_2),
    IconShape::Path(PACKAGE_PATH_3),
];
static PACKAGE_SVG: &str = r#"<!-- @license lucide-static v0.544.0 - ISC --><svg
  class="lucide lucide-package"
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
><path d="M11 21.73a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73z" /><path d="M12 22V12" /><polyline points="3.29 7 12 12 20.71 7" /><path d="m7.5 4.27 9 5.15" /></svg>"#;
static PACKAGE: IconData = IconData {
    name: "package",
    shapes: PACKAGE_SHAPES,
    svg: PACKAGE_SVG,
};

static PALETTE_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([12.0, 22.0]),
    IconPathCommand::CubicTo {
        control_a: [6.4772, 22.0],
        control_b: [2.0, 17.5228],
        to: [2.0, 12.0],
    },
    IconPathCommand::CubicTo {
        control_a: [2.0, 6.4772],
        control_b: [6.4772, 2.0],
        to: [12.0, 2.0],
    },
    IconPathCommand::CubicTo {
        control_a: [17.5228, 2.0],
        control_b: [22.0, 6.0294],
        to: [22.0, 11.0],
    },
    IconPathCommand::CubicTo {
        control_a: [22.0, 13.7614],
        control_b: [19.7614, 16.0],
        to: [17.0, 16.0],
    },
    IconPathCommand::LineTo([14.75, 16.0]),
    IconPathCommand::CubicTo {
        control_a: [14.0871, 16.0],
        control_b: [13.4812, 16.3745],
        to: [13.1848, 16.9674],
    },
    IconPathCommand::CubicTo {
        control_a: [12.8883, 17.5602],
        control_b: [12.9523, 18.2697],
        to: [13.35, 18.8],
    },
    IconPathCommand::LineTo([13.65, 19.2]),
    IconPathCommand::CubicTo {
        control_a: [14.0477, 19.7303],
        control_b: [14.1117, 20.4398],
        to: [13.8152, 21.0326],
    },
    IconPathCommand::CubicTo {
        control_a: [13.5188, 21.6255],
        control_b: [12.9129, 22.0],
        to: [12.25, 22.0],
    },
    IconPathCommand::Close,
];
static PALETTE_SHAPES: &[IconShape] = &[
    IconShape::Path(PALETTE_PATH_0),
    IconShape::Circle {
        center: [13.5, 6.5],
        radius: 0.5,
    },
    IconShape::Circle {
        center: [17.5, 10.5],
        radius: 0.5,
    },
    IconShape::Circle {
        center: [6.5, 12.5],
        radius: 0.5,
    },
    IconShape::Circle {
        center: [8.5, 7.5],
        radius: 0.5,
    },
];
static PALETTE_SVG: &str = r#"<!-- @license lucide-static v0.544.0 - ISC --><svg
  class="lucide lucide-palette"
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
><path d="M12 22a1 1 0 0 1 0-20 10 9 0 0 1 10 9 5 5 0 0 1-5 5h-2.25a1.75 1.75 0 0 0-1.4 2.8l.3.4a1.75 1.75 0 0 1-1.4 2.8z" /><circle cx="13.5" cy="6.5" r=".5" fill="currentColor" /><circle cx="17.5" cy="10.5" r=".5" fill="currentColor" /><circle cx="6.5" cy="12.5" r=".5" fill="currentColor" /><circle cx="8.5" cy="7.5" r=".5" fill="currentColor" /></svg>"#;
static PALETTE: IconData = IconData {
    name: "palette",
    shapes: PALETTE_SHAPES,
    svg: PALETTE_SVG,
};

static PUZZLE_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([15.39, 4.39]),
    IconPathCommand::CubicTo {
        control_a: [15.646, 4.6462],
        control_b: [16.0204, 4.744],
        to: [16.369, 4.6457],
    },
    IconPathCommand::CubicTo {
        control_a: [16.7176, 4.5473],
        control_b: [16.9857, 4.2682],
        to: [17.07, 3.916],
    },
    IconPathCommand::CubicTo {
        control_a: [17.3573, 2.7203],
        control_b: [18.4714, 1.911],
        to: [19.6974, 2.0077],
    },
    IconPathCommand::CubicTo {
        control_a: [20.9233, 2.1044],
        control_b: [21.8969, 3.0783],
        to: [21.9932, 4.3042],
    },
    IconPathCommand::CubicTo {
        control_a: [22.0894, 5.5302],
        control_b: [21.2798, 6.6441],
        to: [20.084, 6.931],
    },
    IconPathCommand::CubicTo {
        control_a: [19.7318, 7.0153],
        control_b: [19.4527, 7.2834],
        to: [19.3543, 7.632],
    },
    IconPathCommand::CubicTo {
        control_a: [19.256, 7.9806],
        control_b: [19.3538, 8.355],
        to: [19.61, 8.611],
    },
    IconPathCommand::LineTo([21.293, 10.293]),
    IconPathCommand::CubicTo {
        control_a: [21.7457, 10.7457],
        control_b: [22.0001, 11.3597],
        to: [22.0001, 12.0],
    },
    IconPathCommand::CubicTo {
        control_a: [22.0001, 12.6403],
        control_b: [21.7457, 13.2543],
        to: [21.293, 13.707],
    },
    IconPathCommand::LineTo([19.61, 15.39]),
    IconPathCommand::CubicTo {
        control_a: [19.354, 15.6462],
        control_b: [18.9796, 15.744],
        to: [18.631, 15.6457],
    },
    IconPathCommand::CubicTo {
        control_a: [18.2824, 15.5473],
        control_b: [18.0143, 15.2682],
        to: [17.93, 14.916],
    },
    IconPathCommand::CubicTo {
        control_a: [17.6427, 13.7203],
        control_b: [16.5286, 12.911],
        to: [15.3026, 13.0077],
    },
    IconPathCommand::CubicTo {
        control_a: [14.0767, 13.1044],
        control_b: [13.1031, 14.0783],
        to: [13.0068, 15.3042],
    },
    IconPathCommand::CubicTo {
        control_a: [12.9106, 16.5302],
        control_b: [13.7202, 17.6441],
        to: [14.916, 17.931],
    },
    IconPathCommand::CubicTo {
        control_a: [15.2682, 18.0153],
        control_b: [15.5473, 18.2834],
        to: [15.6457, 18.632],
    },
    IconPathCommand::CubicTo {
        control_a: [15.744, 18.9806],
        control_b: [15.6462, 19.355],
        to: [15.39, 19.611],
    },
    IconPathCommand::LineTo([13.707, 21.293]),
    IconPathCommand::CubicTo {
        control_a: [13.2543, 21.7457],
        control_b: [12.6403, 22.0001],
        to: [12.0, 22.0001],
    },
    IconPathCommand::CubicTo {
        control_a: [11.3597, 22.0001],
        control_b: [10.7457, 21.7457],
        to: [10.293, 21.293],
    },
    IconPathCommand::LineTo([8.61, 19.61]),
    IconPathCommand::CubicTo {
        control_a: [8.354, 19.3538],
        control_b: [7.9796, 19.256],
        to: [7.631, 19.3543],
    },
    IconPathCommand::CubicTo {
        control_a: [7.2824, 19.4527],
        control_b: [7.0143, 19.7318],
        to: [6.93, 20.084],
    },
    IconPathCommand::CubicTo {
        control_a: [6.6427, 21.2797],
        control_b: [5.5286, 22.089],
        to: [4.3026, 21.9923],
    },
    IconPathCommand::CubicTo {
        control_a: [3.0767, 21.8956],
        control_b: [2.1031, 20.9217],
        to: [2.0068, 19.6958],
    },
    IconPathCommand::CubicTo {
        control_a: [1.9106, 18.4698],
        control_b: [2.7202, 17.3559],
        to: [3.916, 17.069],
    },
    IconPathCommand::CubicTo {
        control_a: [4.2682, 16.9847],
        control_b: [4.5473, 16.7166],
        to: [4.6457, 16.368],
    },
    IconPathCommand::CubicTo {
        control_a: [4.744, 16.0194],
        control_b: [4.6462, 15.645],
        to: [4.39, 15.389],
    },
    IconPathCommand::LineTo([2.707, 13.707]),
    IconPathCommand::CubicTo {
        control_a: [2.2543, 13.2543],
        control_b: [1.9999, 12.6403],
        to: [1.9999, 12.0],
    },
    IconPathCommand::CubicTo {
        control_a: [1.9999, 11.3597],
        control_b: [2.2543, 10.7457],
        to: [2.707, 10.293],
    },
    IconPathCommand::LineTo([4.39, 8.61]),
    IconPathCommand::CubicTo {
        control_a: [4.646, 8.3538],
        control_b: [5.0204, 8.256],
        to: [5.369, 8.3543],
    },
    IconPathCommand::CubicTo {
        control_a: [5.7176, 8.4527],
        control_b: [5.9857, 8.7318],
        to: [6.07, 9.084],
    },
    IconPathCommand::CubicTo {
        control_a: [6.3573, 10.2797],
        control_b: [7.4714, 11.089],
        to: [8.6974, 10.9923],
    },
    IconPathCommand::CubicTo {
        control_a: [9.9233, 10.8956],
        control_b: [10.8969, 9.9217],
        to: [10.9932, 8.6958],
    },
    IconPathCommand::CubicTo {
        control_a: [11.0894, 7.4698],
        control_b: [10.2798, 6.3559],
        to: [9.084, 6.069],
    },
    IconPathCommand::CubicTo {
        control_a: [8.7318, 5.9847],
        control_b: [8.4527, 5.7166],
        to: [8.3543, 5.368],
    },
    IconPathCommand::CubicTo {
        control_a: [8.256, 5.0194],
        control_b: [8.3538, 4.645],
        to: [8.61, 4.389],
    },
    IconPathCommand::LineTo([10.293, 2.707]),
    IconPathCommand::CubicTo {
        control_a: [10.7457, 2.2543],
        control_b: [11.3597, 1.9999],
        to: [12.0, 1.9999],
    },
    IconPathCommand::CubicTo {
        control_a: [12.6403, 1.9999],
        control_b: [13.2543, 2.2543],
        to: [13.707, 2.707],
    },
    IconPathCommand::Close,
];
static PUZZLE_SHAPES: &[IconShape] = &[IconShape::Path(PUZZLE_PATH_0)];
static PUZZLE_SVG: &str = r#"<!-- @license lucide-static v0.544.0 - ISC --><svg
  class="lucide lucide-puzzle"
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
><path d="M15.39 4.39a1 1 0 0 0 1.68-.474 2.5 2.5 0 1 1 3.014 3.015 1 1 0 0 0-.474 1.68l1.683 1.682a2.414 2.414 0 0 1 0 3.414L19.61 15.39a1 1 0 0 1-1.68-.474 2.5 2.5 0 1 0-3.014 3.015 1 1 0 0 1 .474 1.68l-1.683 1.682a2.414 2.414 0 0 1-3.414 0L8.61 19.61a1 1 0 0 0-1.68.474 2.5 2.5 0 1 1-3.014-3.015 1 1 0 0 0 .474-1.68l-1.683-1.682a2.414 2.414 0 0 1 0-3.414L4.39 8.61a1 1 0 0 1 1.68.474 2.5 2.5 0 1 0 3.014-3.015 1 1 0 0 1-.474-1.68l1.683-1.682a2.414 2.414 0 0 1 3.414 0z" /></svg>"#;
static PUZZLE: IconData = IconData {
    name: "puzzle",
    shapes: PUZZLE_SHAPES,
    svg: PUZZLE_SVG,
};

static WEBCAM_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([7.0, 22.0]),
    IconPathCommand::LineTo([17.0, 22.0]),
];
static WEBCAM_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([12.0, 22.0]),
    IconPathCommand::LineTo([12.0, 18.0]),
];
static WEBCAM_SHAPES: &[IconShape] = &[
    IconShape::Circle {
        center: [12.0, 10.0],
        radius: 8.0,
    },
    IconShape::Circle {
        center: [12.0, 10.0],
        radius: 3.0,
    },
    IconShape::Path(WEBCAM_PATH_0),
    IconShape::Path(WEBCAM_PATH_1),
];
static WEBCAM_SVG: &str = r#"<!-- @license lucide-static v0.544.0 - ISC --><svg
  class="lucide lucide-webcam"
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
><circle cx="12" cy="10" r="8" /><circle cx="12" cy="10" r="3" /><path d="M7 22h10" /><path d="M12 22v-4" /></svg>"#;
static WEBCAM: IconData = IconData {
    name: "webcam",
    shapes: WEBCAM_SHAPES,
    svg: WEBCAM_SVG,
};

static WIND_PATH_0: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([12.8, 19.6]),
    IconPathCommand::CubicTo {
        control_a: [13.4961, 20.1221],
        control_b: [14.45, 20.1342],
        to: [15.1591, 19.6298],
    },
    IconPathCommand::CubicTo {
        control_a: [15.8683, 19.1255],
        control_b: [16.1699, 18.2205],
        to: [15.9052, 17.3916],
    },
    IconPathCommand::CubicTo {
        control_a: [15.6405, 16.5627],
        control_b: [14.8702, 16.0],
        to: [14.0, 16.0],
    },
    IconPathCommand::LineTo([2.0, 16.0]),
];
static WIND_PATH_1: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([17.5, 8.0]),
    IconPathCommand::CubicTo {
        control_a: [18.2054, 7.0595],
        control_b: [19.4708, 6.7375],
        to: [20.5399, 7.2265],
    },
    IconPathCommand::CubicTo {
        control_a: [21.609, 7.7156],
        control_b: [22.193, 8.8834],
        to: [21.9427, 10.0321],
    },
    IconPathCommand::CubicTo {
        control_a: [21.6925, 11.1809],
        control_b: [20.6757, 12.0],
        to: [19.5, 12.0],
    },
    IconPathCommand::LineTo([2.0, 12.0]),
];
static WIND_PATH_2: &[IconPathCommand] = &[
    IconPathCommand::MoveTo([9.8, 4.4]),
    IconPathCommand::CubicTo {
        control_a: [10.4961, 3.8779],
        control_b: [11.45, 3.8658],
        to: [12.1591, 4.3702],
    },
    IconPathCommand::CubicTo {
        control_a: [12.8683, 4.8745],
        control_b: [13.1699, 5.7795],
        to: [12.9052, 6.6084],
    },
    IconPathCommand::CubicTo {
        control_a: [12.6405, 7.4373],
        control_b: [11.8702, 8.0],
        to: [11.0, 8.0],
    },
    IconPathCommand::LineTo([2.0, 8.0]),
];
static WIND_SHAPES: &[IconShape] = &[
    IconShape::Path(WIND_PATH_0),
    IconShape::Path(WIND_PATH_1),
    IconShape::Path(WIND_PATH_2),
];
static WIND_SVG: &str = r#"<!-- @license lucide-static v0.544.0 - ISC --><svg
  class="lucide lucide-wind"
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
><path d="M12.8 19.6A2 2 0 1 0 14 16H2" /><path d="M17.5 8a2.5 2.5 0 1 1 2 4H2" /><path d="M9.8 4.4A2 2 0 1 1 11 8H2" /></svg>"#;
static WIND: IconData = IconData {
    name: "wind",
    shapes: WIND_SHAPES,
    svg: WIND_SVG,
};

#[allow(non_upper_case_globals)]
impl Icon {
    pub const About: Self = Self(&ABOUT);
    pub const Add: Self = Self(&ADD);
    pub const Appearance: Self = Self(&APPEARANCE);
    pub const ArrowLeft: Self = Self(&ARROW_LEFT);
    pub const ArrowRight: Self = Self(&ARROW_RIGHT);
    pub const ArrowUp: Self = Self(&ARROW_UP);
    pub const Bot: Self = Self(&BOT);
    pub const ChevronDown: Self = Self(&CHEVRON_DOWN);
    pub const ChevronRight: Self = Self(&CHEVRON_RIGHT);
    pub const ChevronUp: Self = Self(&CHEVRON_UP);
    pub const Chart: Self = Self(&CHART);
    pub const Close: Self = Self(&CLOSE);
    pub const Eye: Self = Self(&EYE);
    pub const File: Self = Self(&FILE);
    pub const Folder: Self = Self(&FOLDER);
    pub const GitBranch: Self = Self(&GIT_BRANCH);
    pub const Maximize: Self = Self(&MAXIMIZE);
    pub const MessageSquarePlus: Self = Self(&MESSAGE_SQUARE_PLUS);
    pub const Minimize: Self = Self(&MINIMIZE);
    pub const Moon: Self = Self(&MOON);
    pub const Nodes: Self = Self(&NODES);
    pub const Paperclip: Self = Self(&PAPERCLIP);
    pub const Restore: Self = Self(&RESTORE);
    pub const Search: Self = Self(&SEARCH);
    pub const Settings: Self = Self(&SETTINGS);
    pub const ShieldCheck: Self = Self(&SHIELD_CHECK);
    pub const Sidebar: Self = Self(&SIDEBAR);
    pub const Sparkles: Self = Self(&SPARKLES);
    pub const Workspace: Self = Self(&WORKSPACE);
    pub const Activity: Self = Self(&ACTIVITY);
    pub const Atom: Self = Self(&ATOM);
    pub const Blend: Self = Self(&BLEND);
    pub const Bug: Self = Self(&BUG);
    pub const Clapperboard: Self = Self(&CLAPPERBOARD);
    pub const Cpu: Self = Self(&CPU);
    pub const Gamepad2: Self = Self(&GAMEPAD2);
    pub const MonitorPlay: Self = Self(&MONITOR_PLAY);
    pub const Package: Self = Self(&PACKAGE);
    pub const Palette: Self = Self(&PALETTE);
    pub const Puzzle: Self = Self(&PUZZLE);
    pub const Sun: Self = Self(&APPEARANCE);
    pub const Webcam: Self = Self(&WEBCAM);
    pub const Wind: Self = Self(&WIND);
}
